// Code generated by ent, DO NOT EDIT.

package recordentity

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/digital-foxy/card-client/store/record/erecord/ent/predicate"
	"github.com/digital-foxy/card-client/store/resource"
	"github.com/digital-foxy/card-fetcher/source"
	"github.com/digital-foxy/toolkit/timestamp"
)

// ID filters vertices based on their ID field.
func ID(id resource.RID) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id resource.RID) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id resource.RID) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...resource.RID) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...resource.RID) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id resource.RID) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id resource.RID) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id resource.RID) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id resource.RID) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldLTE(FieldID, id))
}

// ImportIndex applies equality check predicate on the "import_index" field. It's identical to ImportIndexEQ.
func ImportIndex(v int) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldEQ(FieldImportIndex, v))
}

// ImportTime applies equality check predicate on the "import_time" field. It's identical to ImportTimeEQ.
func ImportTime(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldEQ(FieldImportTime, vc))
}

// NormalizedURL applies equality check predicate on the "normalized_url" field. It's identical to NormalizedURLEQ.
func NormalizedURL(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldEQ(FieldNormalizedURL, v))
}

// DirectURL applies equality check predicate on the "direct_url" field. It's identical to DirectURLEQ.
func DirectURL(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldEQ(FieldDirectURL, v))
}

// PlatformID applies equality check predicate on the "platform_id" field. It's identical to PlatformIDEQ.
func PlatformID(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldEQ(FieldPlatformID, v))
}

// CharacterID applies equality check predicate on the "character_id" field. It's identical to CharacterIDEQ.
func CharacterID(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldEQ(FieldCharacterID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldEQ(FieldTitle, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldEQ(FieldName, v))
}

// CreatorID applies equality check predicate on the "creator_id" field. It's identical to CreatorIDEQ.
func CreatorID(v resource.CID) predicate.RecordEntity {
	vc := string(v)
	return predicate.RecordEntity(sql.FieldEQ(FieldCreatorID, vc))
}

// Tagline applies equality check predicate on the "tagline" field. It's identical to TaglineEQ.
func Tagline(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldEQ(FieldTagline, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldEQ(FieldCreateTime, vc))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldEQ(FieldUpdateTime, vc))
}

// IsFork applies equality check predicate on the "is_fork" field. It's identical to IsForkEQ.
func IsFork(v bool) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldEQ(FieldIsFork, v))
}

// BookUpdateTime applies equality check predicate on the "book_update_time" field. It's identical to BookUpdateTimeEQ.
func BookUpdateTime(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldEQ(FieldBookUpdateTime, vc))
}

// GreetingsCount applies equality check predicate on the "greetings_count" field. It's identical to GreetingsCountEQ.
func GreetingsCount(v int) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldEQ(FieldGreetingsCount, v))
}

// SyncTime applies equality check predicate on the "sync_time" field. It's identical to SyncTimeEQ.
func SyncTime(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldEQ(FieldSyncTime, vc))
}

// ExportedVersion applies equality check predicate on the "exported_version" field. It's identical to ExportedVersionEQ.
func ExportedVersion(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldEQ(FieldExportedVersion, vc))
}

// ExportTime applies equality check predicate on the "export_time" field. It's identical to ExportTimeEQ.
func ExportTime(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldEQ(FieldExportTime, vc))
}

// Favorite applies equality check predicate on the "favorite" field. It's identical to FavoriteEQ.
func Favorite(v bool) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldEQ(FieldFavorite, v))
}

// ImportIndexEQ applies the EQ predicate on the "import_index" field.
func ImportIndexEQ(v int) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldEQ(FieldImportIndex, v))
}

// ImportIndexNEQ applies the NEQ predicate on the "import_index" field.
func ImportIndexNEQ(v int) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldNEQ(FieldImportIndex, v))
}

// ImportIndexIn applies the In predicate on the "import_index" field.
func ImportIndexIn(vs ...int) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldIn(FieldImportIndex, vs...))
}

// ImportIndexNotIn applies the NotIn predicate on the "import_index" field.
func ImportIndexNotIn(vs ...int) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldNotIn(FieldImportIndex, vs...))
}

// ImportIndexGT applies the GT predicate on the "import_index" field.
func ImportIndexGT(v int) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldGT(FieldImportIndex, v))
}

// ImportIndexGTE applies the GTE predicate on the "import_index" field.
func ImportIndexGTE(v int) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldGTE(FieldImportIndex, v))
}

// ImportIndexLT applies the LT predicate on the "import_index" field.
func ImportIndexLT(v int) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldLT(FieldImportIndex, v))
}

// ImportIndexLTE applies the LTE predicate on the "import_index" field.
func ImportIndexLTE(v int) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldLTE(FieldImportIndex, v))
}

// ImportTimeEQ applies the EQ predicate on the "import_time" field.
func ImportTimeEQ(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldEQ(FieldImportTime, vc))
}

// ImportTimeNEQ applies the NEQ predicate on the "import_time" field.
func ImportTimeNEQ(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldNEQ(FieldImportTime, vc))
}

// ImportTimeIn applies the In predicate on the "import_time" field.
func ImportTimeIn(vs ...timestamp.Nano) predicate.RecordEntity {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.RecordEntity(sql.FieldIn(FieldImportTime, v...))
}

// ImportTimeNotIn applies the NotIn predicate on the "import_time" field.
func ImportTimeNotIn(vs ...timestamp.Nano) predicate.RecordEntity {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.RecordEntity(sql.FieldNotIn(FieldImportTime, v...))
}

// ImportTimeGT applies the GT predicate on the "import_time" field.
func ImportTimeGT(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldGT(FieldImportTime, vc))
}

// ImportTimeGTE applies the GTE predicate on the "import_time" field.
func ImportTimeGTE(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldGTE(FieldImportTime, vc))
}

// ImportTimeLT applies the LT predicate on the "import_time" field.
func ImportTimeLT(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldLT(FieldImportTime, vc))
}

// ImportTimeLTE applies the LTE predicate on the "import_time" field.
func ImportTimeLTE(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldLTE(FieldImportTime, vc))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v source.ID) predicate.RecordEntity {
	vc := v
	return predicate.RecordEntity(sql.FieldEQ(FieldSource, vc))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v source.ID) predicate.RecordEntity {
	vc := v
	return predicate.RecordEntity(sql.FieldNEQ(FieldSource, vc))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...source.ID) predicate.RecordEntity {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RecordEntity(sql.FieldIn(FieldSource, v...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...source.ID) predicate.RecordEntity {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RecordEntity(sql.FieldNotIn(FieldSource, v...))
}

// NormalizedURLEQ applies the EQ predicate on the "normalized_url" field.
func NormalizedURLEQ(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldEQ(FieldNormalizedURL, v))
}

// NormalizedURLNEQ applies the NEQ predicate on the "normalized_url" field.
func NormalizedURLNEQ(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldNEQ(FieldNormalizedURL, v))
}

// NormalizedURLIn applies the In predicate on the "normalized_url" field.
func NormalizedURLIn(vs ...string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldIn(FieldNormalizedURL, vs...))
}

// NormalizedURLNotIn applies the NotIn predicate on the "normalized_url" field.
func NormalizedURLNotIn(vs ...string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldNotIn(FieldNormalizedURL, vs...))
}

// NormalizedURLGT applies the GT predicate on the "normalized_url" field.
func NormalizedURLGT(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldGT(FieldNormalizedURL, v))
}

// NormalizedURLGTE applies the GTE predicate on the "normalized_url" field.
func NormalizedURLGTE(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldGTE(FieldNormalizedURL, v))
}

// NormalizedURLLT applies the LT predicate on the "normalized_url" field.
func NormalizedURLLT(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldLT(FieldNormalizedURL, v))
}

// NormalizedURLLTE applies the LTE predicate on the "normalized_url" field.
func NormalizedURLLTE(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldLTE(FieldNormalizedURL, v))
}

// NormalizedURLContains applies the Contains predicate on the "normalized_url" field.
func NormalizedURLContains(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldContains(FieldNormalizedURL, v))
}

// NormalizedURLHasPrefix applies the HasPrefix predicate on the "normalized_url" field.
func NormalizedURLHasPrefix(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldHasPrefix(FieldNormalizedURL, v))
}

// NormalizedURLHasSuffix applies the HasSuffix predicate on the "normalized_url" field.
func NormalizedURLHasSuffix(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldHasSuffix(FieldNormalizedURL, v))
}

// NormalizedURLEqualFold applies the EqualFold predicate on the "normalized_url" field.
func NormalizedURLEqualFold(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldEqualFold(FieldNormalizedURL, v))
}

// NormalizedURLContainsFold applies the ContainsFold predicate on the "normalized_url" field.
func NormalizedURLContainsFold(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldContainsFold(FieldNormalizedURL, v))
}

// DirectURLEQ applies the EQ predicate on the "direct_url" field.
func DirectURLEQ(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldEQ(FieldDirectURL, v))
}

// DirectURLNEQ applies the NEQ predicate on the "direct_url" field.
func DirectURLNEQ(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldNEQ(FieldDirectURL, v))
}

// DirectURLIn applies the In predicate on the "direct_url" field.
func DirectURLIn(vs ...string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldIn(FieldDirectURL, vs...))
}

// DirectURLNotIn applies the NotIn predicate on the "direct_url" field.
func DirectURLNotIn(vs ...string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldNotIn(FieldDirectURL, vs...))
}

// DirectURLGT applies the GT predicate on the "direct_url" field.
func DirectURLGT(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldGT(FieldDirectURL, v))
}

// DirectURLGTE applies the GTE predicate on the "direct_url" field.
func DirectURLGTE(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldGTE(FieldDirectURL, v))
}

// DirectURLLT applies the LT predicate on the "direct_url" field.
func DirectURLLT(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldLT(FieldDirectURL, v))
}

// DirectURLLTE applies the LTE predicate on the "direct_url" field.
func DirectURLLTE(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldLTE(FieldDirectURL, v))
}

// DirectURLContains applies the Contains predicate on the "direct_url" field.
func DirectURLContains(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldContains(FieldDirectURL, v))
}

// DirectURLHasPrefix applies the HasPrefix predicate on the "direct_url" field.
func DirectURLHasPrefix(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldHasPrefix(FieldDirectURL, v))
}

// DirectURLHasSuffix applies the HasSuffix predicate on the "direct_url" field.
func DirectURLHasSuffix(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldHasSuffix(FieldDirectURL, v))
}

// DirectURLEqualFold applies the EqualFold predicate on the "direct_url" field.
func DirectURLEqualFold(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldEqualFold(FieldDirectURL, v))
}

// DirectURLContainsFold applies the ContainsFold predicate on the "direct_url" field.
func DirectURLContainsFold(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldContainsFold(FieldDirectURL, v))
}

// PlatformIDEQ applies the EQ predicate on the "platform_id" field.
func PlatformIDEQ(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldEQ(FieldPlatformID, v))
}

// PlatformIDNEQ applies the NEQ predicate on the "platform_id" field.
func PlatformIDNEQ(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldNEQ(FieldPlatformID, v))
}

// PlatformIDIn applies the In predicate on the "platform_id" field.
func PlatformIDIn(vs ...string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldIn(FieldPlatformID, vs...))
}

// PlatformIDNotIn applies the NotIn predicate on the "platform_id" field.
func PlatformIDNotIn(vs ...string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldNotIn(FieldPlatformID, vs...))
}

// PlatformIDGT applies the GT predicate on the "platform_id" field.
func PlatformIDGT(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldGT(FieldPlatformID, v))
}

// PlatformIDGTE applies the GTE predicate on the "platform_id" field.
func PlatformIDGTE(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldGTE(FieldPlatformID, v))
}

// PlatformIDLT applies the LT predicate on the "platform_id" field.
func PlatformIDLT(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldLT(FieldPlatformID, v))
}

// PlatformIDLTE applies the LTE predicate on the "platform_id" field.
func PlatformIDLTE(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldLTE(FieldPlatformID, v))
}

// PlatformIDContains applies the Contains predicate on the "platform_id" field.
func PlatformIDContains(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldContains(FieldPlatformID, v))
}

// PlatformIDHasPrefix applies the HasPrefix predicate on the "platform_id" field.
func PlatformIDHasPrefix(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldHasPrefix(FieldPlatformID, v))
}

// PlatformIDHasSuffix applies the HasSuffix predicate on the "platform_id" field.
func PlatformIDHasSuffix(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldHasSuffix(FieldPlatformID, v))
}

// PlatformIDEqualFold applies the EqualFold predicate on the "platform_id" field.
func PlatformIDEqualFold(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldEqualFold(FieldPlatformID, v))
}

// PlatformIDContainsFold applies the ContainsFold predicate on the "platform_id" field.
func PlatformIDContainsFold(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldContainsFold(FieldPlatformID, v))
}

// CharacterIDEQ applies the EQ predicate on the "character_id" field.
func CharacterIDEQ(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldEQ(FieldCharacterID, v))
}

// CharacterIDNEQ applies the NEQ predicate on the "character_id" field.
func CharacterIDNEQ(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldNEQ(FieldCharacterID, v))
}

// CharacterIDIn applies the In predicate on the "character_id" field.
func CharacterIDIn(vs ...string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldIn(FieldCharacterID, vs...))
}

// CharacterIDNotIn applies the NotIn predicate on the "character_id" field.
func CharacterIDNotIn(vs ...string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldNotIn(FieldCharacterID, vs...))
}

// CharacterIDGT applies the GT predicate on the "character_id" field.
func CharacterIDGT(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldGT(FieldCharacterID, v))
}

// CharacterIDGTE applies the GTE predicate on the "character_id" field.
func CharacterIDGTE(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldGTE(FieldCharacterID, v))
}

// CharacterIDLT applies the LT predicate on the "character_id" field.
func CharacterIDLT(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldLT(FieldCharacterID, v))
}

// CharacterIDLTE applies the LTE predicate on the "character_id" field.
func CharacterIDLTE(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldLTE(FieldCharacterID, v))
}

// CharacterIDContains applies the Contains predicate on the "character_id" field.
func CharacterIDContains(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldContains(FieldCharacterID, v))
}

// CharacterIDHasPrefix applies the HasPrefix predicate on the "character_id" field.
func CharacterIDHasPrefix(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldHasPrefix(FieldCharacterID, v))
}

// CharacterIDHasSuffix applies the HasSuffix predicate on the "character_id" field.
func CharacterIDHasSuffix(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldHasSuffix(FieldCharacterID, v))
}

// CharacterIDEqualFold applies the EqualFold predicate on the "character_id" field.
func CharacterIDEqualFold(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldEqualFold(FieldCharacterID, v))
}

// CharacterIDContainsFold applies the ContainsFold predicate on the "character_id" field.
func CharacterIDContainsFold(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldContainsFold(FieldCharacterID, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldContainsFold(FieldTitle, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldContainsFold(FieldName, v))
}

// CreatorIDEQ applies the EQ predicate on the "creator_id" field.
func CreatorIDEQ(v resource.CID) predicate.RecordEntity {
	vc := string(v)
	return predicate.RecordEntity(sql.FieldEQ(FieldCreatorID, vc))
}

// CreatorIDNEQ applies the NEQ predicate on the "creator_id" field.
func CreatorIDNEQ(v resource.CID) predicate.RecordEntity {
	vc := string(v)
	return predicate.RecordEntity(sql.FieldNEQ(FieldCreatorID, vc))
}

// CreatorIDIn applies the In predicate on the "creator_id" field.
func CreatorIDIn(vs ...resource.CID) predicate.RecordEntity {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.RecordEntity(sql.FieldIn(FieldCreatorID, v...))
}

// CreatorIDNotIn applies the NotIn predicate on the "creator_id" field.
func CreatorIDNotIn(vs ...resource.CID) predicate.RecordEntity {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.RecordEntity(sql.FieldNotIn(FieldCreatorID, v...))
}

// CreatorIDGT applies the GT predicate on the "creator_id" field.
func CreatorIDGT(v resource.CID) predicate.RecordEntity {
	vc := string(v)
	return predicate.RecordEntity(sql.FieldGT(FieldCreatorID, vc))
}

// CreatorIDGTE applies the GTE predicate on the "creator_id" field.
func CreatorIDGTE(v resource.CID) predicate.RecordEntity {
	vc := string(v)
	return predicate.RecordEntity(sql.FieldGTE(FieldCreatorID, vc))
}

// CreatorIDLT applies the LT predicate on the "creator_id" field.
func CreatorIDLT(v resource.CID) predicate.RecordEntity {
	vc := string(v)
	return predicate.RecordEntity(sql.FieldLT(FieldCreatorID, vc))
}

// CreatorIDLTE applies the LTE predicate on the "creator_id" field.
func CreatorIDLTE(v resource.CID) predicate.RecordEntity {
	vc := string(v)
	return predicate.RecordEntity(sql.FieldLTE(FieldCreatorID, vc))
}

// CreatorIDContains applies the Contains predicate on the "creator_id" field.
func CreatorIDContains(v resource.CID) predicate.RecordEntity {
	vc := string(v)
	return predicate.RecordEntity(sql.FieldContains(FieldCreatorID, vc))
}

// CreatorIDHasPrefix applies the HasPrefix predicate on the "creator_id" field.
func CreatorIDHasPrefix(v resource.CID) predicate.RecordEntity {
	vc := string(v)
	return predicate.RecordEntity(sql.FieldHasPrefix(FieldCreatorID, vc))
}

// CreatorIDHasSuffix applies the HasSuffix predicate on the "creator_id" field.
func CreatorIDHasSuffix(v resource.CID) predicate.RecordEntity {
	vc := string(v)
	return predicate.RecordEntity(sql.FieldHasSuffix(FieldCreatorID, vc))
}

// CreatorIDEqualFold applies the EqualFold predicate on the "creator_id" field.
func CreatorIDEqualFold(v resource.CID) predicate.RecordEntity {
	vc := string(v)
	return predicate.RecordEntity(sql.FieldEqualFold(FieldCreatorID, vc))
}

// CreatorIDContainsFold applies the ContainsFold predicate on the "creator_id" field.
func CreatorIDContainsFold(v resource.CID) predicate.RecordEntity {
	vc := string(v)
	return predicate.RecordEntity(sql.FieldContainsFold(FieldCreatorID, vc))
}

// TaglineEQ applies the EQ predicate on the "tagline" field.
func TaglineEQ(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldEQ(FieldTagline, v))
}

// TaglineNEQ applies the NEQ predicate on the "tagline" field.
func TaglineNEQ(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldNEQ(FieldTagline, v))
}

// TaglineIn applies the In predicate on the "tagline" field.
func TaglineIn(vs ...string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldIn(FieldTagline, vs...))
}

// TaglineNotIn applies the NotIn predicate on the "tagline" field.
func TaglineNotIn(vs ...string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldNotIn(FieldTagline, vs...))
}

// TaglineGT applies the GT predicate on the "tagline" field.
func TaglineGT(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldGT(FieldTagline, v))
}

// TaglineGTE applies the GTE predicate on the "tagline" field.
func TaglineGTE(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldGTE(FieldTagline, v))
}

// TaglineLT applies the LT predicate on the "tagline" field.
func TaglineLT(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldLT(FieldTagline, v))
}

// TaglineLTE applies the LTE predicate on the "tagline" field.
func TaglineLTE(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldLTE(FieldTagline, v))
}

// TaglineContains applies the Contains predicate on the "tagline" field.
func TaglineContains(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldContains(FieldTagline, v))
}

// TaglineHasPrefix applies the HasPrefix predicate on the "tagline" field.
func TaglineHasPrefix(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldHasPrefix(FieldTagline, v))
}

// TaglineHasSuffix applies the HasSuffix predicate on the "tagline" field.
func TaglineHasSuffix(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldHasSuffix(FieldTagline, v))
}

// TaglineEqualFold applies the EqualFold predicate on the "tagline" field.
func TaglineEqualFold(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldEqualFold(FieldTagline, v))
}

// TaglineContainsFold applies the ContainsFold predicate on the "tagline" field.
func TaglineContainsFold(v string) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldContainsFold(FieldTagline, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldEQ(FieldCreateTime, vc))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldNEQ(FieldCreateTime, vc))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...timestamp.Nano) predicate.RecordEntity {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.RecordEntity(sql.FieldIn(FieldCreateTime, v...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...timestamp.Nano) predicate.RecordEntity {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.RecordEntity(sql.FieldNotIn(FieldCreateTime, v...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldGT(FieldCreateTime, vc))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldGTE(FieldCreateTime, vc))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldLT(FieldCreateTime, vc))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldLTE(FieldCreateTime, vc))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldEQ(FieldUpdateTime, vc))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldNEQ(FieldUpdateTime, vc))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...timestamp.Nano) predicate.RecordEntity {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.RecordEntity(sql.FieldIn(FieldUpdateTime, v...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...timestamp.Nano) predicate.RecordEntity {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.RecordEntity(sql.FieldNotIn(FieldUpdateTime, v...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldGT(FieldUpdateTime, vc))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldGTE(FieldUpdateTime, vc))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldLT(FieldUpdateTime, vc))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldLTE(FieldUpdateTime, vc))
}

// IsForkEQ applies the EQ predicate on the "is_fork" field.
func IsForkEQ(v bool) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldEQ(FieldIsFork, v))
}

// IsForkNEQ applies the NEQ predicate on the "is_fork" field.
func IsForkNEQ(v bool) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldNEQ(FieldIsFork, v))
}

// BookUpdateTimeEQ applies the EQ predicate on the "book_update_time" field.
func BookUpdateTimeEQ(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldEQ(FieldBookUpdateTime, vc))
}

// BookUpdateTimeNEQ applies the NEQ predicate on the "book_update_time" field.
func BookUpdateTimeNEQ(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldNEQ(FieldBookUpdateTime, vc))
}

// BookUpdateTimeIn applies the In predicate on the "book_update_time" field.
func BookUpdateTimeIn(vs ...timestamp.Nano) predicate.RecordEntity {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.RecordEntity(sql.FieldIn(FieldBookUpdateTime, v...))
}

// BookUpdateTimeNotIn applies the NotIn predicate on the "book_update_time" field.
func BookUpdateTimeNotIn(vs ...timestamp.Nano) predicate.RecordEntity {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.RecordEntity(sql.FieldNotIn(FieldBookUpdateTime, v...))
}

// BookUpdateTimeGT applies the GT predicate on the "book_update_time" field.
func BookUpdateTimeGT(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldGT(FieldBookUpdateTime, vc))
}

// BookUpdateTimeGTE applies the GTE predicate on the "book_update_time" field.
func BookUpdateTimeGTE(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldGTE(FieldBookUpdateTime, vc))
}

// BookUpdateTimeLT applies the LT predicate on the "book_update_time" field.
func BookUpdateTimeLT(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldLT(FieldBookUpdateTime, vc))
}

// BookUpdateTimeLTE applies the LTE predicate on the "book_update_time" field.
func BookUpdateTimeLTE(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldLTE(FieldBookUpdateTime, vc))
}

// GreetingsCountEQ applies the EQ predicate on the "greetings_count" field.
func GreetingsCountEQ(v int) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldEQ(FieldGreetingsCount, v))
}

// GreetingsCountNEQ applies the NEQ predicate on the "greetings_count" field.
func GreetingsCountNEQ(v int) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldNEQ(FieldGreetingsCount, v))
}

// GreetingsCountIn applies the In predicate on the "greetings_count" field.
func GreetingsCountIn(vs ...int) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldIn(FieldGreetingsCount, vs...))
}

// GreetingsCountNotIn applies the NotIn predicate on the "greetings_count" field.
func GreetingsCountNotIn(vs ...int) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldNotIn(FieldGreetingsCount, vs...))
}

// GreetingsCountGT applies the GT predicate on the "greetings_count" field.
func GreetingsCountGT(v int) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldGT(FieldGreetingsCount, v))
}

// GreetingsCountGTE applies the GTE predicate on the "greetings_count" field.
func GreetingsCountGTE(v int) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldGTE(FieldGreetingsCount, v))
}

// GreetingsCountLT applies the LT predicate on the "greetings_count" field.
func GreetingsCountLT(v int) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldLT(FieldGreetingsCount, v))
}

// GreetingsCountLTE applies the LTE predicate on the "greetings_count" field.
func GreetingsCountLTE(v int) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldLTE(FieldGreetingsCount, v))
}

// SyncStatusEQ applies the EQ predicate on the "sync_status" field.
func SyncStatusEQ(v resource.SyncStatus) predicate.RecordEntity {
	vc := v
	return predicate.RecordEntity(sql.FieldEQ(FieldSyncStatus, vc))
}

// SyncStatusNEQ applies the NEQ predicate on the "sync_status" field.
func SyncStatusNEQ(v resource.SyncStatus) predicate.RecordEntity {
	vc := v
	return predicate.RecordEntity(sql.FieldNEQ(FieldSyncStatus, vc))
}

// SyncStatusIn applies the In predicate on the "sync_status" field.
func SyncStatusIn(vs ...resource.SyncStatus) predicate.RecordEntity {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RecordEntity(sql.FieldIn(FieldSyncStatus, v...))
}

// SyncStatusNotIn applies the NotIn predicate on the "sync_status" field.
func SyncStatusNotIn(vs ...resource.SyncStatus) predicate.RecordEntity {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RecordEntity(sql.FieldNotIn(FieldSyncStatus, v...))
}

// SyncTimeEQ applies the EQ predicate on the "sync_time" field.
func SyncTimeEQ(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldEQ(FieldSyncTime, vc))
}

// SyncTimeNEQ applies the NEQ predicate on the "sync_time" field.
func SyncTimeNEQ(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldNEQ(FieldSyncTime, vc))
}

// SyncTimeIn applies the In predicate on the "sync_time" field.
func SyncTimeIn(vs ...timestamp.Nano) predicate.RecordEntity {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.RecordEntity(sql.FieldIn(FieldSyncTime, v...))
}

// SyncTimeNotIn applies the NotIn predicate on the "sync_time" field.
func SyncTimeNotIn(vs ...timestamp.Nano) predicate.RecordEntity {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.RecordEntity(sql.FieldNotIn(FieldSyncTime, v...))
}

// SyncTimeGT applies the GT predicate on the "sync_time" field.
func SyncTimeGT(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldGT(FieldSyncTime, vc))
}

// SyncTimeGTE applies the GTE predicate on the "sync_time" field.
func SyncTimeGTE(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldGTE(FieldSyncTime, vc))
}

// SyncTimeLT applies the LT predicate on the "sync_time" field.
func SyncTimeLT(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldLT(FieldSyncTime, vc))
}

// SyncTimeLTE applies the LTE predicate on the "sync_time" field.
func SyncTimeLTE(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldLTE(FieldSyncTime, vc))
}

// ExportedVersionEQ applies the EQ predicate on the "exported_version" field.
func ExportedVersionEQ(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldEQ(FieldExportedVersion, vc))
}

// ExportedVersionNEQ applies the NEQ predicate on the "exported_version" field.
func ExportedVersionNEQ(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldNEQ(FieldExportedVersion, vc))
}

// ExportedVersionIn applies the In predicate on the "exported_version" field.
func ExportedVersionIn(vs ...timestamp.Nano) predicate.RecordEntity {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.RecordEntity(sql.FieldIn(FieldExportedVersion, v...))
}

// ExportedVersionNotIn applies the NotIn predicate on the "exported_version" field.
func ExportedVersionNotIn(vs ...timestamp.Nano) predicate.RecordEntity {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.RecordEntity(sql.FieldNotIn(FieldExportedVersion, v...))
}

// ExportedVersionGT applies the GT predicate on the "exported_version" field.
func ExportedVersionGT(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldGT(FieldExportedVersion, vc))
}

// ExportedVersionGTE applies the GTE predicate on the "exported_version" field.
func ExportedVersionGTE(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldGTE(FieldExportedVersion, vc))
}

// ExportedVersionLT applies the LT predicate on the "exported_version" field.
func ExportedVersionLT(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldLT(FieldExportedVersion, vc))
}

// ExportedVersionLTE applies the LTE predicate on the "exported_version" field.
func ExportedVersionLTE(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldLTE(FieldExportedVersion, vc))
}

// ExportTimeEQ applies the EQ predicate on the "export_time" field.
func ExportTimeEQ(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldEQ(FieldExportTime, vc))
}

// ExportTimeNEQ applies the NEQ predicate on the "export_time" field.
func ExportTimeNEQ(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldNEQ(FieldExportTime, vc))
}

// ExportTimeIn applies the In predicate on the "export_time" field.
func ExportTimeIn(vs ...timestamp.Nano) predicate.RecordEntity {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.RecordEntity(sql.FieldIn(FieldExportTime, v...))
}

// ExportTimeNotIn applies the NotIn predicate on the "export_time" field.
func ExportTimeNotIn(vs ...timestamp.Nano) predicate.RecordEntity {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.RecordEntity(sql.FieldNotIn(FieldExportTime, v...))
}

// ExportTimeGT applies the GT predicate on the "export_time" field.
func ExportTimeGT(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldGT(FieldExportTime, vc))
}

// ExportTimeGTE applies the GTE predicate on the "export_time" field.
func ExportTimeGTE(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldGTE(FieldExportTime, vc))
}

// ExportTimeLT applies the LT predicate on the "export_time" field.
func ExportTimeLT(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldLT(FieldExportTime, vc))
}

// ExportTimeLTE applies the LTE predicate on the "export_time" field.
func ExportTimeLTE(v timestamp.Nano) predicate.RecordEntity {
	vc := int64(v)
	return predicate.RecordEntity(sql.FieldLTE(FieldExportTime, vc))
}

// FavoriteEQ applies the EQ predicate on the "favorite" field.
func FavoriteEQ(v bool) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldEQ(FieldFavorite, v))
}

// FavoriteNEQ applies the NEQ predicate on the "favorite" field.
func FavoriteNEQ(v bool) predicate.RecordEntity {
	return predicate.RecordEntity(sql.FieldNEQ(FieldFavorite, v))
}

// HasTags applies the HasEdge predicate on the "tags" edge.
func HasTags() predicate.RecordEntity {
	return predicate.RecordEntity(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, TagsTable, TagsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTagsWith applies the HasEdge predicate on the "tags" edge with a given conditions (other predicates).
func HasTagsWith(preds ...predicate.TagEntity) predicate.RecordEntity {
	return predicate.RecordEntity(func(s *sql.Selector) {
		step := newTagsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCreator applies the HasEdge predicate on the "creator" edge.
func HasCreator() predicate.RecordEntity {
	return predicate.RecordEntity(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, CreatorTable, CreatorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCreatorWith applies the HasEdge predicate on the "creator" edge with a given conditions (other predicates).
func HasCreatorWith(preds ...predicate.CreatorEntity) predicate.RecordEntity {
	return predicate.RecordEntity(func(s *sql.Selector) {
		step := newCreatorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RecordEntity) predicate.RecordEntity {
	return predicate.RecordEntity(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RecordEntity) predicate.RecordEntity {
	return predicate.RecordEntity(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RecordEntity) predicate.RecordEntity {
	return predicate.RecordEntity(sql.NotPredicates(p))
}
