package operation

import (
	"context"
	"fmt"
	"sync"
	"testing"
	"time"

	"github.com/r3dpixel/card-client/services/operation"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const testVault = "vault"

func newTestRegistry() (*Registry, *int) {
	callCount := 0
	mockGenerator := func() operation.ID {
		callCount++
		return operation.ID(fmt.Sprintf("test-id-%d", callCount))
	}
	return NewRegistry(mockGenerator), &callCount
}

func TestDefaultIdGenerator(t *testing.T) {
	generator := DefaultIdGenerator()
	require.NotNil(t, generator)

	id1 := generator()
	id2 := generator()

	assert.NotEmpty(t, id1)
	assert.NotEmpty(t, id2)
	assert.NotEqual(t, id1, id2, "Default ID generator should produce unique IDs")
}

func TestNewRegistry(t *testing.T) {
	reg, _ := newTestRegistry()
	require.NotNil(t, reg, "NewRegistry should not return nil")
	assert.NotNil(t, reg.operations, "Operations map should be initialized")
	assert.Equal(t, 0, reg.ActiveOperations(), "A new registry should have no active operations")
	assert.False(t, reg.HasChanges(), "A new registry should not be dirty")
}

func TestRegistry_RegistrationLifecycle(t *testing.T) {
	testCases := []struct {
		name         string
		registerFunc func(*Registry) operation.Handle[any]
		action       operation.Action
	}{
		{"RegisterImport", func(r *Registry) operation.Handle[any] {
			h := r.RegisterImport(testVault)
			return operation.NewHandle[any](h.ID(), h.Context(), h.TimeStarted(), nil, nil)
		}, operation.Import},
		{"RegisterUpdate", func(r *Registry) operation.Handle[any] {
			h := r.RegisterUpdate(testVault)
			return operation.NewHandle[any](h.ID(), h.Context(), h.TimeStarted(), nil, nil)
		}, operation.Update},
		{"RegisterExport", func(r *Registry) operation.Handle[any] {
			h := r.RegisterExport(testVault)
			return operation.NewHandle[any](h.ID(), h.Context(), h.TimeStarted(), nil, nil)
		}, operation.Export},
		{"RegisterDelete", func(r *Registry) operation.Handle[any] {
			h := r.RegisterDelete(testVault)
			return operation.NewHandle[any](h.ID(), h.Context(), h.TimeStarted(), nil, nil)
		}, operation.Delete},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			reg, idCounter := newTestRegistry()
			assert.False(t, reg.HasChanges(), "Registry should not be dirty initially")

			handle := tc.registerFunc(reg)
			id := handle.ID()

			assert.True(t, reg.HasChanges(), "Registry should be dirty after registration")
			assert.Equal(t, operation.ID("test-id-1"), id, "ID should be generated by the mock generator")
			assert.Equal(t, 1, *idCounter, "ID generator should have been called once")
			assert.Equal(t, 1, reg.ActiveOperations(), "Active operations count should be 1 after registration")
			assert.NotZero(t, handle.TimeStarted(), "Handle should have a non-zero start time")

			reg.mapMutex.RLock()
			entry, ok := reg.operations.Get(id)
			reg.mapMutex.RUnlock()

			require.True(t, ok, "Operation should exist in the internal map")
			assert.Equal(t, tc.action, entry.details.Action, "Operation should have the correct action type")
			assert.Equal(t, operation.Ongoing, entry.details.Status, "New operation should have 'Ongoing' status")
			assert.NotZero(t, entry.details.TimeStarted, "TimeStarted should be set on registration")
			assert.False(t, entry.details.Disposable, "New operation should not be disposable")
			require.NotNil(t, entry.cancel, "A cancel function should be associated with the entry")
		})
	}
}
func TestRegistry_EndOperations(t *testing.T) {
	t.Run("Complete_Success", func(t *testing.T) {
		reg, _ := newTestRegistry()
		handle := reg.RegisterImport(testVault)
		reg.ListReports() // Clear dirty flag from registration
		assert.False(t, reg.HasChanges(), "Flag should be clean after ListReports")

		err := reg.Complete(handle.ID())
		require.NoError(t, err)

		assert.True(t, reg.HasChanges(), "Registry should be dirty after completing an operation")
		assert.Equal(t, 0, reg.ActiveOperations(), "Active operations should be 0 after completion")

		entry, _ := reg.operations.Get(handle.ID())
		entry.mu.Lock()
		defer entry.mu.Unlock()
		assert.Equal(t, operation.Completed, entry.details.Status, "Status should be 'Completed'")
	})

	t.Run("Cancel_Success", func(t *testing.T) {
		reg, _ := newTestRegistry()
		handle := reg.RegisterImport(testVault)
		reg.ListReports() // Clear dirty flag from registration
		assert.False(t, reg.HasChanges(), "Flag should be clean after ListReports")

		err := reg.Cancel(handle.ID())
		require.NoError(t, err)

		assert.True(t, reg.HasChanges(), "Registry should be dirty after cancelling an operation")
		assert.Equal(t, 0, reg.ActiveOperations(), "Active operations should be 0 after cancellation")

		entry, _ := reg.operations.Get(handle.ID())
		entry.mu.Lock()
		defer entry.mu.Unlock()
		assert.Equal(t, operation.Cancelled, entry.details.Status, "Status should be 'Cancelled'")

		select {
		case <-handle.Context().Done():
			assert.ErrorIs(t, handle.Context().Err(), context.Canceled, "Context error should be 'context.Canceled'")
		case <-time.After(100 * time.Millisecond):
			t.Fatal("Context should have been cancelled")
		}
	})

	t.Run("Error_On_NonExistent", func(t *testing.T) {
		reg, _ := newTestRegistry()
		err := reg.Complete("non-existent-id")
		assert.ErrorContains(t, err, `Operation "non-existent-id" not found`)
		assert.False(t, reg.HasChanges(), "Flag should not be set on error")

		err = reg.Cancel("non-existent-id")
		assert.ErrorContains(t, err, `Operation "non-existent-id" not found`)
		assert.False(t, reg.HasChanges(), "Flag should not be set on error")
	})

	t.Run("Error_On_AlreadyTerminated", func(t *testing.T) {
		reg, _ := newTestRegistry()
		handle := reg.RegisterImport(testVault)
		id := handle.ID()

		err := reg.Complete(id)
		require.NoError(t, err, "First completion should succeed")
		reg.ListReports() // Clear dirty flag
		assert.False(t, reg.HasChanges(), "Flag should be clean after ListReports")

		err = reg.Complete(id)
		assert.ErrorContains(t, err, "has already been terminated: COMPLETED")
		assert.False(t, reg.HasChanges(), "Flag should not be set on error")

		err = reg.Cancel(id)
		assert.ErrorContains(t, err, "has already been terminated: COMPLETED")
		assert.False(t, reg.HasChanges(), "Flag should not be set on error")
	})
}

func TestRegistry_Delete(t *testing.T) {
	t.Run("Delete_Success", func(t *testing.T) {
		reg, _ := newTestRegistry()
		handle := reg.RegisterImport(testVault)
		reg.ListReports() // Clear dirty flag from registration
		assert.False(t, reg.HasChanges(), "Flag should be clean after ListReports")

		// Ensure it exists before deletion
		reg.mapMutex.RLock()
		_, exists := reg.operations.Get(handle.ID())
		reg.mapMutex.RUnlock()
		require.True(t, exists, "Operation should exist before deletion")

		err := reg.Delete(handle.ID())
		require.NoError(t, err, "Deletion should not return an error for an existing operation")
		assert.False(t, reg.HasChanges(), "Registry should NOT be dirty after deleting an operation")

		// Ensure it's gone
		reg.mapMutex.RLock()
		_, exists = reg.operations.Get(handle.ID())
		reg.mapMutex.RUnlock()
		assert.False(t, exists, "Operation should not exist after deletion")
	})

	t.Run("Delete_NonExistent", func(t *testing.T) {
		reg, _ := newTestRegistry()
		err := reg.Delete("non-existent-id")
		assert.ErrorContains(t, err, `Operation "non-existent-id" not found`)
		assert.False(t, reg.HasChanges(), "Flag should not be set on error")
	})
}

func TestRegistry_ListReports(t *testing.T) {
	reg, _ := newTestRegistry()

	hImport := reg.RegisterImport(testVault)
	hUpdate := reg.RegisterUpdate(testVault)
	hExport := reg.RegisterExport(testVault)
	hDelete := reg.RegisterDelete(testVault)

	err := hUpdate.Mutate(func(report *operation.UpdateReport) {
		report.Total = 200
		report.Progress = 150
		report.NoSuccesses = 120
		report.NoFailures = 5
		report.NoUnchanges = 25
	})
	require.NoError(t, err)

	_ = reg.Complete(hUpdate.ID())
	_ = reg.Cancel(hDelete.ID())

	assert.True(t, reg.HasChanges(), "Registry should be dirty before listing reports")

	reports := reg.ListReports()
	require.Len(t, reports, 4, "Should get reports for all 4 registered operations")

	assert.False(t, reg.HasChanges(), "Registry should NOT be dirty immediately after listing reports")

	reportMap := make(map[operation.ID]operation.UnifiedReport)
	for _, r := range reports {
		reportMap[r.Details.ID] = r
	}

	impReport, ok := reportMap[hImport.ID()]
	require.True(t, ok, "Import report should be found")
	assert.Equal(t, operation.Import, impReport.Details.Action)
	assert.Equal(t, operation.Ongoing, impReport.Details.Status)
	assert.Zero(t, impReport.Details.TimeEnded)
	assert.Equal(t, impReport.Details.VaultName, testVault)
	assert.False(t, impReport.Details.Disposable, "Ongoing report should not be disposable")
	assert.NotZero(t, impReport.Details.TimeStarted, "TimeStarted should be populated")
	assert.NotNil(t, impReport.Import, "UnifiedReport.Import should not be nil")
	assert.Nil(t, impReport.Update, "UnifiedReport.Update should be nil for an import op")
	assert.Nil(t, impReport.Export, "UnifiedReport.Export should be nil for an import op")
	assert.Nil(t, impReport.Delete, "UnifiedReport.Delete should be nil for an import op")

	updReport, ok := reportMap[hUpdate.ID()]
	require.True(t, ok, "Update report should be found")
	assert.Equal(t, operation.Update, updReport.Details.Action)
	assert.Equal(t, operation.Completed, updReport.Details.Status)
	assert.NotZero(t, updReport.Details.TimeEnded)
	assert.Equal(t, updReport.Details.VaultName, testVault)
	assert.True(t, updReport.Details.Disposable, "Completed report should be marked as disposable")
	require.NotNil(t, updReport.Update, "UnifiedReport.Update should not be nil")
	assert.Nil(t, updReport.Import, "UnifiedReport.Import should be nil for an update op")

	assert.Equal(t, 200, updReport.Update.Total)
	assert.Equal(t, 150, updReport.Update.Progress)
	assert.Equal(t, 120, updReport.Update.NoSuccesses)
	assert.Equal(t, 5, updReport.Update.NoFailures)
	assert.Equal(t, 25, updReport.Update.NoUnchanges)

	expReport, ok := reportMap[hExport.ID()]
	require.True(t, ok, "Export report should be found")
	assert.Equal(t, operation.Export, expReport.Details.Action)
	assert.Equal(t, operation.Ongoing, expReport.Details.Status)
	assert.Zero(t, impReport.Details.TimeEnded)
	assert.Equal(t, expReport.Details.VaultName, testVault)
	assert.False(t, expReport.Details.Disposable, "Ongoing report should not be disposable")
	assert.NotNil(t, expReport.Export, "UnifiedReport.Export should not be nil")
	assert.Nil(t, expReport.Update, "UnifiedReport.Update should be nil for an export op")

	delReport, ok := reportMap[hDelete.ID()]
	require.True(t, ok, "Delete report should be found")
	assert.Equal(t, operation.Delete, delReport.Details.Action)
	assert.Equal(t, operation.Cancelled, delReport.Details.Status)
	assert.NotZero(t, delReport.Details.TimeEnded)
	assert.Equal(t, delReport.Details.VaultName, testVault)
	assert.True(t, delReport.Details.Disposable, "Cancelled report should be marked as disposable")
	assert.NotNil(t, delReport.Delete, "UnifiedReport.Delete should not be nil")
	assert.Nil(t, delReport.Import, "UnifiedReport.Import should be nil for a delete op")
}

func TestRegistry_DisposableCleanup(t *testing.T) {
	reg, _ := newTestRegistry()

	hOngoing := reg.RegisterExport(testVault)
	hCompleted := reg.RegisterImport(testVault)
	hCancelled := reg.RegisterUpdate(testVault)

	err := reg.Complete(hCompleted.ID())
	require.NoError(t, err)
	err = reg.Cancel(hCancelled.ID())
	require.NoError(t, err)

	t.Log("First call to ListReports: expecting to see all 3 operations, with 2 marked as disposable.")
	reports1 := reg.ListReports()
	require.Len(t, reports1, 3, "Should show all 3 operations on the first list")
	assert.Equal(t, 3, reg.operations.Len(), "Internal map should still contain 3 operations")

	entryCompleted, _ := reg.operations.Get(hCompleted.ID())
	assert.True(t, entryCompleted.details.Disposable, "Completed op should be marked disposable internally")
	entryCancelled, _ := reg.operations.Get(hCancelled.ID())
	assert.True(t, entryCancelled.details.Disposable, "Cancelled op should be marked disposable internally")
	entryOngoing, _ := reg.operations.Get(hOngoing.ID())
	assert.False(t, entryOngoing.details.Disposable, "Ongoing op should not be marked disposable")

	t.Log("Second call to ListReports: expecting to see only the ongoing operation.")
	reports2 := reg.ListReports()
	require.Len(t, reports2, 1, "Should only show the ongoing operation on the second list")
	assert.Equal(t, 1, reg.operations.Len(), "Internal map should now only contain 1 operation")
	assert.Equal(t, hOngoing.ID(), reports2[0].Details.ID, "The remaining report should be the ongoing one")

	t.Log("Third call to ListReports: expecting no change.")
	reports3 := reg.ListReports()
	require.Len(t, reports3, 1, "Should still show the ongoing operation on the third list")
	assert.Equal(t, 1, reg.operations.Len(), "Internal map should still contain 1 operation")
}

func TestOperationHandle(t *testing.T) {
	t.Run("Apply_Success", func(t *testing.T) {
		reg, _ := newTestRegistry()
		handle := reg.RegisterImport(testVault)
		assert.NotZero(t, handle.TimeStarted(), "Handle should have a start time")
		reg.ListReports() // Clear dirty flag from registration
		assert.False(t, reg.HasChanges(), "Flag should be clean after ListReports")

		err := handle.Mutate(func(report *operation.ImportReport) {
			report.Progress = 99
		})
		require.NoError(t, err)

		assert.True(t, reg.HasChanges(), "Registry should be dirty after a mutation")

		entry, _ := reg.operations.Get(handle.ID())
		report, ok := entry.report.(*operation.ImportReport)
		require.True(t, ok, "Report should be of the correct type")
		assert.Equal(t, 99, report.Progress)
	})

	t.Run("Apply_ErrorOnDeletedOperation", func(t *testing.T) {
		reg, _ := newTestRegistry()
		handle := reg.RegisterImport(testVault)

		err := reg.Delete(handle.ID())
		require.NoError(t, err)
		reg.ListReports()
		assert.False(t, reg.HasChanges(), "Flag should be clean after ListReports")

		err = handle.Mutate(func(report *operation.ImportReport) {
			report.Progress = 99
		})
		assert.Error(t, err, "Apply should fail for a deleted operation")
		assert.False(t, reg.HasChanges(), "Flag should not be set on error")
	})

	t.Run("Complete_ViaHandle", func(t *testing.T) {
		reg, _ := newTestRegistry()
		handle := reg.RegisterImport(testVault)
		reg.ListReports()
		assert.False(t, reg.HasChanges(), "Flag should be clean after ListReports")

		err := handle.Complete()
		require.NoError(t, err)

		assert.True(t, reg.HasChanges(), "Registry should be dirty after completing via handle")
		assert.Equal(t, 0, reg.ActiveOperations())
		entry, _ := reg.operations.Get(handle.ID())
		assert.Equal(t, operation.Completed, entry.details.Status)
	})
}

func TestRegistry_Concurrency(t *testing.T) {
	reg := NewRegistry(DefaultIdGenerator())
	var wg sync.WaitGroup
	numGoroutines := 100

	wg.Add(numGoroutines)
	for i := 0; i < numGoroutines; i++ {
		go func(i int) {
			defer wg.Done()

			var handle operation.Handle[*operation.ImportReport]
			handle = reg.RegisterImport(testVault)

			for j := 0; j < 10; j++ {
				_ = handle.Mutate(func(r *operation.ImportReport) {
					r.Progress++
				})
			}

			if i%2 == 0 {
				_ = handle.Complete()
			} else {
				_ = reg.Cancel(handle.ID())
			}
		}(i)
	}

	var readerWg sync.WaitGroup
	readerWg.Add(1)
	stopReading := make(chan struct{})
	go func() {
		defer readerWg.Done()
		for {
			select {
			case <-stopReading:
				return
			default:
				_ = reg.ListReports()
				_ = reg.ActiveOperations()
				time.Sleep(1 * time.Millisecond)
			}
		}
	}()

	wg.Wait()
	close(stopReading)
	readerWg.Wait()

	assert.Equal(t, 0, reg.ActiveOperations(), "All operations should be terminated")

	_ = reg.ListReports()
	finalReports := reg.ListReports()
	assert.Empty(t, finalReports, "Registry should be empty after all operations are completed and listed twice")
	assert.True(t, reg.operations.Len() == 0, "Internal map should be empty after cleanup")
}
