// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/r3dpixel/card-client/internal/ent/card"
	"github.com/r3dpixel/card-client/internal/ent/predicate"
	"github.com/r3dpixel/card-client/internal/ent/tag"
	"github.com/r3dpixel/card-client/services/scheme"
	"github.com/r3dpixel/card-fetcher/source"
	"github.com/r3dpixel/toolkit/timestamp"
)

// CardUpdate is the builder for updating Card entities.
type CardUpdate struct {
	config
	hooks     []Hook
	mutation  *CardMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the CardUpdate builder.
func (_u *CardUpdate) Where(ps ...predicate.Card) *CardUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBatchOrder sets the "batch_order" field.
func (_u *CardUpdate) SetBatchOrder(v int) *CardUpdate {
	_u.mutation.ResetBatchOrder()
	_u.mutation.SetBatchOrder(v)
	return _u
}

// SetNillableBatchOrder sets the "batch_order" field if the given value is not nil.
func (_u *CardUpdate) SetNillableBatchOrder(v *int) *CardUpdate {
	if v != nil {
		_u.SetBatchOrder(*v)
	}
	return _u
}

// AddBatchOrder adds value to the "batch_order" field.
func (_u *CardUpdate) AddBatchOrder(v int) *CardUpdate {
	_u.mutation.AddBatchOrder(v)
	return _u
}

// SetSource sets the "source" field.
func (_u *CardUpdate) SetSource(v source.ID) *CardUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *CardUpdate) SetNillableSource(v *source.ID) *CardUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetCardURL sets the "card_url" field.
func (_u *CardUpdate) SetCardURL(v string) *CardUpdate {
	_u.mutation.SetCardURL(v)
	return _u
}

// SetNillableCardURL sets the "card_url" field if the given value is not nil.
func (_u *CardUpdate) SetNillableCardURL(v *string) *CardUpdate {
	if v != nil {
		_u.SetCardURL(*v)
	}
	return _u
}

// SetDirectURL sets the "direct_url" field.
func (_u *CardUpdate) SetDirectURL(v string) *CardUpdate {
	_u.mutation.SetDirectURL(v)
	return _u
}

// SetNillableDirectURL sets the "direct_url" field if the given value is not nil.
func (_u *CardUpdate) SetNillableDirectURL(v *string) *CardUpdate {
	if v != nil {
		_u.SetDirectURL(*v)
	}
	return _u
}

// SetPlatformID sets the "platform_id" field.
func (_u *CardUpdate) SetPlatformID(v string) *CardUpdate {
	_u.mutation.SetPlatformID(v)
	return _u
}

// SetNillablePlatformID sets the "platform_id" field if the given value is not nil.
func (_u *CardUpdate) SetNillablePlatformID(v *string) *CardUpdate {
	if v != nil {
		_u.SetPlatformID(*v)
	}
	return _u
}

// SetCharacterID sets the "character_id" field.
func (_u *CardUpdate) SetCharacterID(v string) *CardUpdate {
	_u.mutation.SetCharacterID(v)
	return _u
}

// SetNillableCharacterID sets the "character_id" field if the given value is not nil.
func (_u *CardUpdate) SetNillableCharacterID(v *string) *CardUpdate {
	if v != nil {
		_u.SetCharacterID(*v)
	}
	return _u
}

// SetCardName sets the "card_name" field.
func (_u *CardUpdate) SetCardName(v string) *CardUpdate {
	_u.mutation.SetCardName(v)
	return _u
}

// SetNillableCardName sets the "card_name" field if the given value is not nil.
func (_u *CardUpdate) SetNillableCardName(v *string) *CardUpdate {
	if v != nil {
		_u.SetCardName(*v)
	}
	return _u
}

// SetCharacterName sets the "character_name" field.
func (_u *CardUpdate) SetCharacterName(v string) *CardUpdate {
	_u.mutation.SetCharacterName(v)
	return _u
}

// SetNillableCharacterName sets the "character_name" field if the given value is not nil.
func (_u *CardUpdate) SetNillableCharacterName(v *string) *CardUpdate {
	if v != nil {
		_u.SetCharacterName(*v)
	}
	return _u
}

// SetCreator sets the "creator" field.
func (_u *CardUpdate) SetCreator(v string) *CardUpdate {
	_u.mutation.SetCreator(v)
	return _u
}

// SetNillableCreator sets the "creator" field if the given value is not nil.
func (_u *CardUpdate) SetNillableCreator(v *string) *CardUpdate {
	if v != nil {
		_u.SetCreator(*v)
	}
	return _u
}

// SetTagline sets the "tagline" field.
func (_u *CardUpdate) SetTagline(v string) *CardUpdate {
	_u.mutation.SetTagline(v)
	return _u
}

// SetNillableTagline sets the "tagline" field if the given value is not nil.
func (_u *CardUpdate) SetNillableTagline(v *string) *CardUpdate {
	if v != nil {
		_u.SetTagline(*v)
	}
	return _u
}

// SetCreateTime sets the "create_time" field.
func (_u *CardUpdate) SetCreateTime(v timestamp.Nano) *CardUpdate {
	_u.mutation.ResetCreateTime()
	_u.mutation.SetCreateTime(v)
	return _u
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_u *CardUpdate) SetNillableCreateTime(v *timestamp.Nano) *CardUpdate {
	if v != nil {
		_u.SetCreateTime(*v)
	}
	return _u
}

// AddCreateTime adds value to the "create_time" field.
func (_u *CardUpdate) AddCreateTime(v timestamp.Nano) *CardUpdate {
	_u.mutation.AddCreateTime(v)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *CardUpdate) SetUpdateTime(v timestamp.Nano) *CardUpdate {
	_u.mutation.ResetUpdateTime()
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *CardUpdate) SetNillableUpdateTime(v *timestamp.Nano) *CardUpdate {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// AddUpdateTime adds value to the "update_time" field.
func (_u *CardUpdate) AddUpdateTime(v timestamp.Nano) *CardUpdate {
	_u.mutation.AddUpdateTime(v)
	return _u
}

// SetBookUpdateTime sets the "book_update_time" field.
func (_u *CardUpdate) SetBookUpdateTime(v timestamp.Nano) *CardUpdate {
	_u.mutation.ResetBookUpdateTime()
	_u.mutation.SetBookUpdateTime(v)
	return _u
}

// SetNillableBookUpdateTime sets the "book_update_time" field if the given value is not nil.
func (_u *CardUpdate) SetNillableBookUpdateTime(v *timestamp.Nano) *CardUpdate {
	if v != nil {
		_u.SetBookUpdateTime(*v)
	}
	return _u
}

// AddBookUpdateTime adds value to the "book_update_time" field.
func (_u *CardUpdate) AddBookUpdateTime(v timestamp.Nano) *CardUpdate {
	_u.mutation.AddBookUpdateTime(v)
	return _u
}

// SetImportTime sets the "import_time" field.
func (_u *CardUpdate) SetImportTime(v timestamp.Nano) *CardUpdate {
	_u.mutation.ResetImportTime()
	_u.mutation.SetImportTime(v)
	return _u
}

// SetNillableImportTime sets the "import_time" field if the given value is not nil.
func (_u *CardUpdate) SetNillableImportTime(v *timestamp.Nano) *CardUpdate {
	if v != nil {
		_u.SetImportTime(*v)
	}
	return _u
}

// AddImportTime adds value to the "import_time" field.
func (_u *CardUpdate) AddImportTime(v timestamp.Nano) *CardUpdate {
	_u.mutation.AddImportTime(v)
	return _u
}

// SetCheckTime sets the "check_time" field.
func (_u *CardUpdate) SetCheckTime(v timestamp.Nano) *CardUpdate {
	_u.mutation.ResetCheckTime()
	_u.mutation.SetCheckTime(v)
	return _u
}

// SetNillableCheckTime sets the "check_time" field if the given value is not nil.
func (_u *CardUpdate) SetNillableCheckTime(v *timestamp.Nano) *CardUpdate {
	if v != nil {
		_u.SetCheckTime(*v)
	}
	return _u
}

// AddCheckTime adds value to the "check_time" field.
func (_u *CardUpdate) AddCheckTime(v timestamp.Nano) *CardUpdate {
	_u.mutation.AddCheckTime(v)
	return _u
}

// SetLastUpdateStatus sets the "last_update_status" field.
func (_u *CardUpdate) SetLastUpdateStatus(v scheme.UpdateStatus) *CardUpdate {
	_u.mutation.SetLastUpdateStatus(v)
	return _u
}

// SetNillableLastUpdateStatus sets the "last_update_status" field if the given value is not nil.
func (_u *CardUpdate) SetNillableLastUpdateStatus(v *scheme.UpdateStatus) *CardUpdate {
	if v != nil {
		_u.SetLastUpdateStatus(*v)
	}
	return _u
}

// SetExportTime sets the "export_time" field.
func (_u *CardUpdate) SetExportTime(v timestamp.Nano) *CardUpdate {
	_u.mutation.ResetExportTime()
	_u.mutation.SetExportTime(v)
	return _u
}

// SetNillableExportTime sets the "export_time" field if the given value is not nil.
func (_u *CardUpdate) SetNillableExportTime(v *timestamp.Nano) *CardUpdate {
	if v != nil {
		_u.SetExportTime(*v)
	}
	return _u
}

// AddExportTime adds value to the "export_time" field.
func (_u *CardUpdate) AddExportTime(v timestamp.Nano) *CardUpdate {
	_u.mutation.AddExportTime(v)
	return _u
}

// SetLastExportedVersion sets the "last_exported_version" field.
func (_u *CardUpdate) SetLastExportedVersion(v timestamp.Nano) *CardUpdate {
	_u.mutation.ResetLastExportedVersion()
	_u.mutation.SetLastExportedVersion(v)
	return _u
}

// SetNillableLastExportedVersion sets the "last_exported_version" field if the given value is not nil.
func (_u *CardUpdate) SetNillableLastExportedVersion(v *timestamp.Nano) *CardUpdate {
	if v != nil {
		_u.SetLastExportedVersion(*v)
	}
	return _u
}

// AddLastExportedVersion adds value to the "last_exported_version" field.
func (_u *CardUpdate) AddLastExportedVersion(v timestamp.Nano) *CardUpdate {
	_u.mutation.AddLastExportedVersion(v)
	return _u
}

// SetFavorite sets the "favorite" field.
func (_u *CardUpdate) SetFavorite(v bool) *CardUpdate {
	_u.mutation.SetFavorite(v)
	return _u
}

// SetNillableFavorite sets the "favorite" field if the given value is not nil.
func (_u *CardUpdate) SetNillableFavorite(v *bool) *CardUpdate {
	if v != nil {
		_u.SetFavorite(*v)
	}
	return _u
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (_u *CardUpdate) AddTagIDs(ids ...scheme.TagID) *CardUpdate {
	_u.mutation.AddTagIDs(ids...)
	return _u
}

// AddTags adds the "tags" edges to the Tag entity.
func (_u *CardUpdate) AddTags(v ...*Tag) *CardUpdate {
	ids := make([]scheme.TagID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTagIDs(ids...)
}

// Mutation returns the CardMutation object of the builder.
func (_u *CardUpdate) Mutation() *CardMutation {
	return _u.mutation
}

// ClearTags clears all "tags" edges to the Tag entity.
func (_u *CardUpdate) ClearTags() *CardUpdate {
	_u.mutation.ClearTags()
	return _u
}

// RemoveTagIDs removes the "tags" edge to Tag entities by IDs.
func (_u *CardUpdate) RemoveTagIDs(ids ...scheme.TagID) *CardUpdate {
	_u.mutation.RemoveTagIDs(ids...)
	return _u
}

// RemoveTags removes "tags" edges to Tag entities.
func (_u *CardUpdate) RemoveTags(v ...*Tag) *CardUpdate {
	ids := make([]scheme.TagID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTagIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CardUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CardUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CardUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CardUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CardUpdate) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := card.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Card.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastUpdateStatus(); ok {
		if err := card.LastUpdateStatusValidator(v); err != nil {
			return &ValidationError{Name: "last_update_status", err: fmt.Errorf(`ent: validator failed for field "Card.last_update_status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CardUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CardUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CardUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(card.Table, card.Columns, sqlgraph.NewFieldSpec(card.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BatchOrder(); ok {
		_spec.SetField(card.FieldBatchOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBatchOrder(); ok {
		_spec.AddField(card.FieldBatchOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(card.FieldSource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CardURL(); ok {
		_spec.SetField(card.FieldCardURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.DirectURL(); ok {
		_spec.SetField(card.FieldDirectURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlatformID(); ok {
		_spec.SetField(card.FieldPlatformID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CharacterID(); ok {
		_spec.SetField(card.FieldCharacterID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CardName(); ok {
		_spec.SetField(card.FieldCardName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CharacterName(); ok {
		_spec.SetField(card.FieldCharacterName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Creator(); ok {
		_spec.SetField(card.FieldCreator, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tagline(); ok {
		_spec.SetField(card.FieldTagline, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreateTime(); ok {
		_spec.SetField(card.FieldCreateTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreateTime(); ok {
		_spec.AddField(card.FieldCreateTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(card.FieldUpdateTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdateTime(); ok {
		_spec.AddField(card.FieldUpdateTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BookUpdateTime(); ok {
		_spec.SetField(card.FieldBookUpdateTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBookUpdateTime(); ok {
		_spec.AddField(card.FieldBookUpdateTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ImportTime(); ok {
		_spec.SetField(card.FieldImportTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedImportTime(); ok {
		_spec.AddField(card.FieldImportTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CheckTime(); ok {
		_spec.SetField(card.FieldCheckTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCheckTime(); ok {
		_spec.AddField(card.FieldCheckTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastUpdateStatus(); ok {
		_spec.SetField(card.FieldLastUpdateStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ExportTime(); ok {
		_spec.SetField(card.FieldExportTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedExportTime(); ok {
		_spec.AddField(card.FieldExportTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastExportedVersion(); ok {
		_spec.SetField(card.FieldLastExportedVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastExportedVersion(); ok {
		_spec.AddField(card.FieldLastExportedVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Favorite(); ok {
		_spec.SetField(card.FieldFavorite, field.TypeBool, value)
	}
	if _u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   card.TagsTable,
			Columns: card.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTagsIDs(); len(nodes) > 0 && !_u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   card.TagsTable,
			Columns: card.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   card.TagsTable,
			Columns: card.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{card.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CardUpdateOne is the builder for updating a single Card entity.
type CardUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *CardMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetBatchOrder sets the "batch_order" field.
func (_u *CardUpdateOne) SetBatchOrder(v int) *CardUpdateOne {
	_u.mutation.ResetBatchOrder()
	_u.mutation.SetBatchOrder(v)
	return _u
}

// SetNillableBatchOrder sets the "batch_order" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableBatchOrder(v *int) *CardUpdateOne {
	if v != nil {
		_u.SetBatchOrder(*v)
	}
	return _u
}

// AddBatchOrder adds value to the "batch_order" field.
func (_u *CardUpdateOne) AddBatchOrder(v int) *CardUpdateOne {
	_u.mutation.AddBatchOrder(v)
	return _u
}

// SetSource sets the "source" field.
func (_u *CardUpdateOne) SetSource(v source.ID) *CardUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableSource(v *source.ID) *CardUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetCardURL sets the "card_url" field.
func (_u *CardUpdateOne) SetCardURL(v string) *CardUpdateOne {
	_u.mutation.SetCardURL(v)
	return _u
}

// SetNillableCardURL sets the "card_url" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableCardURL(v *string) *CardUpdateOne {
	if v != nil {
		_u.SetCardURL(*v)
	}
	return _u
}

// SetDirectURL sets the "direct_url" field.
func (_u *CardUpdateOne) SetDirectURL(v string) *CardUpdateOne {
	_u.mutation.SetDirectURL(v)
	return _u
}

// SetNillableDirectURL sets the "direct_url" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableDirectURL(v *string) *CardUpdateOne {
	if v != nil {
		_u.SetDirectURL(*v)
	}
	return _u
}

// SetPlatformID sets the "platform_id" field.
func (_u *CardUpdateOne) SetPlatformID(v string) *CardUpdateOne {
	_u.mutation.SetPlatformID(v)
	return _u
}

// SetNillablePlatformID sets the "platform_id" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillablePlatformID(v *string) *CardUpdateOne {
	if v != nil {
		_u.SetPlatformID(*v)
	}
	return _u
}

// SetCharacterID sets the "character_id" field.
func (_u *CardUpdateOne) SetCharacterID(v string) *CardUpdateOne {
	_u.mutation.SetCharacterID(v)
	return _u
}

// SetNillableCharacterID sets the "character_id" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableCharacterID(v *string) *CardUpdateOne {
	if v != nil {
		_u.SetCharacterID(*v)
	}
	return _u
}

// SetCardName sets the "card_name" field.
func (_u *CardUpdateOne) SetCardName(v string) *CardUpdateOne {
	_u.mutation.SetCardName(v)
	return _u
}

// SetNillableCardName sets the "card_name" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableCardName(v *string) *CardUpdateOne {
	if v != nil {
		_u.SetCardName(*v)
	}
	return _u
}

// SetCharacterName sets the "character_name" field.
func (_u *CardUpdateOne) SetCharacterName(v string) *CardUpdateOne {
	_u.mutation.SetCharacterName(v)
	return _u
}

// SetNillableCharacterName sets the "character_name" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableCharacterName(v *string) *CardUpdateOne {
	if v != nil {
		_u.SetCharacterName(*v)
	}
	return _u
}

// SetCreator sets the "creator" field.
func (_u *CardUpdateOne) SetCreator(v string) *CardUpdateOne {
	_u.mutation.SetCreator(v)
	return _u
}

// SetNillableCreator sets the "creator" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableCreator(v *string) *CardUpdateOne {
	if v != nil {
		_u.SetCreator(*v)
	}
	return _u
}

// SetTagline sets the "tagline" field.
func (_u *CardUpdateOne) SetTagline(v string) *CardUpdateOne {
	_u.mutation.SetTagline(v)
	return _u
}

// SetNillableTagline sets the "tagline" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableTagline(v *string) *CardUpdateOne {
	if v != nil {
		_u.SetTagline(*v)
	}
	return _u
}

// SetCreateTime sets the "create_time" field.
func (_u *CardUpdateOne) SetCreateTime(v timestamp.Nano) *CardUpdateOne {
	_u.mutation.ResetCreateTime()
	_u.mutation.SetCreateTime(v)
	return _u
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableCreateTime(v *timestamp.Nano) *CardUpdateOne {
	if v != nil {
		_u.SetCreateTime(*v)
	}
	return _u
}

// AddCreateTime adds value to the "create_time" field.
func (_u *CardUpdateOne) AddCreateTime(v timestamp.Nano) *CardUpdateOne {
	_u.mutation.AddCreateTime(v)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *CardUpdateOne) SetUpdateTime(v timestamp.Nano) *CardUpdateOne {
	_u.mutation.ResetUpdateTime()
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableUpdateTime(v *timestamp.Nano) *CardUpdateOne {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// AddUpdateTime adds value to the "update_time" field.
func (_u *CardUpdateOne) AddUpdateTime(v timestamp.Nano) *CardUpdateOne {
	_u.mutation.AddUpdateTime(v)
	return _u
}

// SetBookUpdateTime sets the "book_update_time" field.
func (_u *CardUpdateOne) SetBookUpdateTime(v timestamp.Nano) *CardUpdateOne {
	_u.mutation.ResetBookUpdateTime()
	_u.mutation.SetBookUpdateTime(v)
	return _u
}

// SetNillableBookUpdateTime sets the "book_update_time" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableBookUpdateTime(v *timestamp.Nano) *CardUpdateOne {
	if v != nil {
		_u.SetBookUpdateTime(*v)
	}
	return _u
}

// AddBookUpdateTime adds value to the "book_update_time" field.
func (_u *CardUpdateOne) AddBookUpdateTime(v timestamp.Nano) *CardUpdateOne {
	_u.mutation.AddBookUpdateTime(v)
	return _u
}

// SetImportTime sets the "import_time" field.
func (_u *CardUpdateOne) SetImportTime(v timestamp.Nano) *CardUpdateOne {
	_u.mutation.ResetImportTime()
	_u.mutation.SetImportTime(v)
	return _u
}

// SetNillableImportTime sets the "import_time" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableImportTime(v *timestamp.Nano) *CardUpdateOne {
	if v != nil {
		_u.SetImportTime(*v)
	}
	return _u
}

// AddImportTime adds value to the "import_time" field.
func (_u *CardUpdateOne) AddImportTime(v timestamp.Nano) *CardUpdateOne {
	_u.mutation.AddImportTime(v)
	return _u
}

// SetCheckTime sets the "check_time" field.
func (_u *CardUpdateOne) SetCheckTime(v timestamp.Nano) *CardUpdateOne {
	_u.mutation.ResetCheckTime()
	_u.mutation.SetCheckTime(v)
	return _u
}

// SetNillableCheckTime sets the "check_time" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableCheckTime(v *timestamp.Nano) *CardUpdateOne {
	if v != nil {
		_u.SetCheckTime(*v)
	}
	return _u
}

// AddCheckTime adds value to the "check_time" field.
func (_u *CardUpdateOne) AddCheckTime(v timestamp.Nano) *CardUpdateOne {
	_u.mutation.AddCheckTime(v)
	return _u
}

// SetLastUpdateStatus sets the "last_update_status" field.
func (_u *CardUpdateOne) SetLastUpdateStatus(v scheme.UpdateStatus) *CardUpdateOne {
	_u.mutation.SetLastUpdateStatus(v)
	return _u
}

// SetNillableLastUpdateStatus sets the "last_update_status" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableLastUpdateStatus(v *scheme.UpdateStatus) *CardUpdateOne {
	if v != nil {
		_u.SetLastUpdateStatus(*v)
	}
	return _u
}

// SetExportTime sets the "export_time" field.
func (_u *CardUpdateOne) SetExportTime(v timestamp.Nano) *CardUpdateOne {
	_u.mutation.ResetExportTime()
	_u.mutation.SetExportTime(v)
	return _u
}

// SetNillableExportTime sets the "export_time" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableExportTime(v *timestamp.Nano) *CardUpdateOne {
	if v != nil {
		_u.SetExportTime(*v)
	}
	return _u
}

// AddExportTime adds value to the "export_time" field.
func (_u *CardUpdateOne) AddExportTime(v timestamp.Nano) *CardUpdateOne {
	_u.mutation.AddExportTime(v)
	return _u
}

// SetLastExportedVersion sets the "last_exported_version" field.
func (_u *CardUpdateOne) SetLastExportedVersion(v timestamp.Nano) *CardUpdateOne {
	_u.mutation.ResetLastExportedVersion()
	_u.mutation.SetLastExportedVersion(v)
	return _u
}

// SetNillableLastExportedVersion sets the "last_exported_version" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableLastExportedVersion(v *timestamp.Nano) *CardUpdateOne {
	if v != nil {
		_u.SetLastExportedVersion(*v)
	}
	return _u
}

// AddLastExportedVersion adds value to the "last_exported_version" field.
func (_u *CardUpdateOne) AddLastExportedVersion(v timestamp.Nano) *CardUpdateOne {
	_u.mutation.AddLastExportedVersion(v)
	return _u
}

// SetFavorite sets the "favorite" field.
func (_u *CardUpdateOne) SetFavorite(v bool) *CardUpdateOne {
	_u.mutation.SetFavorite(v)
	return _u
}

// SetNillableFavorite sets the "favorite" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableFavorite(v *bool) *CardUpdateOne {
	if v != nil {
		_u.SetFavorite(*v)
	}
	return _u
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (_u *CardUpdateOne) AddTagIDs(ids ...scheme.TagID) *CardUpdateOne {
	_u.mutation.AddTagIDs(ids...)
	return _u
}

// AddTags adds the "tags" edges to the Tag entity.
func (_u *CardUpdateOne) AddTags(v ...*Tag) *CardUpdateOne {
	ids := make([]scheme.TagID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTagIDs(ids...)
}

// Mutation returns the CardMutation object of the builder.
func (_u *CardUpdateOne) Mutation() *CardMutation {
	return _u.mutation
}

// ClearTags clears all "tags" edges to the Tag entity.
func (_u *CardUpdateOne) ClearTags() *CardUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// RemoveTagIDs removes the "tags" edge to Tag entities by IDs.
func (_u *CardUpdateOne) RemoveTagIDs(ids ...scheme.TagID) *CardUpdateOne {
	_u.mutation.RemoveTagIDs(ids...)
	return _u
}

// RemoveTags removes "tags" edges to Tag entities.
func (_u *CardUpdateOne) RemoveTags(v ...*Tag) *CardUpdateOne {
	ids := make([]scheme.TagID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTagIDs(ids...)
}

// Where appends a list predicates to the CardUpdate builder.
func (_u *CardUpdateOne) Where(ps ...predicate.Card) *CardUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CardUpdateOne) Select(field string, fields ...string) *CardUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Card entity.
func (_u *CardUpdateOne) Save(ctx context.Context) (*Card, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CardUpdateOne) SaveX(ctx context.Context) *Card {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CardUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CardUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CardUpdateOne) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := card.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Card.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastUpdateStatus(); ok {
		if err := card.LastUpdateStatusValidator(v); err != nil {
			return &ValidationError{Name: "last_update_status", err: fmt.Errorf(`ent: validator failed for field "Card.last_update_status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CardUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CardUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CardUpdateOne) sqlSave(ctx context.Context) (_node *Card, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(card.Table, card.Columns, sqlgraph.NewFieldSpec(card.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Card.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, card.FieldID)
		for _, f := range fields {
			if !card.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != card.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BatchOrder(); ok {
		_spec.SetField(card.FieldBatchOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBatchOrder(); ok {
		_spec.AddField(card.FieldBatchOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(card.FieldSource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CardURL(); ok {
		_spec.SetField(card.FieldCardURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.DirectURL(); ok {
		_spec.SetField(card.FieldDirectURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlatformID(); ok {
		_spec.SetField(card.FieldPlatformID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CharacterID(); ok {
		_spec.SetField(card.FieldCharacterID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CardName(); ok {
		_spec.SetField(card.FieldCardName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CharacterName(); ok {
		_spec.SetField(card.FieldCharacterName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Creator(); ok {
		_spec.SetField(card.FieldCreator, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tagline(); ok {
		_spec.SetField(card.FieldTagline, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreateTime(); ok {
		_spec.SetField(card.FieldCreateTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreateTime(); ok {
		_spec.AddField(card.FieldCreateTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(card.FieldUpdateTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdateTime(); ok {
		_spec.AddField(card.FieldUpdateTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BookUpdateTime(); ok {
		_spec.SetField(card.FieldBookUpdateTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBookUpdateTime(); ok {
		_spec.AddField(card.FieldBookUpdateTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ImportTime(); ok {
		_spec.SetField(card.FieldImportTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedImportTime(); ok {
		_spec.AddField(card.FieldImportTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CheckTime(); ok {
		_spec.SetField(card.FieldCheckTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCheckTime(); ok {
		_spec.AddField(card.FieldCheckTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastUpdateStatus(); ok {
		_spec.SetField(card.FieldLastUpdateStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ExportTime(); ok {
		_spec.SetField(card.FieldExportTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedExportTime(); ok {
		_spec.AddField(card.FieldExportTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastExportedVersion(); ok {
		_spec.SetField(card.FieldLastExportedVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastExportedVersion(); ok {
		_spec.AddField(card.FieldLastExportedVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Favorite(); ok {
		_spec.SetField(card.FieldFavorite, field.TypeBool, value)
	}
	if _u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   card.TagsTable,
			Columns: card.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTagsIDs(); len(nodes) > 0 && !_u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   card.TagsTable,
			Columns: card.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   card.TagsTable,
			Columns: card.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Card{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{card.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
