// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/r3dpixel/card-client/internal/ent/card"
	"github.com/r3dpixel/card-client/internal/ent/schema"
	"github.com/r3dpixel/card-client/services/scheme"
	"github.com/r3dpixel/toolkit/timestamp"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	cardFields := schema.Card{}.Fields()
	_ = cardFields
	// cardDescBatchOrder is the schema descriptor for batch_order field.
	cardDescBatchOrder := cardFields[1].Descriptor()
	// card.DefaultBatchOrder holds the default value on creation for the batch_order field.
	card.DefaultBatchOrder = cardDescBatchOrder.Default.(int)
	// cardDescBookUpdateTime is the schema descriptor for book_update_time field.
	cardDescBookUpdateTime := cardFields[13].Descriptor()
	// card.DefaultBookUpdateTime holds the default value on creation for the book_update_time field.
	card.DefaultBookUpdateTime = timestamp.Nano(cardDescBookUpdateTime.Default.(int64))
	// cardDescExportTime is the schema descriptor for export_time field.
	cardDescExportTime := cardFields[17].Descriptor()
	// card.DefaultExportTime holds the default value on creation for the export_time field.
	card.DefaultExportTime = timestamp.Nano(cardDescExportTime.Default.(int64))
	// cardDescLastExportedVersion is the schema descriptor for last_exported_version field.
	cardDescLastExportedVersion := cardFields[18].Descriptor()
	// card.DefaultLastExportedVersion holds the default value on creation for the last_exported_version field.
	card.DefaultLastExportedVersion = timestamp.Nano(cardDescLastExportedVersion.Default.(int64))
	// cardDescFavorite is the schema descriptor for favorite field.
	cardDescFavorite := cardFields[19].Descriptor()
	// card.DefaultFavorite holds the default value on creation for the favorite field.
	card.DefaultFavorite = cardDescFavorite.Default.(bool)
	// cardDescID is the schema descriptor for id field.
	cardDescID := cardFields[0].Descriptor()
	// card.DefaultID holds the default value on creation for the id field.
	card.DefaultID = cardDescID.Default.(func() scheme.CardID)
}
