// Code generated by ent, DO NOT EDIT.

package card

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/r3dpixel/card-client/services/scheme"
	"github.com/r3dpixel/card-fetcher/source"
	"github.com/r3dpixel/toolkit/timestamp"
)

const (
	// Label holds the string label denoting the card type in the database.
	Label = "card"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBatchOrder holds the string denoting the batch_order field in the database.
	FieldBatchOrder = "batch_order"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldCardURL holds the string denoting the card_url field in the database.
	FieldCardURL = "card_url"
	// FieldDirectURL holds the string denoting the direct_url field in the database.
	FieldDirectURL = "direct_url"
	// FieldPlatformID holds the string denoting the platform_id field in the database.
	FieldPlatformID = "platform_id"
	// FieldCharacterID holds the string denoting the character_id field in the database.
	FieldCharacterID = "character_id"
	// FieldCardName holds the string denoting the card_name field in the database.
	FieldCardName = "card_name"
	// FieldCharacterName holds the string denoting the character_name field in the database.
	FieldCharacterName = "character_name"
	// FieldCreator holds the string denoting the creator field in the database.
	FieldCreator = "creator"
	// FieldTagline holds the string denoting the tagline field in the database.
	FieldTagline = "tagline"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldBookUpdateTime holds the string denoting the book_update_time field in the database.
	FieldBookUpdateTime = "book_update_time"
	// FieldImportTime holds the string denoting the import_time field in the database.
	FieldImportTime = "import_time"
	// FieldCheckTime holds the string denoting the check_time field in the database.
	FieldCheckTime = "check_time"
	// FieldLastUpdateStatus holds the string denoting the last_update_status field in the database.
	FieldLastUpdateStatus = "last_update_status"
	// FieldExportTime holds the string denoting the export_time field in the database.
	FieldExportTime = "export_time"
	// FieldLastExportedVersion holds the string denoting the last_exported_version field in the database.
	FieldLastExportedVersion = "last_exported_version"
	// FieldFavorite holds the string denoting the favorite field in the database.
	FieldFavorite = "favorite"
	// EdgeTags holds the string denoting the tags edge name in mutations.
	EdgeTags = "tags"
	// Table holds the table name of the card in the database.
	Table = "cards"
	// TagsTable is the table that holds the tags relation/edge. The primary key declared below.
	TagsTable = "card_tags"
	// TagsInverseTable is the table name for the Tag entity.
	// It exists in this package in order to avoid circular dependency with the "tag" package.
	TagsInverseTable = "tags"
)

// Columns holds all SQL columns for card fields.
var Columns = []string{
	FieldID,
	FieldBatchOrder,
	FieldSource,
	FieldCardURL,
	FieldDirectURL,
	FieldPlatformID,
	FieldCharacterID,
	FieldCardName,
	FieldCharacterName,
	FieldCreator,
	FieldTagline,
	FieldCreateTime,
	FieldUpdateTime,
	FieldBookUpdateTime,
	FieldImportTime,
	FieldCheckTime,
	FieldLastUpdateStatus,
	FieldExportTime,
	FieldLastExportedVersion,
	FieldFavorite,
}

var (
	// TagsPrimaryKey and TagsColumn2 are the table columns denoting the
	// primary key for the tags relation (M2M).
	TagsPrimaryKey = []string{"card_id", "tag_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultBatchOrder holds the default value on creation for the "batch_order" field.
	DefaultBatchOrder int
	// DefaultBookUpdateTime holds the default value on creation for the "book_update_time" field.
	DefaultBookUpdateTime timestamp.Nano
	// DefaultExportTime holds the default value on creation for the "export_time" field.
	DefaultExportTime timestamp.Nano
	// DefaultLastExportedVersion holds the default value on creation for the "last_exported_version" field.
	DefaultLastExportedVersion timestamp.Nano
	// DefaultFavorite holds the default value on creation for the "favorite" field.
	DefaultFavorite bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() scheme.CardID
)

// SourceValidator is a validator for the "source" field enum values. It is called by the builders before save.
func SourceValidator(s source.ID) error {
	switch s {
	case "File", "CharacterTavern", "ChubAI", "NyaiMe", "PepHop", "Pygmalion", "WyvernChat", "RisuAI", "AICharacterCard":
		return nil
	default:
		return fmt.Errorf("card: invalid enum value for source field: %q", s)
	}
}

// LastUpdateStatusValidator is a validator for the "last_update_status" field enum values. It is called by the builders before save.
func LastUpdateStatusValidator(lus scheme.UpdateStatus) error {
	switch lus {
	case "UNCHANGED", "SUCCESS", "FAILED":
		return nil
	default:
		return fmt.Errorf("card: invalid enum value for last_update_status field: %q", lus)
	}
}

// OrderOption defines the ordering options for the Card queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBatchOrder orders the results by the batch_order field.
func ByBatchOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBatchOrder, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByCardURL orders the results by the card_url field.
func ByCardURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCardURL, opts...).ToFunc()
}

// ByDirectURL orders the results by the direct_url field.
func ByDirectURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDirectURL, opts...).ToFunc()
}

// ByPlatformID orders the results by the platform_id field.
func ByPlatformID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatformID, opts...).ToFunc()
}

// ByCharacterID orders the results by the character_id field.
func ByCharacterID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCharacterID, opts...).ToFunc()
}

// ByCardName orders the results by the card_name field.
func ByCardName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCardName, opts...).ToFunc()
}

// ByCharacterName orders the results by the character_name field.
func ByCharacterName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCharacterName, opts...).ToFunc()
}

// ByCreator orders the results by the creator field.
func ByCreator(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreator, opts...).ToFunc()
}

// ByTagline orders the results by the tagline field.
func ByTagline(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTagline, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByBookUpdateTime orders the results by the book_update_time field.
func ByBookUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBookUpdateTime, opts...).ToFunc()
}

// ByImportTime orders the results by the import_time field.
func ByImportTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImportTime, opts...).ToFunc()
}

// ByCheckTime orders the results by the check_time field.
func ByCheckTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCheckTime, opts...).ToFunc()
}

// ByLastUpdateStatus orders the results by the last_update_status field.
func ByLastUpdateStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastUpdateStatus, opts...).ToFunc()
}

// ByExportTime orders the results by the export_time field.
func ByExportTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExportTime, opts...).ToFunc()
}

// ByLastExportedVersion orders the results by the last_exported_version field.
func ByLastExportedVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastExportedVersion, opts...).ToFunc()
}

// ByFavorite orders the results by the favorite field.
func ByFavorite(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFavorite, opts...).ToFunc()
}

// ByTagsCount orders the results by tags count.
func ByTagsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTagsStep(), opts...)
	}
}

// ByTags orders the results by tags terms.
func ByTags(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTagsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTagsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TagsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, TagsTable, TagsPrimaryKey...),
	)
}
