// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CreatorsColumns holds the columns for the "creators" table.
	CreatorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "nickname", Type: field.TypeString},
		{Name: "username", Type: field.TypeString},
		{Name: "platform_id", Type: field.TypeString},
		{Name: "source", Type: field.TypeEnum, Enums: []string{"Local", "CharacterTavern", "ChubAI", "NyaiMe", "PepHop", "Pygmalion", "WyvernChat", "JannyAI", "AICC"}},
	}
	// CreatorsTable holds the schema information for the "creators" table.
	CreatorsTable = &schema.Table{
		Name:       "creators",
		Columns:    CreatorsColumns,
		PrimaryKey: []*schema.Column{CreatorsColumns[0]},
	}
	// RecordsColumns holds the columns for the "records" table.
	RecordsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "import_index", Type: field.TypeInt},
		{Name: "import_time", Type: field.TypeInt64},
		{Name: "source", Type: field.TypeEnum, Enums: []string{"Local", "CharacterTavern", "ChubAI", "NyaiMe", "PepHop", "Pygmalion", "WyvernChat", "JannyAI", "AICC"}},
		{Name: "normalized_url", Type: field.TypeString},
		{Name: "direct_url", Type: field.TypeString},
		{Name: "platform_id", Type: field.TypeString},
		{Name: "character_id", Type: field.TypeString},
		{Name: "title", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "tagline", Type: field.TypeString},
		{Name: "create_time", Type: field.TypeInt64},
		{Name: "update_time", Type: field.TypeInt64},
		{Name: "is_fork", Type: field.TypeBool, Default: false},
		{Name: "book_update_time", Type: field.TypeInt64},
		{Name: "greetings_count", Type: field.TypeInt, Default: -1},
		{Name: "sync_status", Type: field.TypeEnum, Enums: []string{"UNCHANGED", "SUCCESS", "FAILED", "MISSING"}},
		{Name: "sync_time", Type: field.TypeInt64},
		{Name: "exported_version", Type: field.TypeInt64},
		{Name: "export_time", Type: field.TypeInt64},
		{Name: "favorite", Type: field.TypeBool},
		{Name: "creator_id", Type: field.TypeString},
	}
	// RecordsTable holds the schema information for the "records" table.
	RecordsTable = &schema.Table{
		Name:       "records",
		Columns:    RecordsColumns,
		PrimaryKey: []*schema.Column{RecordsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "records_creators_creator",
				Columns:    []*schema.Column{RecordsColumns[21]},
				RefColumns: []*schema.Column{CreatorsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "idx_record_character_id",
				Unique:  true,
				Columns: []*schema.Column{RecordsColumns[3], RecordsColumns[7]},
			},
			{
				Name:    "idx_record_platform_id",
				Unique:  true,
				Columns: []*schema.Column{RecordsColumns[3], RecordsColumns[6]},
			},
			{
				Name:    "idx_record_normalized_url",
				Unique:  true,
				Columns: []*schema.Column{RecordsColumns[4]},
			},
		},
	}
	// TagsColumns holds the columns for the "tags" table.
	TagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
	}
	// TagsTable holds the schema information for the "tags" table.
	TagsTable = &schema.Table{
		Name:       "tags",
		Columns:    TagsColumns,
		PrimaryKey: []*schema.Column{TagsColumns[0]},
	}
	// RecordTagsColumns holds the columns for the "record_tags" table.
	RecordTagsColumns = []*schema.Column{
		{Name: "record_entity_id", Type: field.TypeUint64},
		{Name: "tag_entity_id", Type: field.TypeString},
	}
	// RecordTagsTable holds the schema information for the "record_tags" table.
	RecordTagsTable = &schema.Table{
		Name:       "record_tags",
		Columns:    RecordTagsColumns,
		PrimaryKey: []*schema.Column{RecordTagsColumns[0], RecordTagsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "record_tags_record_entity_id",
				Columns:    []*schema.Column{RecordTagsColumns[0]},
				RefColumns: []*schema.Column{RecordsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "record_tags_tag_entity_id",
				Columns:    []*schema.Column{RecordTagsColumns[1]},
				RefColumns: []*schema.Column{TagsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CreatorsTable,
		RecordsTable,
		TagsTable,
		RecordTagsTable,
	}
)

func init() {
	CreatorsTable.Annotation = &entsql.Annotation{
		Table: "creators",
	}
	RecordsTable.ForeignKeys[0].RefTable = CreatorsTable
	RecordsTable.Annotation = &entsql.Annotation{
		Table: "records",
	}
	TagsTable.Annotation = &entsql.Annotation{
		Table: "tags",
	}
	RecordTagsTable.ForeignKeys[0].RefTable = RecordsTable
	RecordTagsTable.ForeignKeys[1].RefTable = TagsTable
}
