// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/r3dpixel/card-client/internal/ent/card"
	"github.com/r3dpixel/card-client/internal/ent/tag"
	"github.com/r3dpixel/card-client/services/scheme"
	"github.com/r3dpixel/card-fetcher/source"
	"github.com/r3dpixel/toolkit/timestamp"
)

// CardCreate is the builder for creating a Card entity.
type CardCreate struct {
	config
	mutation *CardMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetBatchOrder sets the "batch_order" field.
func (_c *CardCreate) SetBatchOrder(v int) *CardCreate {
	_c.mutation.SetBatchOrder(v)
	return _c
}

// SetNillableBatchOrder sets the "batch_order" field if the given value is not nil.
func (_c *CardCreate) SetNillableBatchOrder(v *int) *CardCreate {
	if v != nil {
		_c.SetBatchOrder(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *CardCreate) SetSource(v source.ID) *CardCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetCardURL sets the "card_url" field.
func (_c *CardCreate) SetCardURL(v string) *CardCreate {
	_c.mutation.SetCardURL(v)
	return _c
}

// SetDirectURL sets the "direct_url" field.
func (_c *CardCreate) SetDirectURL(v string) *CardCreate {
	_c.mutation.SetDirectURL(v)
	return _c
}

// SetPlatformID sets the "platform_id" field.
func (_c *CardCreate) SetPlatformID(v string) *CardCreate {
	_c.mutation.SetPlatformID(v)
	return _c
}

// SetCharacterID sets the "character_id" field.
func (_c *CardCreate) SetCharacterID(v string) *CardCreate {
	_c.mutation.SetCharacterID(v)
	return _c
}

// SetCardName sets the "card_name" field.
func (_c *CardCreate) SetCardName(v string) *CardCreate {
	_c.mutation.SetCardName(v)
	return _c
}

// SetCharacterName sets the "character_name" field.
func (_c *CardCreate) SetCharacterName(v string) *CardCreate {
	_c.mutation.SetCharacterName(v)
	return _c
}

// SetCreator sets the "creator" field.
func (_c *CardCreate) SetCreator(v string) *CardCreate {
	_c.mutation.SetCreator(v)
	return _c
}

// SetTagline sets the "tagline" field.
func (_c *CardCreate) SetTagline(v string) *CardCreate {
	_c.mutation.SetTagline(v)
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *CardCreate) SetCreateTime(v timestamp.Nano) *CardCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *CardCreate) SetUpdateTime(v timestamp.Nano) *CardCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetBookUpdateTime sets the "book_update_time" field.
func (_c *CardCreate) SetBookUpdateTime(v timestamp.Nano) *CardCreate {
	_c.mutation.SetBookUpdateTime(v)
	return _c
}

// SetNillableBookUpdateTime sets the "book_update_time" field if the given value is not nil.
func (_c *CardCreate) SetNillableBookUpdateTime(v *timestamp.Nano) *CardCreate {
	if v != nil {
		_c.SetBookUpdateTime(*v)
	}
	return _c
}

// SetImportTime sets the "import_time" field.
func (_c *CardCreate) SetImportTime(v timestamp.Nano) *CardCreate {
	_c.mutation.SetImportTime(v)
	return _c
}

// SetCheckTime sets the "check_time" field.
func (_c *CardCreate) SetCheckTime(v timestamp.Nano) *CardCreate {
	_c.mutation.SetCheckTime(v)
	return _c
}

// SetLastUpdateStatus sets the "last_update_status" field.
func (_c *CardCreate) SetLastUpdateStatus(v scheme.UpdateStatus) *CardCreate {
	_c.mutation.SetLastUpdateStatus(v)
	return _c
}

// SetExportTime sets the "export_time" field.
func (_c *CardCreate) SetExportTime(v timestamp.Nano) *CardCreate {
	_c.mutation.SetExportTime(v)
	return _c
}

// SetNillableExportTime sets the "export_time" field if the given value is not nil.
func (_c *CardCreate) SetNillableExportTime(v *timestamp.Nano) *CardCreate {
	if v != nil {
		_c.SetExportTime(*v)
	}
	return _c
}

// SetLastExportedVersion sets the "last_exported_version" field.
func (_c *CardCreate) SetLastExportedVersion(v timestamp.Nano) *CardCreate {
	_c.mutation.SetLastExportedVersion(v)
	return _c
}

// SetNillableLastExportedVersion sets the "last_exported_version" field if the given value is not nil.
func (_c *CardCreate) SetNillableLastExportedVersion(v *timestamp.Nano) *CardCreate {
	if v != nil {
		_c.SetLastExportedVersion(*v)
	}
	return _c
}

// SetFavorite sets the "favorite" field.
func (_c *CardCreate) SetFavorite(v bool) *CardCreate {
	_c.mutation.SetFavorite(v)
	return _c
}

// SetNillableFavorite sets the "favorite" field if the given value is not nil.
func (_c *CardCreate) SetNillableFavorite(v *bool) *CardCreate {
	if v != nil {
		_c.SetFavorite(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CardCreate) SetID(v scheme.CardID) *CardCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *CardCreate) SetNillableID(v *scheme.CardID) *CardCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (_c *CardCreate) AddTagIDs(ids ...scheme.TagID) *CardCreate {
	_c.mutation.AddTagIDs(ids...)
	return _c
}

// AddTags adds the "tags" edges to the Tag entity.
func (_c *CardCreate) AddTags(v ...*Tag) *CardCreate {
	ids := make([]scheme.TagID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTagIDs(ids...)
}

// Mutation returns the CardMutation object of the builder.
func (_c *CardCreate) Mutation() *CardMutation {
	return _c.mutation
}

// Save creates the Card in the database.
func (_c *CardCreate) Save(ctx context.Context) (*Card, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CardCreate) SaveX(ctx context.Context) *Card {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CardCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CardCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CardCreate) defaults() {
	if _, ok := _c.mutation.BatchOrder(); !ok {
		v := card.DefaultBatchOrder
		_c.mutation.SetBatchOrder(v)
	}
	if _, ok := _c.mutation.BookUpdateTime(); !ok {
		v := card.DefaultBookUpdateTime
		_c.mutation.SetBookUpdateTime(v)
	}
	if _, ok := _c.mutation.ExportTime(); !ok {
		v := card.DefaultExportTime
		_c.mutation.SetExportTime(v)
	}
	if _, ok := _c.mutation.LastExportedVersion(); !ok {
		v := card.DefaultLastExportedVersion
		_c.mutation.SetLastExportedVersion(v)
	}
	if _, ok := _c.mutation.Favorite(); !ok {
		v := card.DefaultFavorite
		_c.mutation.SetFavorite(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := card.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CardCreate) check() error {
	if _, ok := _c.mutation.BatchOrder(); !ok {
		return &ValidationError{Name: "batch_order", err: errors.New(`ent: missing required field "Card.batch_order"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "Card.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := card.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Card.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CardURL(); !ok {
		return &ValidationError{Name: "card_url", err: errors.New(`ent: missing required field "Card.card_url"`)}
	}
	if _, ok := _c.mutation.DirectURL(); !ok {
		return &ValidationError{Name: "direct_url", err: errors.New(`ent: missing required field "Card.direct_url"`)}
	}
	if _, ok := _c.mutation.PlatformID(); !ok {
		return &ValidationError{Name: "platform_id", err: errors.New(`ent: missing required field "Card.platform_id"`)}
	}
	if _, ok := _c.mutation.CharacterID(); !ok {
		return &ValidationError{Name: "character_id", err: errors.New(`ent: missing required field "Card.character_id"`)}
	}
	if _, ok := _c.mutation.CardName(); !ok {
		return &ValidationError{Name: "card_name", err: errors.New(`ent: missing required field "Card.card_name"`)}
	}
	if _, ok := _c.mutation.CharacterName(); !ok {
		return &ValidationError{Name: "character_name", err: errors.New(`ent: missing required field "Card.character_name"`)}
	}
	if _, ok := _c.mutation.Creator(); !ok {
		return &ValidationError{Name: "creator", err: errors.New(`ent: missing required field "Card.creator"`)}
	}
	if _, ok := _c.mutation.Tagline(); !ok {
		return &ValidationError{Name: "tagline", err: errors.New(`ent: missing required field "Card.tagline"`)}
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Card.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Card.update_time"`)}
	}
	if _, ok := _c.mutation.BookUpdateTime(); !ok {
		return &ValidationError{Name: "book_update_time", err: errors.New(`ent: missing required field "Card.book_update_time"`)}
	}
	if _, ok := _c.mutation.ImportTime(); !ok {
		return &ValidationError{Name: "import_time", err: errors.New(`ent: missing required field "Card.import_time"`)}
	}
	if _, ok := _c.mutation.CheckTime(); !ok {
		return &ValidationError{Name: "check_time", err: errors.New(`ent: missing required field "Card.check_time"`)}
	}
	if _, ok := _c.mutation.LastUpdateStatus(); !ok {
		return &ValidationError{Name: "last_update_status", err: errors.New(`ent: missing required field "Card.last_update_status"`)}
	}
	if v, ok := _c.mutation.LastUpdateStatus(); ok {
		if err := card.LastUpdateStatusValidator(v); err != nil {
			return &ValidationError{Name: "last_update_status", err: fmt.Errorf(`ent: validator failed for field "Card.last_update_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExportTime(); !ok {
		return &ValidationError{Name: "export_time", err: errors.New(`ent: missing required field "Card.export_time"`)}
	}
	if _, ok := _c.mutation.LastExportedVersion(); !ok {
		return &ValidationError{Name: "last_exported_version", err: errors.New(`ent: missing required field "Card.last_exported_version"`)}
	}
	if _, ok := _c.mutation.Favorite(); !ok {
		return &ValidationError{Name: "favorite", err: errors.New(`ent: missing required field "Card.favorite"`)}
	}
	return nil
}

func (_c *CardCreate) sqlSave(ctx context.Context) (*Card, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*scheme.CardID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CardCreate) createSpec() (*Card, *sqlgraph.CreateSpec) {
	var (
		_node = &Card{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(card.Table, sqlgraph.NewFieldSpec(card.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.BatchOrder(); ok {
		_spec.SetField(card.FieldBatchOrder, field.TypeInt, value)
		_node.BatchOrder = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(card.FieldSource, field.TypeEnum, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.CardURL(); ok {
		_spec.SetField(card.FieldCardURL, field.TypeString, value)
		_node.CardURL = value
	}
	if value, ok := _c.mutation.DirectURL(); ok {
		_spec.SetField(card.FieldDirectURL, field.TypeString, value)
		_node.DirectURL = value
	}
	if value, ok := _c.mutation.PlatformID(); ok {
		_spec.SetField(card.FieldPlatformID, field.TypeString, value)
		_node.PlatformID = value
	}
	if value, ok := _c.mutation.CharacterID(); ok {
		_spec.SetField(card.FieldCharacterID, field.TypeString, value)
		_node.CharacterID = value
	}
	if value, ok := _c.mutation.CardName(); ok {
		_spec.SetField(card.FieldCardName, field.TypeString, value)
		_node.CardName = value
	}
	if value, ok := _c.mutation.CharacterName(); ok {
		_spec.SetField(card.FieldCharacterName, field.TypeString, value)
		_node.CharacterName = value
	}
	if value, ok := _c.mutation.Creator(); ok {
		_spec.SetField(card.FieldCreator, field.TypeString, value)
		_node.Creator = value
	}
	if value, ok := _c.mutation.Tagline(); ok {
		_spec.SetField(card.FieldTagline, field.TypeString, value)
		_node.Tagline = value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(card.FieldCreateTime, field.TypeInt64, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(card.FieldUpdateTime, field.TypeInt64, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.BookUpdateTime(); ok {
		_spec.SetField(card.FieldBookUpdateTime, field.TypeInt64, value)
		_node.BookUpdateTime = value
	}
	if value, ok := _c.mutation.ImportTime(); ok {
		_spec.SetField(card.FieldImportTime, field.TypeInt64, value)
		_node.ImportTime = value
	}
	if value, ok := _c.mutation.CheckTime(); ok {
		_spec.SetField(card.FieldCheckTime, field.TypeInt64, value)
		_node.CheckTime = value
	}
	if value, ok := _c.mutation.LastUpdateStatus(); ok {
		_spec.SetField(card.FieldLastUpdateStatus, field.TypeEnum, value)
		_node.LastUpdateStatus = value
	}
	if value, ok := _c.mutation.ExportTime(); ok {
		_spec.SetField(card.FieldExportTime, field.TypeInt64, value)
		_node.ExportTime = value
	}
	if value, ok := _c.mutation.LastExportedVersion(); ok {
		_spec.SetField(card.FieldLastExportedVersion, field.TypeInt64, value)
		_node.LastExportedVersion = value
	}
	if value, ok := _c.mutation.Favorite(); ok {
		_spec.SetField(card.FieldFavorite, field.TypeBool, value)
		_node.Favorite = value
	}
	if nodes := _c.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   card.TagsTable,
			Columns: card.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Card.Create().
//		SetBatchOrder(v).
//		OnConflict(
//			// UpdateInfoSyncData the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		UpdateInfoSyncData(func(u *ent.CardUpsert) {
//			SetBatchOrder(v+v).
//		}).
//		Exec(ctx)
func (_c *CardCreate) OnConflict(opts ...sql.ConflictOption) *CardUpsertOne {
	_c.conflict = opts
	return &CardUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Card.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CardCreate) OnConflictColumns(columns ...string) *CardUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CardUpsertOne{
		create: _c,
	}
}

type (
	// CardUpsertOne is the builder for "upsert"-ing
	//  one Card node.
	CardUpsertOne struct {
		create *CardCreate
	}

	// CardUpsert is the "OnConflict" setter.
	CardUpsert struct {
		*sql.UpdateSet
	}
)

// SetBatchOrder sets the "batch_order" field.
func (u *CardUpsert) SetBatchOrder(v int) *CardUpsert {
	u.Set(card.FieldBatchOrder, v)
	return u
}

// UpdateBatchOrder sets the "batch_order" field to the value that was provided on create.
func (u *CardUpsert) UpdateBatchOrder() *CardUpsert {
	u.SetExcluded(card.FieldBatchOrder)
	return u
}

// AddBatchOrder adds v to the "batch_order" field.
func (u *CardUpsert) AddBatchOrder(v int) *CardUpsert {
	u.Add(card.FieldBatchOrder, v)
	return u
}

// SetSource sets the "source" field.
func (u *CardUpsert) SetSource(v source.ID) *CardUpsert {
	u.Set(card.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *CardUpsert) UpdateSource() *CardUpsert {
	u.SetExcluded(card.FieldSource)
	return u
}

// SetCardURL sets the "card_url" field.
func (u *CardUpsert) SetCardURL(v string) *CardUpsert {
	u.Set(card.FieldCardURL, v)
	return u
}

// UpdateCardURL sets the "card_url" field to the value that was provided on create.
func (u *CardUpsert) UpdateCardURL() *CardUpsert {
	u.SetExcluded(card.FieldCardURL)
	return u
}

// SetDirectURL sets the "direct_url" field.
func (u *CardUpsert) SetDirectURL(v string) *CardUpsert {
	u.Set(card.FieldDirectURL, v)
	return u
}

// UpdateDirectURL sets the "direct_url" field to the value that was provided on create.
func (u *CardUpsert) UpdateDirectURL() *CardUpsert {
	u.SetExcluded(card.FieldDirectURL)
	return u
}

// SetPlatformID sets the "platform_id" field.
func (u *CardUpsert) SetPlatformID(v string) *CardUpsert {
	u.Set(card.FieldPlatformID, v)
	return u
}

// UpdatePlatformID sets the "platform_id" field to the value that was provided on create.
func (u *CardUpsert) UpdatePlatformID() *CardUpsert {
	u.SetExcluded(card.FieldPlatformID)
	return u
}

// SetCharacterID sets the "character_id" field.
func (u *CardUpsert) SetCharacterID(v string) *CardUpsert {
	u.Set(card.FieldCharacterID, v)
	return u
}

// UpdateCharacterID sets the "character_id" field to the value that was provided on create.
func (u *CardUpsert) UpdateCharacterID() *CardUpsert {
	u.SetExcluded(card.FieldCharacterID)
	return u
}

// SetCardName sets the "card_name" field.
func (u *CardUpsert) SetCardName(v string) *CardUpsert {
	u.Set(card.FieldCardName, v)
	return u
}

// UpdateCardName sets the "card_name" field to the value that was provided on create.
func (u *CardUpsert) UpdateCardName() *CardUpsert {
	u.SetExcluded(card.FieldCardName)
	return u
}

// SetCharacterName sets the "character_name" field.
func (u *CardUpsert) SetCharacterName(v string) *CardUpsert {
	u.Set(card.FieldCharacterName, v)
	return u
}

// UpdateCharacterName sets the "character_name" field to the value that was provided on create.
func (u *CardUpsert) UpdateCharacterName() *CardUpsert {
	u.SetExcluded(card.FieldCharacterName)
	return u
}

// SetCreator sets the "creator" field.
func (u *CardUpsert) SetCreator(v string) *CardUpsert {
	u.Set(card.FieldCreator, v)
	return u
}

// UpdateCreator sets the "creator" field to the value that was provided on create.
func (u *CardUpsert) UpdateCreator() *CardUpsert {
	u.SetExcluded(card.FieldCreator)
	return u
}

// SetTagline sets the "tagline" field.
func (u *CardUpsert) SetTagline(v string) *CardUpsert {
	u.Set(card.FieldTagline, v)
	return u
}

// UpdateTagline sets the "tagline" field to the value that was provided on create.
func (u *CardUpsert) UpdateTagline() *CardUpsert {
	u.SetExcluded(card.FieldTagline)
	return u
}

// SetCreateTime sets the "create_time" field.
func (u *CardUpsert) SetCreateTime(v timestamp.Nano) *CardUpsert {
	u.Set(card.FieldCreateTime, v)
	return u
}

// UpdateCreateTime sets the "create_time" field to the value that was provided on create.
func (u *CardUpsert) UpdateCreateTime() *CardUpsert {
	u.SetExcluded(card.FieldCreateTime)
	return u
}

// AddCreateTime adds v to the "create_time" field.
func (u *CardUpsert) AddCreateTime(v timestamp.Nano) *CardUpsert {
	u.Add(card.FieldCreateTime, v)
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *CardUpsert) SetUpdateTime(v timestamp.Nano) *CardUpsert {
	u.Set(card.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *CardUpsert) UpdateUpdateTime() *CardUpsert {
	u.SetExcluded(card.FieldUpdateTime)
	return u
}

// AddUpdateTime adds v to the "update_time" field.
func (u *CardUpsert) AddUpdateTime(v timestamp.Nano) *CardUpsert {
	u.Add(card.FieldUpdateTime, v)
	return u
}

// SetBookUpdateTime sets the "book_update_time" field.
func (u *CardUpsert) SetBookUpdateTime(v timestamp.Nano) *CardUpsert {
	u.Set(card.FieldBookUpdateTime, v)
	return u
}

// UpdateBookUpdateTime sets the "book_update_time" field to the value that was provided on create.
func (u *CardUpsert) UpdateBookUpdateTime() *CardUpsert {
	u.SetExcluded(card.FieldBookUpdateTime)
	return u
}

// AddBookUpdateTime adds v to the "book_update_time" field.
func (u *CardUpsert) AddBookUpdateTime(v timestamp.Nano) *CardUpsert {
	u.Add(card.FieldBookUpdateTime, v)
	return u
}

// SetImportTime sets the "import_time" field.
func (u *CardUpsert) SetImportTime(v timestamp.Nano) *CardUpsert {
	u.Set(card.FieldImportTime, v)
	return u
}

// UpdateImportTime sets the "import_time" field to the value that was provided on create.
func (u *CardUpsert) UpdateImportTime() *CardUpsert {
	u.SetExcluded(card.FieldImportTime)
	return u
}

// AddImportTime adds v to the "import_time" field.
func (u *CardUpsert) AddImportTime(v timestamp.Nano) *CardUpsert {
	u.Add(card.FieldImportTime, v)
	return u
}

// SetCheckTime sets the "check_time" field.
func (u *CardUpsert) SetCheckTime(v timestamp.Nano) *CardUpsert {
	u.Set(card.FieldCheckTime, v)
	return u
}

// UpdateCheckTime sets the "check_time" field to the value that was provided on create.
func (u *CardUpsert) UpdateCheckTime() *CardUpsert {
	u.SetExcluded(card.FieldCheckTime)
	return u
}

// AddCheckTime adds v to the "check_time" field.
func (u *CardUpsert) AddCheckTime(v timestamp.Nano) *CardUpsert {
	u.Add(card.FieldCheckTime, v)
	return u
}

// SetLastUpdateStatus sets the "last_update_status" field.
func (u *CardUpsert) SetLastUpdateStatus(v scheme.UpdateStatus) *CardUpsert {
	u.Set(card.FieldLastUpdateStatus, v)
	return u
}

// UpdateLastUpdateStatus sets the "last_update_status" field to the value that was provided on create.
func (u *CardUpsert) UpdateLastUpdateStatus() *CardUpsert {
	u.SetExcluded(card.FieldLastUpdateStatus)
	return u
}

// SetExportTime sets the "export_time" field.
func (u *CardUpsert) SetExportTime(v timestamp.Nano) *CardUpsert {
	u.Set(card.FieldExportTime, v)
	return u
}

// UpdateExportTime sets the "export_time" field to the value that was provided on create.
func (u *CardUpsert) UpdateExportTime() *CardUpsert {
	u.SetExcluded(card.FieldExportTime)
	return u
}

// AddExportTime adds v to the "export_time" field.
func (u *CardUpsert) AddExportTime(v timestamp.Nano) *CardUpsert {
	u.Add(card.FieldExportTime, v)
	return u
}

// SetLastExportedVersion sets the "last_exported_version" field.
func (u *CardUpsert) SetLastExportedVersion(v timestamp.Nano) *CardUpsert {
	u.Set(card.FieldLastExportedVersion, v)
	return u
}

// UpdateLastExportedVersion sets the "last_exported_version" field to the value that was provided on create.
func (u *CardUpsert) UpdateLastExportedVersion() *CardUpsert {
	u.SetExcluded(card.FieldLastExportedVersion)
	return u
}

// AddLastExportedVersion adds v to the "last_exported_version" field.
func (u *CardUpsert) AddLastExportedVersion(v timestamp.Nano) *CardUpsert {
	u.Add(card.FieldLastExportedVersion, v)
	return u
}

// SetFavorite sets the "favorite" field.
func (u *CardUpsert) SetFavorite(v bool) *CardUpsert {
	u.Set(card.FieldFavorite, v)
	return u
}

// UpdateFavorite sets the "favorite" field to the value that was provided on create.
func (u *CardUpsert) UpdateFavorite() *CardUpsert {
	u.SetExcluded(card.FieldFavorite)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Card.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(card.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CardUpsertOne) UpdateNewValues() *CardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(card.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Card.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CardUpsertOne) Ignore() *CardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CardUpsertOne) DoNothing() *CardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CardCreate.OnConflict
// documentation for more info.
func (u *CardUpsertOne) Update(set func(*CardUpsert)) *CardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CardUpsert{UpdateSet: update})
	}))
	return u
}

// SetBatchOrder sets the "batch_order" field.
func (u *CardUpsertOne) SetBatchOrder(v int) *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.SetBatchOrder(v)
	})
}

// AddBatchOrder adds v to the "batch_order" field.
func (u *CardUpsertOne) AddBatchOrder(v int) *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.AddBatchOrder(v)
	})
}

// UpdateBatchOrder sets the "batch_order" field to the value that was provided on create.
func (u *CardUpsertOne) UpdateBatchOrder() *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.UpdateBatchOrder()
	})
}

// SetSource sets the "source" field.
func (u *CardUpsertOne) SetSource(v source.ID) *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *CardUpsertOne) UpdateSource() *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.UpdateSource()
	})
}

// SetCardURL sets the "card_url" field.
func (u *CardUpsertOne) SetCardURL(v string) *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.SetCardURL(v)
	})
}

// UpdateCardURL sets the "card_url" field to the value that was provided on create.
func (u *CardUpsertOne) UpdateCardURL() *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.UpdateCardURL()
	})
}

// SetDirectURL sets the "direct_url" field.
func (u *CardUpsertOne) SetDirectURL(v string) *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.SetDirectURL(v)
	})
}

// UpdateDirectURL sets the "direct_url" field to the value that was provided on create.
func (u *CardUpsertOne) UpdateDirectURL() *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.UpdateDirectURL()
	})
}

// SetPlatformID sets the "platform_id" field.
func (u *CardUpsertOne) SetPlatformID(v string) *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.SetPlatformID(v)
	})
}

// UpdatePlatformID sets the "platform_id" field to the value that was provided on create.
func (u *CardUpsertOne) UpdatePlatformID() *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.UpdatePlatformID()
	})
}

// SetCharacterID sets the "character_id" field.
func (u *CardUpsertOne) SetCharacterID(v string) *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.SetCharacterID(v)
	})
}

// UpdateCharacterID sets the "character_id" field to the value that was provided on create.
func (u *CardUpsertOne) UpdateCharacterID() *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.UpdateCharacterID()
	})
}

// SetCardName sets the "card_name" field.
func (u *CardUpsertOne) SetCardName(v string) *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.SetCardName(v)
	})
}

// UpdateCardName sets the "card_name" field to the value that was provided on create.
func (u *CardUpsertOne) UpdateCardName() *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.UpdateCardName()
	})
}

// SetCharacterName sets the "character_name" field.
func (u *CardUpsertOne) SetCharacterName(v string) *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.SetCharacterName(v)
	})
}

// UpdateCharacterName sets the "character_name" field to the value that was provided on create.
func (u *CardUpsertOne) UpdateCharacterName() *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.UpdateCharacterName()
	})
}

// SetCreator sets the "creator" field.
func (u *CardUpsertOne) SetCreator(v string) *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.SetCreator(v)
	})
}

// UpdateCreator sets the "creator" field to the value that was provided on create.
func (u *CardUpsertOne) UpdateCreator() *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.UpdateCreator()
	})
}

// SetTagline sets the "tagline" field.
func (u *CardUpsertOne) SetTagline(v string) *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.SetTagline(v)
	})
}

// UpdateTagline sets the "tagline" field to the value that was provided on create.
func (u *CardUpsertOne) UpdateTagline() *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.UpdateTagline()
	})
}

// SetCreateTime sets the "create_time" field.
func (u *CardUpsertOne) SetCreateTime(v timestamp.Nano) *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.SetCreateTime(v)
	})
}

// AddCreateTime adds v to the "create_time" field.
func (u *CardUpsertOne) AddCreateTime(v timestamp.Nano) *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.AddCreateTime(v)
	})
}

// UpdateCreateTime sets the "create_time" field to the value that was provided on create.
func (u *CardUpsertOne) UpdateCreateTime() *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.UpdateCreateTime()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *CardUpsertOne) SetUpdateTime(v timestamp.Nano) *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.SetUpdateTime(v)
	})
}

// AddUpdateTime adds v to the "update_time" field.
func (u *CardUpsertOne) AddUpdateTime(v timestamp.Nano) *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.AddUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *CardUpsertOne) UpdateUpdateTime() *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetBookUpdateTime sets the "book_update_time" field.
func (u *CardUpsertOne) SetBookUpdateTime(v timestamp.Nano) *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.SetBookUpdateTime(v)
	})
}

// AddBookUpdateTime adds v to the "book_update_time" field.
func (u *CardUpsertOne) AddBookUpdateTime(v timestamp.Nano) *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.AddBookUpdateTime(v)
	})
}

// UpdateBookUpdateTime sets the "book_update_time" field to the value that was provided on create.
func (u *CardUpsertOne) UpdateBookUpdateTime() *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.UpdateBookUpdateTime()
	})
}

// SetImportTime sets the "import_time" field.
func (u *CardUpsertOne) SetImportTime(v timestamp.Nano) *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.SetImportTime(v)
	})
}

// AddImportTime adds v to the "import_time" field.
func (u *CardUpsertOne) AddImportTime(v timestamp.Nano) *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.AddImportTime(v)
	})
}

// UpdateImportTime sets the "import_time" field to the value that was provided on create.
func (u *CardUpsertOne) UpdateImportTime() *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.UpdateImportTime()
	})
}

// SetCheckTime sets the "check_time" field.
func (u *CardUpsertOne) SetCheckTime(v timestamp.Nano) *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.SetCheckTime(v)
	})
}

// AddCheckTime adds v to the "check_time" field.
func (u *CardUpsertOne) AddCheckTime(v timestamp.Nano) *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.AddCheckTime(v)
	})
}

// UpdateCheckTime sets the "check_time" field to the value that was provided on create.
func (u *CardUpsertOne) UpdateCheckTime() *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.UpdateCheckTime()
	})
}

// SetLastUpdateStatus sets the "last_update_status" field.
func (u *CardUpsertOne) SetLastUpdateStatus(v scheme.UpdateStatus) *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.SetLastUpdateStatus(v)
	})
}

// UpdateLastUpdateStatus sets the "last_update_status" field to the value that was provided on create.
func (u *CardUpsertOne) UpdateLastUpdateStatus() *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.UpdateLastUpdateStatus()
	})
}

// SetExportTime sets the "export_time" field.
func (u *CardUpsertOne) SetExportTime(v timestamp.Nano) *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.SetExportTime(v)
	})
}

// AddExportTime adds v to the "export_time" field.
func (u *CardUpsertOne) AddExportTime(v timestamp.Nano) *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.AddExportTime(v)
	})
}

// UpdateExportTime sets the "export_time" field to the value that was provided on create.
func (u *CardUpsertOne) UpdateExportTime() *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.UpdateExportTime()
	})
}

// SetLastExportedVersion sets the "last_exported_version" field.
func (u *CardUpsertOne) SetLastExportedVersion(v timestamp.Nano) *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.SetLastExportedVersion(v)
	})
}

// AddLastExportedVersion adds v to the "last_exported_version" field.
func (u *CardUpsertOne) AddLastExportedVersion(v timestamp.Nano) *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.AddLastExportedVersion(v)
	})
}

// UpdateLastExportedVersion sets the "last_exported_version" field to the value that was provided on create.
func (u *CardUpsertOne) UpdateLastExportedVersion() *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.UpdateLastExportedVersion()
	})
}

// SetFavorite sets the "favorite" field.
func (u *CardUpsertOne) SetFavorite(v bool) *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.SetFavorite(v)
	})
}

// UpdateFavorite sets the "favorite" field to the value that was provided on create.
func (u *CardUpsertOne) UpdateFavorite() *CardUpsertOne {
	return u.Update(func(s *CardUpsert) {
		s.UpdateFavorite()
	})
}

// Exec executes the query.
func (u *CardUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CardCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CardUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CardUpsertOne) ID(ctx context.Context) (id scheme.CardID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ResourceID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: CardUpsertOne.ResourceID is not supported by MySQL driver. Use CardUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CardUpsertOne) IDX(ctx context.Context) scheme.CardID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CardCreateBulk is the builder for creating many Card entities in bulk.
type CardCreateBulk struct {
	config
	err      error
	builders []*CardCreate
	conflict []sql.ConflictOption
}

// Save creates the Card entities in the database.
func (_c *CardCreateBulk) Save(ctx context.Context) ([]*Card, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Card, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CardMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CardCreateBulk) SaveX(ctx context.Context) []*Card {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CardCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CardCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Card.CreateBulk(builders...).
//		OnConflict(
//			// UpdateInfoSyncData the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		UpdateInfoSyncData(func(u *ent.CardUpsert) {
//			SetBatchOrder(v+v).
//		}).
//		Exec(ctx)
func (_c *CardCreateBulk) OnConflict(opts ...sql.ConflictOption) *CardUpsertBulk {
	_c.conflict = opts
	return &CardUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Card.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CardCreateBulk) OnConflictColumns(columns ...string) *CardUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CardUpsertBulk{
		create: _c,
	}
}

// CardUpsertBulk is the builder for "upsert"-ing
// a bulk of Card nodes.
type CardUpsertBulk struct {
	create *CardCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Card.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(card.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CardUpsertBulk) UpdateNewValues() *CardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(card.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Card.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CardUpsertBulk) Ignore() *CardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CardUpsertBulk) DoNothing() *CardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CardCreateBulk.OnConflict
// documentation for more info.
func (u *CardUpsertBulk) Update(set func(*CardUpsert)) *CardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CardUpsert{UpdateSet: update})
	}))
	return u
}

// SetBatchOrder sets the "batch_order" field.
func (u *CardUpsertBulk) SetBatchOrder(v int) *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.SetBatchOrder(v)
	})
}

// AddBatchOrder adds v to the "batch_order" field.
func (u *CardUpsertBulk) AddBatchOrder(v int) *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.AddBatchOrder(v)
	})
}

// UpdateBatchOrder sets the "batch_order" field to the value that was provided on create.
func (u *CardUpsertBulk) UpdateBatchOrder() *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.UpdateBatchOrder()
	})
}

// SetSource sets the "source" field.
func (u *CardUpsertBulk) SetSource(v source.ID) *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *CardUpsertBulk) UpdateSource() *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.UpdateSource()
	})
}

// SetCardURL sets the "card_url" field.
func (u *CardUpsertBulk) SetCardURL(v string) *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.SetCardURL(v)
	})
}

// UpdateCardURL sets the "card_url" field to the value that was provided on create.
func (u *CardUpsertBulk) UpdateCardURL() *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.UpdateCardURL()
	})
}

// SetDirectURL sets the "direct_url" field.
func (u *CardUpsertBulk) SetDirectURL(v string) *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.SetDirectURL(v)
	})
}

// UpdateDirectURL sets the "direct_url" field to the value that was provided on create.
func (u *CardUpsertBulk) UpdateDirectURL() *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.UpdateDirectURL()
	})
}

// SetPlatformID sets the "platform_id" field.
func (u *CardUpsertBulk) SetPlatformID(v string) *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.SetPlatformID(v)
	})
}

// UpdatePlatformID sets the "platform_id" field to the value that was provided on create.
func (u *CardUpsertBulk) UpdatePlatformID() *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.UpdatePlatformID()
	})
}

// SetCharacterID sets the "character_id" field.
func (u *CardUpsertBulk) SetCharacterID(v string) *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.SetCharacterID(v)
	})
}

// UpdateCharacterID sets the "character_id" field to the value that was provided on create.
func (u *CardUpsertBulk) UpdateCharacterID() *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.UpdateCharacterID()
	})
}

// SetCardName sets the "card_name" field.
func (u *CardUpsertBulk) SetCardName(v string) *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.SetCardName(v)
	})
}

// UpdateCardName sets the "card_name" field to the value that was provided on create.
func (u *CardUpsertBulk) UpdateCardName() *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.UpdateCardName()
	})
}

// SetCharacterName sets the "character_name" field.
func (u *CardUpsertBulk) SetCharacterName(v string) *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.SetCharacterName(v)
	})
}

// UpdateCharacterName sets the "character_name" field to the value that was provided on create.
func (u *CardUpsertBulk) UpdateCharacterName() *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.UpdateCharacterName()
	})
}

// SetCreator sets the "creator" field.
func (u *CardUpsertBulk) SetCreator(v string) *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.SetCreator(v)
	})
}

// UpdateCreator sets the "creator" field to the value that was provided on create.
func (u *CardUpsertBulk) UpdateCreator() *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.UpdateCreator()
	})
}

// SetTagline sets the "tagline" field.
func (u *CardUpsertBulk) SetTagline(v string) *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.SetTagline(v)
	})
}

// UpdateTagline sets the "tagline" field to the value that was provided on create.
func (u *CardUpsertBulk) UpdateTagline() *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.UpdateTagline()
	})
}

// SetCreateTime sets the "create_time" field.
func (u *CardUpsertBulk) SetCreateTime(v timestamp.Nano) *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.SetCreateTime(v)
	})
}

// AddCreateTime adds v to the "create_time" field.
func (u *CardUpsertBulk) AddCreateTime(v timestamp.Nano) *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.AddCreateTime(v)
	})
}

// UpdateCreateTime sets the "create_time" field to the value that was provided on create.
func (u *CardUpsertBulk) UpdateCreateTime() *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.UpdateCreateTime()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *CardUpsertBulk) SetUpdateTime(v timestamp.Nano) *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.SetUpdateTime(v)
	})
}

// AddUpdateTime adds v to the "update_time" field.
func (u *CardUpsertBulk) AddUpdateTime(v timestamp.Nano) *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.AddUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *CardUpsertBulk) UpdateUpdateTime() *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetBookUpdateTime sets the "book_update_time" field.
func (u *CardUpsertBulk) SetBookUpdateTime(v timestamp.Nano) *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.SetBookUpdateTime(v)
	})
}

// AddBookUpdateTime adds v to the "book_update_time" field.
func (u *CardUpsertBulk) AddBookUpdateTime(v timestamp.Nano) *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.AddBookUpdateTime(v)
	})
}

// UpdateBookUpdateTime sets the "book_update_time" field to the value that was provided on create.
func (u *CardUpsertBulk) UpdateBookUpdateTime() *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.UpdateBookUpdateTime()
	})
}

// SetImportTime sets the "import_time" field.
func (u *CardUpsertBulk) SetImportTime(v timestamp.Nano) *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.SetImportTime(v)
	})
}

// AddImportTime adds v to the "import_time" field.
func (u *CardUpsertBulk) AddImportTime(v timestamp.Nano) *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.AddImportTime(v)
	})
}

// UpdateImportTime sets the "import_time" field to the value that was provided on create.
func (u *CardUpsertBulk) UpdateImportTime() *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.UpdateImportTime()
	})
}

// SetCheckTime sets the "check_time" field.
func (u *CardUpsertBulk) SetCheckTime(v timestamp.Nano) *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.SetCheckTime(v)
	})
}

// AddCheckTime adds v to the "check_time" field.
func (u *CardUpsertBulk) AddCheckTime(v timestamp.Nano) *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.AddCheckTime(v)
	})
}

// UpdateCheckTime sets the "check_time" field to the value that was provided on create.
func (u *CardUpsertBulk) UpdateCheckTime() *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.UpdateCheckTime()
	})
}

// SetLastUpdateStatus sets the "last_update_status" field.
func (u *CardUpsertBulk) SetLastUpdateStatus(v scheme.UpdateStatus) *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.SetLastUpdateStatus(v)
	})
}

// UpdateLastUpdateStatus sets the "last_update_status" field to the value that was provided on create.
func (u *CardUpsertBulk) UpdateLastUpdateStatus() *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.UpdateLastUpdateStatus()
	})
}

// SetExportTime sets the "export_time" field.
func (u *CardUpsertBulk) SetExportTime(v timestamp.Nano) *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.SetExportTime(v)
	})
}

// AddExportTime adds v to the "export_time" field.
func (u *CardUpsertBulk) AddExportTime(v timestamp.Nano) *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.AddExportTime(v)
	})
}

// UpdateExportTime sets the "export_time" field to the value that was provided on create.
func (u *CardUpsertBulk) UpdateExportTime() *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.UpdateExportTime()
	})
}

// SetLastExportedVersion sets the "last_exported_version" field.
func (u *CardUpsertBulk) SetLastExportedVersion(v timestamp.Nano) *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.SetLastExportedVersion(v)
	})
}

// AddLastExportedVersion adds v to the "last_exported_version" field.
func (u *CardUpsertBulk) AddLastExportedVersion(v timestamp.Nano) *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.AddLastExportedVersion(v)
	})
}

// UpdateLastExportedVersion sets the "last_exported_version" field to the value that was provided on create.
func (u *CardUpsertBulk) UpdateLastExportedVersion() *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.UpdateLastExportedVersion()
	})
}

// SetFavorite sets the "favorite" field.
func (u *CardUpsertBulk) SetFavorite(v bool) *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.SetFavorite(v)
	})
}

// UpdateFavorite sets the "favorite" field to the value that was provided on create.
func (u *CardUpsertBulk) UpdateFavorite() *CardUpsertBulk {
	return u.Update(func(s *CardUpsert) {
		s.UpdateFavorite()
	})
}

// Exec executes the query.
func (u *CardUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CardCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CardCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CardUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
