// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/r3dpixel/card-client/internal/ent/card"
	"github.com/r3dpixel/card-client/services/scheme"
	"github.com/r3dpixel/card-fetcher/source"
	"github.com/r3dpixel/toolkit/timestamp"
)

// Card is the model entity for the Card schema.
type Card struct {
	config `json:"-"`
	// ID of the ent.
	ID scheme.CardID `json:"id,omitempty"`
	// BatchOrder holds the value of the "batch_order" field.
	BatchOrder int `json:"batch_order,omitempty"`
	// Source holds the value of the "source" field.
	Source source.ID `json:"source,omitempty"`
	// CardURL holds the value of the "card_url" field.
	CardURL string `json:"card_url,omitempty"`
	// DirectURL holds the value of the "direct_url" field.
	DirectURL string `json:"direct_url,omitempty"`
	// PlatformID holds the value of the "platform_id" field.
	PlatformID string `json:"platform_id,omitempty"`
	// CharacterID holds the value of the "character_id" field.
	CharacterID string `json:"character_id,omitempty"`
	// CardName holds the value of the "card_name" field.
	CardName string `json:"card_name,omitempty"`
	// CharacterName holds the value of the "character_name" field.
	CharacterName string `json:"character_name,omitempty"`
	// Creator holds the value of the "creator" field.
	Creator string `json:"creator,omitempty"`
	// Tagline holds the value of the "tagline" field.
	Tagline string `json:"tagline,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime timestamp.Nano `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime timestamp.Nano `json:"update_time,omitempty"`
	// BookUpdateTime holds the value of the "book_update_time" field.
	BookUpdateTime timestamp.Nano `json:"book_update_time,omitempty"`
	// ImportTime holds the value of the "import_time" field.
	ImportTime timestamp.Nano `json:"import_time,omitempty"`
	// CheckTime holds the value of the "check_time" field.
	CheckTime timestamp.Nano `json:"check_time,omitempty"`
	// LastUpdateStatus holds the value of the "last_update_status" field.
	LastUpdateStatus scheme.UpdateStatus `json:"last_update_status,omitempty"`
	// ExportTime holds the value of the "export_time" field.
	ExportTime timestamp.Nano `json:"export_time,omitempty"`
	// LastExportedVersion holds the value of the "last_exported_version" field.
	LastExportedVersion timestamp.Nano `json:"last_exported_version,omitempty"`
	// Favorite holds the value of the "favorite" field.
	Favorite bool `json:"favorite,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CardQuery when eager-loading is set.
	Edges        CardEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CardEdges holds the relations/edges for other nodes in the graph.
type CardEdges struct {
	// Tags holds the value of the tags edge.
	Tags []*Tag `json:"tags,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TagsOrErr returns the Tags value or an error if the edge
// was not loaded in eager-loading.
func (e CardEdges) TagsOrErr() ([]*Tag, error) {
	if e.loadedTypes[0] {
		return e.Tags, nil
	}
	return nil, &NotLoadedError{edge: "tags"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Card) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case card.FieldID:
			values[i] = new(scheme.CardID)
		case card.FieldFavorite:
			values[i] = new(sql.NullBool)
		case card.FieldBatchOrder, card.FieldCreateTime, card.FieldUpdateTime, card.FieldBookUpdateTime, card.FieldImportTime, card.FieldCheckTime, card.FieldExportTime, card.FieldLastExportedVersion:
			values[i] = new(sql.NullInt64)
		case card.FieldSource, card.FieldCardURL, card.FieldDirectURL, card.FieldPlatformID, card.FieldCharacterID, card.FieldCardName, card.FieldCharacterName, card.FieldCreator, card.FieldTagline, card.FieldLastUpdateStatus:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Card fields.
func (_m *Card) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case card.FieldID:
			if value, ok := values[i].(*scheme.CardID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case card.FieldBatchOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field batch_order", values[i])
			} else if value.Valid {
				_m.BatchOrder = int(value.Int64)
			}
		case card.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = source.ID(value.String)
			}
		case card.FieldCardURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field card_url", values[i])
			} else if value.Valid {
				_m.CardURL = value.String
			}
		case card.FieldDirectURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field direct_url", values[i])
			} else if value.Valid {
				_m.DirectURL = value.String
			}
		case card.FieldPlatformID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform_id", values[i])
			} else if value.Valid {
				_m.PlatformID = value.String
			}
		case card.FieldCharacterID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field character_id", values[i])
			} else if value.Valid {
				_m.CharacterID = value.String
			}
		case card.FieldCardName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field card_name", values[i])
			} else if value.Valid {
				_m.CardName = value.String
			}
		case card.FieldCharacterName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field character_name", values[i])
			} else if value.Valid {
				_m.CharacterName = value.String
			}
		case card.FieldCreator:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field creator", values[i])
			} else if value.Valid {
				_m.Creator = value.String
			}
		case card.FieldTagline:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tagline", values[i])
			} else if value.Valid {
				_m.Tagline = value.String
			}
		case card.FieldCreateTime:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = timestamp.Nano(value.Int64)
			}
		case card.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = timestamp.Nano(value.Int64)
			}
		case card.FieldBookUpdateTime:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field book_update_time", values[i])
			} else if value.Valid {
				_m.BookUpdateTime = timestamp.Nano(value.Int64)
			}
		case card.FieldImportTime:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field import_time", values[i])
			} else if value.Valid {
				_m.ImportTime = timestamp.Nano(value.Int64)
			}
		case card.FieldCheckTime:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field check_time", values[i])
			} else if value.Valid {
				_m.CheckTime = timestamp.Nano(value.Int64)
			}
		case card.FieldLastUpdateStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_update_status", values[i])
			} else if value.Valid {
				_m.LastUpdateStatus = scheme.UpdateStatus(value.String)
			}
		case card.FieldExportTime:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field export_time", values[i])
			} else if value.Valid {
				_m.ExportTime = timestamp.Nano(value.Int64)
			}
		case card.FieldLastExportedVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_exported_version", values[i])
			} else if value.Valid {
				_m.LastExportedVersion = timestamp.Nano(value.Int64)
			}
		case card.FieldFavorite:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field favorite", values[i])
			} else if value.Valid {
				_m.Favorite = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Card.
// This includes values selected through modifiers, order, etc.
func (_m *Card) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTags queries the "tags" edge of the Card entity.
func (_m *Card) QueryTags() *TagQuery {
	return NewCardClient(_m.config).QueryTags(_m)
}

// Update returns a builder for updating this Card.
// Note that you need to call Card.Unwrap() before calling this method if this Card
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Card) Update() *CardUpdateOne {
	return NewCardClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Card entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Card) Unwrap() *Card {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Card is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Card) String() string {
	var builder strings.Builder
	builder.WriteString("Card(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("batch_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.BatchOrder))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(fmt.Sprintf("%v", _m.Source))
	builder.WriteString(", ")
	builder.WriteString("card_url=")
	builder.WriteString(_m.CardURL)
	builder.WriteString(", ")
	builder.WriteString("direct_url=")
	builder.WriteString(_m.DirectURL)
	builder.WriteString(", ")
	builder.WriteString("platform_id=")
	builder.WriteString(_m.PlatformID)
	builder.WriteString(", ")
	builder.WriteString("character_id=")
	builder.WriteString(_m.CharacterID)
	builder.WriteString(", ")
	builder.WriteString("card_name=")
	builder.WriteString(_m.CardName)
	builder.WriteString(", ")
	builder.WriteString("character_name=")
	builder.WriteString(_m.CharacterName)
	builder.WriteString(", ")
	builder.WriteString("creator=")
	builder.WriteString(_m.Creator)
	builder.WriteString(", ")
	builder.WriteString("tagline=")
	builder.WriteString(_m.Tagline)
	builder.WriteString(", ")
	builder.WriteString("create_time=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreateTime))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdateTime))
	builder.WriteString(", ")
	builder.WriteString("book_update_time=")
	builder.WriteString(fmt.Sprintf("%v", _m.BookUpdateTime))
	builder.WriteString(", ")
	builder.WriteString("import_time=")
	builder.WriteString(fmt.Sprintf("%v", _m.ImportTime))
	builder.WriteString(", ")
	builder.WriteString("check_time=")
	builder.WriteString(fmt.Sprintf("%v", _m.CheckTime))
	builder.WriteString(", ")
	builder.WriteString("last_update_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.LastUpdateStatus))
	builder.WriteString(", ")
	builder.WriteString("export_time=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExportTime))
	builder.WriteString(", ")
	builder.WriteString("last_exported_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.LastExportedVersion))
	builder.WriteString(", ")
	builder.WriteString("favorite=")
	builder.WriteString(fmt.Sprintf("%v", _m.Favorite))
	builder.WriteByte(')')
	return builder.String()
}

// Cards is a parsable slice of Card.
type Cards []*Card
