package opcache

import (
	"context"
	"fmt"
	"sync"
	"testing"
	"time"

	"github.com/digital-foxy/card-client/library"
	"github.com/digital-foxy/card-client/operation"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const testVault = library.VaultName("vault")

func newTestRegistry() (*Registry, *int) {
	callCount := 0
	mockGenerator := func() operation.ID {
		callCount++
		return operation.ID(fmt.Sprintf("test-id-%d", callCount))
	}
	return NewRegistry(mockGenerator), &callCount
}

func TestDefaultIdGenerator(t *testing.T) {
	generator := DefaultIdGenerator()
	require.NotNil(t, generator)

	id1 := generator()
	id2 := generator()

	assert.NotEmpty(t, id1)
	assert.NotEmpty(t, id2)
	assert.NotEqual(t, id1, id2, "Default ID generator should produce unique IDs")
}

func TestNewRegistry(t *testing.T) {
	reg, _ := newTestRegistry()
	require.NotNil(t, reg, "NewRegistry should not return nil")
	assert.NotNil(t, reg.operations, "Operations map should be initialized")
	assert.Equal(t, 0, reg.ActiveOperations(), "A new registry should have no active operations")
	assert.False(t, reg.HasChanges(), "A new registry should not be dirty")
}

func TestRegistry_RegistrationLifecycle(t *testing.T) {
	testCases := []struct {
		name   string
		action operation.Action
	}{
		{"Import", operation.Import},
		{"Update", operation.Update},
		{"Export", operation.Export},
		{"Delete", operation.Delete},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			reg, idCounter := newTestRegistry()
			assert.False(t, reg.HasChanges(), "Registry should not be dirty initially")

			handle := reg.NewOperation(testVault, tc.action)

			assert.True(t, reg.HasChanges(), "Registry should be dirty after registration")
			assert.Equal(t, operation.ID("test-id-1"), handle.OperationID, "ID should be generated by the mock generator")
			assert.Equal(t, 1, *idCounter, "ID generator should have been called once")
			assert.Equal(t, 1, reg.ActiveOperations(), "Active operations count should be 1 after registration")
			assert.NotZero(t, handle.TimeStarted, "Handle should have a non-zero start time")

			reg.mapMutex.RLock()
			entry, ok := reg.operations.Get(handle.OperationID)
			reg.mapMutex.RUnlock()

			require.True(t, ok, "Operation should exist in the internal map")
			assert.Equal(t, tc.action, entry.details.Action, "Operation should have the correct action type")
			assert.Equal(t, operation.Ongoing, entry.details.Status, "New operation should have 'Ongoing' status")
			assert.NotZero(t, entry.details.TimeStarted, "TimeStarted should be set on registration")
			assert.False(t, entry.details.Disposable, "New operation should not be disposable")
			require.NotNil(t, entry.cancel, "A cancel function should be associated with the entry")
		})
	}
}

func TestRegistry_TerminateOperations(t *testing.T) {
	testCases := []struct {
		name         string
		setupFunc    func(*Registry) (operation.ID, operation.Handle)
		cancelFirst  bool
		expectError  bool
		validateFunc func(*testing.T, *Registry, operation.ID, operation.Handle, error)
	}{
		{
			name: "Complete_Success",
			setupFunc: func(reg *Registry) (operation.ID, operation.Handle) {
				handle := reg.NewOperation(testVault, operation.Import)
				reg.ListReports() // Clear dirty flag from registration
				assert.False(t, reg.HasChanges(), "Flag should be clean after ListReports")
				return handle.OperationID, handle
			},
			cancelFirst: false,
			expectError: false,
			validateFunc: func(t *testing.T, reg *Registry, opID operation.ID, handle operation.Handle, err error) {
				require.NoError(t, err)
				assert.True(t, reg.HasChanges(), "Registry should be dirty after completing an operation")
				assert.Equal(t, 0, reg.ActiveOperations(), "Active operations should be 0 after completion")

				entry, _ := reg.operations.Get(opID)
				entry.mu.Lock()
				defer entry.mu.Unlock()
				assert.Equal(t, operation.Completed, entry.details.Status, "Status should be 'Completed'")
			},
		},
		{
			name: "Cancel_Success",
			setupFunc: func(reg *Registry) (operation.ID, operation.Handle) {
				handle := reg.NewOperation(testVault, operation.Import)
				reg.ListReports() // Clear dirty flag from registration
				assert.False(t, reg.HasChanges(), "Flag should be clean after ListReports")
				return handle.OperationID, handle
			},
			cancelFirst: true,
			expectError: false,
			validateFunc: func(t *testing.T, reg *Registry, opID operation.ID, handle operation.Handle, err error) {
				require.NoError(t, err)
				assert.True(t, reg.HasChanges(), "Registry should be dirty after cancelling an operation")
				assert.Equal(t, 0, reg.ActiveOperations(), "Active operations should be 0 after cancellation")

				entry, _ := reg.operations.Get(opID)
				entry.mu.Lock()
				assert.Equal(t, operation.Cancelled, entry.details.Status, "Status should be 'Cancelled'")
				entry.mu.Unlock()

				select {
				case <-handle.Context.Done():
					assert.ErrorIs(t, handle.Context.Err(), context.Canceled, "Context error should be 'context.Canceled'")
				case <-time.After(100 * time.Millisecond):
					t.Fatal("Context should have been cancelled")
				}
			},
		},
		{
			name: "Error_On_NonExistent",
			setupFunc: func(reg *Registry) (operation.ID, operation.Handle) {
				return "non-existent-id", operation.Handle{}
			},
			cancelFirst: false,
			expectError: true,
			validateFunc: func(t *testing.T, reg *Registry, opID operation.ID, handle operation.Handle, err error) {
				assert.ErrorContains(t, err, `"non-existent-id" not found`)
				assert.False(t, reg.HasChanges(), "Flag should not be set on error")

				// Also test Cancel on non-existent
				err2 := reg.Cancel(opID)
				assert.ErrorContains(t, err2, `"non-existent-id" not found`)
				assert.False(t, reg.HasChanges(), "Flag should not be set on error")
			},
		},
		{
			name: "Error_On_AlreadyTerminated",
			setupFunc: func(reg *Registry) (operation.ID, operation.Handle) {
				handle := reg.NewOperation(testVault, operation.Import)
				err := reg.MarkTerminated(handle.OperationID)
				require.NoError(t, err, "First completion should succeed")
				reg.ListReports() // Clear dirty flag
				assert.False(t, reg.HasChanges(), "Flag should be clean after ListReports")
				return handle.OperationID, handle
			},
			cancelFirst: false,
			expectError: true,
			validateFunc: func(t *testing.T, reg *Registry, opID operation.ID, handle operation.Handle, err error) {
				assert.ErrorContains(t, err, "has already been terminated")
				assert.False(t, reg.HasChanges(), "Flag should not be set on error")
			},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			reg, _ := newTestRegistry()
			opID, handle := tc.setupFunc(reg)

			if tc.cancelFirst {
				err := reg.Cancel(opID)
				require.NoError(t, err)
			}

			err := reg.MarkTerminated(opID)

			tc.validateFunc(t, reg, opID, handle, err)
		})
	}
}

func TestRegistry_ListReports(t *testing.T) {
	reg, _ := newTestRegistry()

	hImport := reg.NewOperation(testVault, operation.Import)
	hUpdate := reg.NewOperation(testVault, operation.Update)
	hExport := reg.NewOperation(testVault, operation.Export)
	hDelete := reg.NewOperation(testVault, operation.Delete)

	err := reg.MutateReport(hUpdate.OperationID, func(report *operation.Report) {
		report.Total = 200
		report.Progress = 150
		report.NoSuccesses = 120
		report.NoFailures = 5
		report.NoUnchanges = 25
	})
	require.NoError(t, err)

	_ = reg.MarkTerminated(hUpdate.OperationID)
	_ = reg.Cancel(hDelete.OperationID)
	_ = reg.MarkTerminated(hDelete.OperationID)

	assert.True(t, reg.HasChanges(), "Registry should be dirty before listing reports")

	reports := reg.ListReports()
	require.Len(t, reports, 4, "Should get reports for all 4 registered operations")

	assert.False(t, reg.HasChanges(), "Registry should NOT be dirty immediately after listing reports")

	reportMap := make(map[operation.ID]operation.UnifiedReport)
	for _, r := range reports {
		reportMap[r.Details.ID] = r
	}

	impReport, ok := reportMap[hImport.OperationID]
	require.True(t, ok, "Import report should be found")
	assert.Equal(t, operation.Import, impReport.Details.Action)
	assert.Equal(t, operation.Ongoing, impReport.Details.Status)
	assert.Zero(t, impReport.Details.TimeEnded)
	assert.Equal(t, impReport.Details.VaultName, testVault)
	assert.False(t, impReport.Details.Disposable, "Ongoing report should not be disposable")
	assert.NotZero(t, impReport.Details.TimeStarted, "TimeStarted should be populated")

	updReport, ok := reportMap[hUpdate.OperationID]
	require.True(t, ok, "Update report should be found")
	assert.Equal(t, operation.Update, updReport.Details.Action)
	assert.Equal(t, operation.Completed, updReport.Details.Status)
	assert.NotZero(t, updReport.Details.TimeEnded)
	assert.Equal(t, updReport.Details.VaultName, testVault)
	assert.True(t, updReport.Details.Disposable, "Completed report should be marked as disposable")

	assert.Equal(t, 200, updReport.Report.Total)
	assert.Equal(t, 150, updReport.Report.Progress)
	assert.Equal(t, 120, updReport.Report.NoSuccesses)
	assert.Equal(t, 5, updReport.Report.NoFailures)
	assert.Equal(t, 25, updReport.Report.NoUnchanges)

	expReport, ok := reportMap[hExport.OperationID]
	require.True(t, ok, "Export report should be found")
	assert.Equal(t, operation.Export, expReport.Details.Action)
	assert.Equal(t, operation.Ongoing, expReport.Details.Status)
	assert.Zero(t, expReport.Details.TimeEnded)
	assert.Equal(t, expReport.Details.VaultName, testVault)
	assert.False(t, expReport.Details.Disposable, "Ongoing report should not be disposable")

	delReport, ok := reportMap[hDelete.OperationID]
	require.True(t, ok, "Delete report should be found")
	assert.Equal(t, operation.Delete, delReport.Details.Action)
	assert.Equal(t, operation.Cancelled, delReport.Details.Status)
	assert.NotZero(t, delReport.Details.TimeEnded)
	assert.Equal(t, delReport.Details.VaultName, testVault)
	assert.True(t, delReport.Details.Disposable, "Cancelled report should be marked as disposable")
}

func TestRegistry_DisposableCleanup(t *testing.T) {
	reg, _ := newTestRegistry()

	hOngoing := reg.NewOperation(testVault, operation.Export)
	hCompleted := reg.NewOperation(testVault, operation.Import)
	hCancelled := reg.NewOperation(testVault, operation.Update)

	err := reg.MarkTerminated(hCompleted.OperationID)
	require.NoError(t, err)
	err = reg.Cancel(hCancelled.OperationID)
	require.NoError(t, err)
	err = reg.MarkTerminated(hCancelled.OperationID)
	require.NoError(t, err)

	t.Log("First call to ListReports: expecting to see all 3 operations, with 2 marked as disposable.")
	reports1 := reg.ListReports()
	require.Len(t, reports1, 3, "Should show all 3 operations on the first list")
	assert.Equal(t, 3, reg.operations.Len(), "Internal map should still contain 3 operations")

	entryCompleted, _ := reg.operations.Get(hCompleted.OperationID)
	assert.True(t, entryCompleted.details.Disposable, "Completed op should be marked disposable internally")
	entryCancelled, _ := reg.operations.Get(hCancelled.OperationID)
	assert.True(t, entryCancelled.details.Disposable, "Cancelled op should be marked disposable internally")
	entryOngoing, _ := reg.operations.Get(hOngoing.OperationID)
	assert.False(t, entryOngoing.details.Disposable, "Ongoing op should not be marked disposable")

	t.Log("Second call to ListReports: expecting to see only the ongoing operation.")
	reports2 := reg.ListReports()
	require.Len(t, reports2, 1, "Should only show the ongoing operation on the second list")
	assert.Equal(t, 1, reg.operations.Len(), "Internal map should now only contain 1 operation")
	assert.Equal(t, hOngoing.OperationID, reports2[0].Details.ID, "The remaining report should be the ongoing one")

	t.Log("Third call to ListReports: expecting no change.")
	reports3 := reg.ListReports()
	require.Len(t, reports3, 1, "Should still show the ongoing operation on the third list")
	assert.Equal(t, 1, reg.operations.Len(), "Internal map should still contain 1 operation")
}

func TestRegistry_MutateReport(t *testing.T) {
	t.Run("Mutate_Success", func(t *testing.T) {
		reg, _ := newTestRegistry()
		handle := reg.NewOperation(testVault, operation.Import)
		reg.ListReports() // Clear dirty flag from registration
		assert.False(t, reg.HasChanges(), "Flag should be clean after ListReports")

		err := reg.MutateReport(handle.OperationID, func(report *operation.Report) {
			report.Progress = 99
			report.NoValidURLs = 50
		})
		require.NoError(t, err)

		assert.True(t, reg.HasChanges(), "Registry should be dirty after a mutation")

		entry, _ := reg.operations.Get(handle.OperationID)
		entry.mu.Lock()
		assert.Equal(t, 99, entry.report.Progress)
		assert.Equal(t, 50, entry.report.NoValidURLs)
		entry.mu.Unlock()
	})

	t.Run("Mutate_ErrorOnNonExistent", func(t *testing.T) {
		reg, _ := newTestRegistry()

		err := reg.MutateReport("non-existent-id", func(report *operation.Report) {
			report.Progress = 99
		})
		assert.Error(t, err, "Mutate should fail for a non-existent operation")
		assert.False(t, reg.HasChanges(), "Flag should not be set on error")
	})
}

func TestRegistry_Concurrency(t *testing.T) {
	reg := NewRegistry(DefaultIdGenerator())
	var wg sync.WaitGroup
	numGoroutines := 100

	wg.Add(numGoroutines)
	for i := 0; i < numGoroutines; i++ {
		go func(i int) {
			defer wg.Done()

			handle := reg.NewOperation(testVault, operation.Import)

			for j := 0; j < 10; j++ {
				_ = reg.MutateReport(handle.OperationID, func(r *operation.Report) {
					r.Progress++
				})
			}

			if i%2 == 0 {
				_ = reg.MarkTerminated(handle.OperationID)
			} else {
				_ = reg.Cancel(handle.OperationID)
				_ = reg.MarkTerminated(handle.OperationID)
			}
		}(i)
	}

	var readerWg sync.WaitGroup
	readerWg.Add(1)
	stopReading := make(chan struct{})
	go func() {
		defer readerWg.Done()
		for {
			select {
			case <-stopReading:
				return
			default:
				_ = reg.ListReports()
				_ = reg.ActiveOperations()
				time.Sleep(1 * time.Millisecond)
			}
		}
	}()

	wg.Wait()
	close(stopReading)
	readerWg.Wait()

	assert.Equal(t, 0, reg.ActiveOperations(), "All operations should be terminated")

	_ = reg.ListReports()
	finalReports := reg.ListReports()
	assert.Empty(t, finalReports, "Registry should be empty after all operations are completed and listed twice")
	assert.True(t, reg.operations.Len() == 0, "Internal map should be empty after cleanup")
}
