// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/r3dpixel/card-client/store/record/entrecord/ent/creatorentity"
	"github.com/r3dpixel/card-client/store/record/entrecord/ent/predicate"
	"github.com/r3dpixel/card-client/store/record/entrecord/ent/recordentity"
	"github.com/r3dpixel/card-client/store/resource"
	"github.com/r3dpixel/card-fetcher/source"
)

// CreatorEntityUpdate is the builder for updating CreatorEntity entities.
type CreatorEntityUpdate struct {
	config
	hooks     []Hook
	mutation  *CreatorEntityMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the CreatorEntityUpdate builder.
func (_u *CreatorEntityUpdate) Where(ps ...predicate.CreatorEntity) *CreatorEntityUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetNickname sets the "nickname" field.
func (_u *CreatorEntityUpdate) SetNickname(v string) *CreatorEntityUpdate {
	_u.mutation.SetNickname(v)
	return _u
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (_u *CreatorEntityUpdate) SetNillableNickname(v *string) *CreatorEntityUpdate {
	if v != nil {
		_u.SetNickname(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *CreatorEntityUpdate) SetUsername(v string) *CreatorEntityUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *CreatorEntityUpdate) SetNillableUsername(v *string) *CreatorEntityUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetPlatformID sets the "platform_id" field.
func (_u *CreatorEntityUpdate) SetPlatformID(v string) *CreatorEntityUpdate {
	_u.mutation.SetPlatformID(v)
	return _u
}

// SetNillablePlatformID sets the "platform_id" field if the given value is not nil.
func (_u *CreatorEntityUpdate) SetNillablePlatformID(v *string) *CreatorEntityUpdate {
	if v != nil {
		_u.SetPlatformID(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *CreatorEntityUpdate) SetSource(v source.ID) *CreatorEntityUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *CreatorEntityUpdate) SetNillableSource(v *source.ID) *CreatorEntityUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// AddRecordIDs adds the "records" edge to the RecordEntity entity by IDs.
func (_u *CreatorEntityUpdate) AddRecordIDs(ids ...resource.RID) *CreatorEntityUpdate {
	_u.mutation.AddRecordIDs(ids...)
	return _u
}

// AddRecords adds the "records" edges to the RecordEntity entity.
func (_u *CreatorEntityUpdate) AddRecords(v ...*RecordEntity) *CreatorEntityUpdate {
	ids := make([]resource.RID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRecordIDs(ids...)
}

// Mutation returns the CreatorEntityMutation object of the builder.
func (_u *CreatorEntityUpdate) Mutation() *CreatorEntityMutation {
	return _u.mutation
}

// ClearRecords clears all "records" edges to the RecordEntity entity.
func (_u *CreatorEntityUpdate) ClearRecords() *CreatorEntityUpdate {
	_u.mutation.ClearRecords()
	return _u
}

// RemoveRecordIDs removes the "records" edge to RecordEntity entities by IDs.
func (_u *CreatorEntityUpdate) RemoveRecordIDs(ids ...resource.RID) *CreatorEntityUpdate {
	_u.mutation.RemoveRecordIDs(ids...)
	return _u
}

// RemoveRecords removes "records" edges to RecordEntity entities.
func (_u *CreatorEntityUpdate) RemoveRecords(v ...*RecordEntity) *CreatorEntityUpdate {
	ids := make([]resource.RID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRecordIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CreatorEntityUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CreatorEntityUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CreatorEntityUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CreatorEntityUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CreatorEntityUpdate) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := creatorentity.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "CreatorEntity.source": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CreatorEntityUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CreatorEntityUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CreatorEntityUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(creatorentity.Table, creatorentity.Columns, sqlgraph.NewFieldSpec(creatorentity.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Nickname(); ok {
		_spec.SetField(creatorentity.FieldNickname, field.TypeString, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(creatorentity.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlatformID(); ok {
		_spec.SetField(creatorentity.FieldPlatformID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(creatorentity.FieldSource, field.TypeEnum, value)
	}
	if _u.mutation.RecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   creatorentity.RecordsTable,
			Columns: []string{creatorentity.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recordentity.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRecordsIDs(); len(nodes) > 0 && !_u.mutation.RecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   creatorentity.RecordsTable,
			Columns: []string{creatorentity.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recordentity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   creatorentity.RecordsTable,
			Columns: []string{creatorentity.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recordentity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{creatorentity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CreatorEntityUpdateOne is the builder for updating a single CreatorEntity entity.
type CreatorEntityUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *CreatorEntityMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetNickname sets the "nickname" field.
func (_u *CreatorEntityUpdateOne) SetNickname(v string) *CreatorEntityUpdateOne {
	_u.mutation.SetNickname(v)
	return _u
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (_u *CreatorEntityUpdateOne) SetNillableNickname(v *string) *CreatorEntityUpdateOne {
	if v != nil {
		_u.SetNickname(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *CreatorEntityUpdateOne) SetUsername(v string) *CreatorEntityUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *CreatorEntityUpdateOne) SetNillableUsername(v *string) *CreatorEntityUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetPlatformID sets the "platform_id" field.
func (_u *CreatorEntityUpdateOne) SetPlatformID(v string) *CreatorEntityUpdateOne {
	_u.mutation.SetPlatformID(v)
	return _u
}

// SetNillablePlatformID sets the "platform_id" field if the given value is not nil.
func (_u *CreatorEntityUpdateOne) SetNillablePlatformID(v *string) *CreatorEntityUpdateOne {
	if v != nil {
		_u.SetPlatformID(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *CreatorEntityUpdateOne) SetSource(v source.ID) *CreatorEntityUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *CreatorEntityUpdateOne) SetNillableSource(v *source.ID) *CreatorEntityUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// AddRecordIDs adds the "records" edge to the RecordEntity entity by IDs.
func (_u *CreatorEntityUpdateOne) AddRecordIDs(ids ...resource.RID) *CreatorEntityUpdateOne {
	_u.mutation.AddRecordIDs(ids...)
	return _u
}

// AddRecords adds the "records" edges to the RecordEntity entity.
func (_u *CreatorEntityUpdateOne) AddRecords(v ...*RecordEntity) *CreatorEntityUpdateOne {
	ids := make([]resource.RID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRecordIDs(ids...)
}

// Mutation returns the CreatorEntityMutation object of the builder.
func (_u *CreatorEntityUpdateOne) Mutation() *CreatorEntityMutation {
	return _u.mutation
}

// ClearRecords clears all "records" edges to the RecordEntity entity.
func (_u *CreatorEntityUpdateOne) ClearRecords() *CreatorEntityUpdateOne {
	_u.mutation.ClearRecords()
	return _u
}

// RemoveRecordIDs removes the "records" edge to RecordEntity entities by IDs.
func (_u *CreatorEntityUpdateOne) RemoveRecordIDs(ids ...resource.RID) *CreatorEntityUpdateOne {
	_u.mutation.RemoveRecordIDs(ids...)
	return _u
}

// RemoveRecords removes "records" edges to RecordEntity entities.
func (_u *CreatorEntityUpdateOne) RemoveRecords(v ...*RecordEntity) *CreatorEntityUpdateOne {
	ids := make([]resource.RID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRecordIDs(ids...)
}

// Where appends a list predicates to the CreatorEntityUpdate builder.
func (_u *CreatorEntityUpdateOne) Where(ps ...predicate.CreatorEntity) *CreatorEntityUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CreatorEntityUpdateOne) Select(field string, fields ...string) *CreatorEntityUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CreatorEntity entity.
func (_u *CreatorEntityUpdateOne) Save(ctx context.Context) (*CreatorEntity, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CreatorEntityUpdateOne) SaveX(ctx context.Context) *CreatorEntity {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CreatorEntityUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CreatorEntityUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CreatorEntityUpdateOne) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := creatorentity.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "CreatorEntity.source": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CreatorEntityUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CreatorEntityUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CreatorEntityUpdateOne) sqlSave(ctx context.Context) (_node *CreatorEntity, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(creatorentity.Table, creatorentity.Columns, sqlgraph.NewFieldSpec(creatorentity.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CreatorEntity.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, creatorentity.FieldID)
		for _, f := range fields {
			if !creatorentity.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != creatorentity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Nickname(); ok {
		_spec.SetField(creatorentity.FieldNickname, field.TypeString, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(creatorentity.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlatformID(); ok {
		_spec.SetField(creatorentity.FieldPlatformID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(creatorentity.FieldSource, field.TypeEnum, value)
	}
	if _u.mutation.RecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   creatorentity.RecordsTable,
			Columns: []string{creatorentity.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recordentity.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRecordsIDs(); len(nodes) > 0 && !_u.mutation.RecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   creatorentity.RecordsTable,
			Columns: []string{creatorentity.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recordentity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   creatorentity.RecordsTable,
			Columns: []string{creatorentity.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recordentity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &CreatorEntity{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{creatorentity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
