// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/r3dpixel/card-client/store/record/entrecord/ent/predicate"
	"github.com/r3dpixel/card-client/store/record/entrecord/ent/recordentity"
	"github.com/r3dpixel/card-client/store/record/entrecord/ent/tagentity"
	"github.com/r3dpixel/card-client/store/resource"
)

// TagEntityUpdate is the builder for updating TagEntity entities.
type TagEntityUpdate struct {
	config
	hooks     []Hook
	mutation  *TagEntityMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the TagEntityUpdate builder.
func (_u *TagEntityUpdate) Where(ps ...predicate.TagEntity) *TagEntityUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *TagEntityUpdate) SetName(v string) *TagEntityUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TagEntityUpdate) SetNillableName(v *string) *TagEntityUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// AddRecordIDs adds the "records" edge to the RecordEntity entity by IDs.
func (_u *TagEntityUpdate) AddRecordIDs(ids ...resource.RID) *TagEntityUpdate {
	_u.mutation.AddRecordIDs(ids...)
	return _u
}

// AddRecords adds the "records" edges to the RecordEntity entity.
func (_u *TagEntityUpdate) AddRecords(v ...*RecordEntity) *TagEntityUpdate {
	ids := make([]resource.RID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRecordIDs(ids...)
}

// Mutation returns the TagEntityMutation object of the builder.
func (_u *TagEntityUpdate) Mutation() *TagEntityMutation {
	return _u.mutation
}

// ClearRecords clears all "records" edges to the RecordEntity entity.
func (_u *TagEntityUpdate) ClearRecords() *TagEntityUpdate {
	_u.mutation.ClearRecords()
	return _u
}

// RemoveRecordIDs removes the "records" edge to RecordEntity entities by IDs.
func (_u *TagEntityUpdate) RemoveRecordIDs(ids ...resource.RID) *TagEntityUpdate {
	_u.mutation.RemoveRecordIDs(ids...)
	return _u
}

// RemoveRecords removes "records" edges to RecordEntity entities.
func (_u *TagEntityUpdate) RemoveRecords(v ...*RecordEntity) *TagEntityUpdate {
	ids := make([]resource.RID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRecordIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TagEntityUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TagEntityUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TagEntityUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TagEntityUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TagEntityUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TagEntityUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TagEntityUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(tagentity.Table, tagentity.Columns, sqlgraph.NewFieldSpec(tagentity.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tagentity.FieldName, field.TypeString, value)
	}
	if _u.mutation.RecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tagentity.RecordsTable,
			Columns: tagentity.RecordsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recordentity.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRecordsIDs(); len(nodes) > 0 && !_u.mutation.RecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tagentity.RecordsTable,
			Columns: tagentity.RecordsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recordentity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tagentity.RecordsTable,
			Columns: tagentity.RecordsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recordentity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tagentity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TagEntityUpdateOne is the builder for updating a single TagEntity entity.
type TagEntityUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *TagEntityMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetName sets the "name" field.
func (_u *TagEntityUpdateOne) SetName(v string) *TagEntityUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TagEntityUpdateOne) SetNillableName(v *string) *TagEntityUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// AddRecordIDs adds the "records" edge to the RecordEntity entity by IDs.
func (_u *TagEntityUpdateOne) AddRecordIDs(ids ...resource.RID) *TagEntityUpdateOne {
	_u.mutation.AddRecordIDs(ids...)
	return _u
}

// AddRecords adds the "records" edges to the RecordEntity entity.
func (_u *TagEntityUpdateOne) AddRecords(v ...*RecordEntity) *TagEntityUpdateOne {
	ids := make([]resource.RID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRecordIDs(ids...)
}

// Mutation returns the TagEntityMutation object of the builder.
func (_u *TagEntityUpdateOne) Mutation() *TagEntityMutation {
	return _u.mutation
}

// ClearRecords clears all "records" edges to the RecordEntity entity.
func (_u *TagEntityUpdateOne) ClearRecords() *TagEntityUpdateOne {
	_u.mutation.ClearRecords()
	return _u
}

// RemoveRecordIDs removes the "records" edge to RecordEntity entities by IDs.
func (_u *TagEntityUpdateOne) RemoveRecordIDs(ids ...resource.RID) *TagEntityUpdateOne {
	_u.mutation.RemoveRecordIDs(ids...)
	return _u
}

// RemoveRecords removes "records" edges to RecordEntity entities.
func (_u *TagEntityUpdateOne) RemoveRecords(v ...*RecordEntity) *TagEntityUpdateOne {
	ids := make([]resource.RID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRecordIDs(ids...)
}

// Where appends a list predicates to the TagEntityUpdate builder.
func (_u *TagEntityUpdateOne) Where(ps ...predicate.TagEntity) *TagEntityUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TagEntityUpdateOne) Select(field string, fields ...string) *TagEntityUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TagEntity entity.
func (_u *TagEntityUpdateOne) Save(ctx context.Context) (*TagEntity, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TagEntityUpdateOne) SaveX(ctx context.Context) *TagEntity {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TagEntityUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TagEntityUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TagEntityUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TagEntityUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TagEntityUpdateOne) sqlSave(ctx context.Context) (_node *TagEntity, err error) {
	_spec := sqlgraph.NewUpdateSpec(tagentity.Table, tagentity.Columns, sqlgraph.NewFieldSpec(tagentity.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TagEntity.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tagentity.FieldID)
		for _, f := range fields {
			if !tagentity.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tagentity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tagentity.FieldName, field.TypeString, value)
	}
	if _u.mutation.RecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tagentity.RecordsTable,
			Columns: tagentity.RecordsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recordentity.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRecordsIDs(); len(nodes) > 0 && !_u.mutation.RecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tagentity.RecordsTable,
			Columns: tagentity.RecordsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recordentity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tagentity.RecordsTable,
			Columns: tagentity.RecordsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recordentity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &TagEntity{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tagentity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
