// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/r3dpixel/card-client/store/record/entrecord/ent/recordentity"
	"github.com/r3dpixel/card-client/store/record/entrecord/ent/tagentity"
	"github.com/r3dpixel/card-client/store/resource"
)

// TagEntityCreate is the builder for creating a TagEntity entity.
type TagEntityCreate struct {
	config
	mutation *TagEntityMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *TagEntityCreate) SetName(v string) *TagEntityCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetID sets the "id" field.
func (_c *TagEntityCreate) SetID(v resource.TID) *TagEntityCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddRecordIDs adds the "records" edge to the RecordEntity entity by IDs.
func (_c *TagEntityCreate) AddRecordIDs(ids ...resource.RID) *TagEntityCreate {
	_c.mutation.AddRecordIDs(ids...)
	return _c
}

// AddRecords adds the "records" edges to the RecordEntity entity.
func (_c *TagEntityCreate) AddRecords(v ...*RecordEntity) *TagEntityCreate {
	ids := make([]resource.RID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRecordIDs(ids...)
}

// Mutation returns the TagEntityMutation object of the builder.
func (_c *TagEntityCreate) Mutation() *TagEntityMutation {
	return _c.mutation
}

// Save creates the TagEntity in the database.
func (_c *TagEntityCreate) Save(ctx context.Context) (*TagEntity, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TagEntityCreate) SaveX(ctx context.Context) *TagEntity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TagEntityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TagEntityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TagEntityCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "TagEntity.name"`)}
	}
	return nil
}

func (_c *TagEntityCreate) sqlSave(ctx context.Context) (*TagEntity, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = resource.TID(id)
		} else {
			return nil, fmt.Errorf("unexpected TagEntity.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TagEntityCreate) createSpec() (*TagEntity, *sqlgraph.CreateSpec) {
	var (
		_node = &TagEntity{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tagentity.Table, sqlgraph.NewFieldSpec(tagentity.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(tagentity.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if nodes := _c.mutation.RecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tagentity.RecordsTable,
			Columns: tagentity.RecordsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recordentity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TagEntity.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TagEntityUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *TagEntityCreate) OnConflict(opts ...sql.ConflictOption) *TagEntityUpsertOne {
	_c.conflict = opts
	return &TagEntityUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TagEntity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TagEntityCreate) OnConflictColumns(columns ...string) *TagEntityUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TagEntityUpsertOne{
		create: _c,
	}
}

type (
	// TagEntityUpsertOne is the builder for "upsert"-ing
	//  one TagEntity node.
	TagEntityUpsertOne struct {
		create *TagEntityCreate
	}

	// TagEntityUpsert is the "OnConflict" setter.
	TagEntityUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *TagEntityUpsert) SetName(v string) *TagEntityUpsert {
	u.Set(tagentity.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TagEntityUpsert) UpdateName() *TagEntityUpsert {
	u.SetExcluded(tagentity.FieldName)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.TagEntity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(tagentity.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TagEntityUpsertOne) UpdateNewValues() *TagEntityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(tagentity.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TagEntity.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TagEntityUpsertOne) Ignore() *TagEntityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TagEntityUpsertOne) DoNothing() *TagEntityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TagEntityCreate.OnConflict
// documentation for more info.
func (u *TagEntityUpsertOne) Update(set func(*TagEntityUpsert)) *TagEntityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TagEntityUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *TagEntityUpsertOne) SetName(v string) *TagEntityUpsertOne {
	return u.Update(func(s *TagEntityUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TagEntityUpsertOne) UpdateName() *TagEntityUpsertOne {
	return u.Update(func(s *TagEntityUpsert) {
		s.UpdateName()
	})
}

// Exec executes the query.
func (u *TagEntityUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TagEntityCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TagEntityUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TagEntityUpsertOne) ID(ctx context.Context) (id resource.TID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: TagEntityUpsertOne.ID is not supported by MySQL driver. Use TagEntityUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TagEntityUpsertOne) IDX(ctx context.Context) resource.TID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TagEntityCreateBulk is the builder for creating many TagEntity entities in bulk.
type TagEntityCreateBulk struct {
	config
	err      error
	builders []*TagEntityCreate
	conflict []sql.ConflictOption
}

// Save creates the TagEntity entities in the database.
func (_c *TagEntityCreateBulk) Save(ctx context.Context) ([]*TagEntity, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TagEntity, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TagEntityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TagEntityCreateBulk) SaveX(ctx context.Context) []*TagEntity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TagEntityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TagEntityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TagEntity.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TagEntityUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *TagEntityCreateBulk) OnConflict(opts ...sql.ConflictOption) *TagEntityUpsertBulk {
	_c.conflict = opts
	return &TagEntityUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TagEntity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TagEntityCreateBulk) OnConflictColumns(columns ...string) *TagEntityUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TagEntityUpsertBulk{
		create: _c,
	}
}

// TagEntityUpsertBulk is the builder for "upsert"-ing
// a bulk of TagEntity nodes.
type TagEntityUpsertBulk struct {
	create *TagEntityCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TagEntity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(tagentity.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TagEntityUpsertBulk) UpdateNewValues() *TagEntityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(tagentity.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TagEntity.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TagEntityUpsertBulk) Ignore() *TagEntityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TagEntityUpsertBulk) DoNothing() *TagEntityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TagEntityCreateBulk.OnConflict
// documentation for more info.
func (u *TagEntityUpsertBulk) Update(set func(*TagEntityUpsert)) *TagEntityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TagEntityUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *TagEntityUpsertBulk) SetName(v string) *TagEntityUpsertBulk {
	return u.Update(func(s *TagEntityUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TagEntityUpsertBulk) UpdateName() *TagEntityUpsertBulk {
	return u.Update(func(s *TagEntityUpsert) {
		s.UpdateName()
	})
}

// Exec executes the query.
func (u *TagEntityUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TagEntityCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TagEntityCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TagEntityUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
