// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/r3dpixel/card-client/store/record/entrecord/ent/tagentity"
	"github.com/r3dpixel/card-client/store/resource"
)

// TagEntity is the model entity for the TagEntity schema.
type TagEntity struct {
	config `json:"-"`
	// ID of the ent.
	// Slug of the tag
	ID resource.TID `json:"id,omitempty"`
	// Tag name
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TagEntityQuery when eager-loading is set.
	Edges        TagEntityEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TagEntityEdges holds the relations/edges for other nodes in the graph.
type TagEntityEdges struct {
	// Records holds the value of the records edge.
	Records []*RecordEntity `json:"records,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RecordsOrErr returns the Records value or an error if the edge
// was not loaded in eager-loading.
func (e TagEntityEdges) RecordsOrErr() ([]*RecordEntity, error) {
	if e.loadedTypes[0] {
		return e.Records, nil
	}
	return nil, &NotLoadedError{edge: "records"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TagEntity) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tagentity.FieldID, tagentity.FieldName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TagEntity fields.
func (_m *TagEntity) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tagentity.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = resource.TID(value.String)
			}
		case tagentity.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TagEntity.
// This includes values selected through modifiers, order, etc.
func (_m *TagEntity) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRecords queries the "records" edge of the TagEntity entity.
func (_m *TagEntity) QueryRecords() *RecordEntityQuery {
	return NewTagEntityClient(_m.config).QueryRecords(_m)
}

// Update returns a builder for updating this TagEntity.
// Note that you need to call TagEntity.Unwrap() before calling this method if this TagEntity
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TagEntity) Update() *TagEntityUpdateOne {
	return NewTagEntityClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TagEntity entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TagEntity) Unwrap() *TagEntity {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TagEntity is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TagEntity) String() string {
	var builder strings.Builder
	builder.WriteString("TagEntity(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteByte(')')
	return builder.String()
}

// TagEntities is a parsable slice of TagEntity.
type TagEntities []*TagEntity
