// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CardsColumns holds the columns for the "cards" table.
	CardsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "batch_order", Type: field.TypeInt, Default: 0},
		{Name: "source", Type: field.TypeEnum, Enums: []string{"File", "CharacterTavern", "ChubAI", "NyaiMe", "PepHop", "Pygmalion", "WyvernChat", "RisuAI", "AICharacterCard"}},
		{Name: "card_url", Type: field.TypeString, Unique: true},
		{Name: "direct_url", Type: field.TypeString},
		{Name: "platform_id", Type: field.TypeString},
		{Name: "character_id", Type: field.TypeString},
		{Name: "card_name", Type: field.TypeString},
		{Name: "character_name", Type: field.TypeString},
		{Name: "creator", Type: field.TypeString},
		{Name: "tagline", Type: field.TypeString},
		{Name: "create_time", Type: field.TypeInt64},
		{Name: "update_time", Type: field.TypeInt64},
		{Name: "book_update_time", Type: field.TypeInt64, Default: 0},
		{Name: "import_time", Type: field.TypeInt64},
		{Name: "check_time", Type: field.TypeInt64},
		{Name: "last_update_status", Type: field.TypeEnum, Enums: []string{"UNCHANGED", "SUCCESS", "FAILED"}},
		{Name: "export_time", Type: field.TypeInt64, Default: 0},
		{Name: "last_exported_version", Type: field.TypeInt64, Default: 0},
		{Name: "favorite", Type: field.TypeBool, Default: false},
	}
	// CardsTable holds the schema information for the "cards" table.
	CardsTable = &schema.Table{
		Name:       "cards",
		Columns:    CardsColumns,
		PrimaryKey: []*schema.Column{CardsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "card_source_character_id",
				Unique:  true,
				Columns: []*schema.Column{CardsColumns[2], CardsColumns[6]},
			},
			{
				Name:    "card_source_platform_id",
				Unique:  true,
				Columns: []*schema.Column{CardsColumns[2], CardsColumns[5]},
			},
		},
	}
	// TagsColumns holds the columns for the "tags" table.
	TagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
	}
	// TagsTable holds the schema information for the "tags" table.
	TagsTable = &schema.Table{
		Name:       "tags",
		Columns:    TagsColumns,
		PrimaryKey: []*schema.Column{TagsColumns[0]},
	}
	// CardTagsColumns holds the columns for the "card_tags" table.
	CardTagsColumns = []*schema.Column{
		{Name: "card_id", Type: field.TypeString},
		{Name: "tag_id", Type: field.TypeString},
	}
	// CardTagsTable holds the schema information for the "card_tags" table.
	CardTagsTable = &schema.Table{
		Name:       "card_tags",
		Columns:    CardTagsColumns,
		PrimaryKey: []*schema.Column{CardTagsColumns[0], CardTagsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "card_tags_card_id",
				Columns:    []*schema.Column{CardTagsColumns[0]},
				RefColumns: []*schema.Column{CardsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "card_tags_tag_id",
				Columns:    []*schema.Column{CardTagsColumns[1]},
				RefColumns: []*schema.Column{TagsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CardsTable,
		TagsTable,
		CardTagsTable,
	}
)

func init() {
	CardsTable.Annotation = &entsql.Annotation{
		Table: "cards",
	}
	TagsTable.Annotation = &entsql.Annotation{
		Table: "tags",
	}
	CardTagsTable.ForeignKeys[0].RefTable = CardsTable
	CardTagsTable.ForeignKeys[1].RefTable = TagsTable
}
