// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/r3dpixel/card-client/store/record/erecord/ent/migrate"
	"github.com/r3dpixel/card-client/store/resource"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/r3dpixel/card-client/store/record/erecord/ent/creatorentity"
	"github.com/r3dpixel/card-client/store/record/erecord/ent/recordentity"
	"github.com/r3dpixel/card-client/store/record/erecord/ent/tagentity"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// CreatorEntity is the client for interacting with the CreatorEntity builders.
	CreatorEntity *CreatorEntityClient
	// RecordEntity is the client for interacting with the RecordEntity builders.
	RecordEntity *RecordEntityClient
	// TagEntity is the client for interacting with the TagEntity builders.
	TagEntity *TagEntityClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.CreatorEntity = NewCreatorEntityClient(c.config)
	c.RecordEntity = NewRecordEntityClient(c.config)
	c.TagEntity = NewTagEntityClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		CreatorEntity: NewCreatorEntityClient(cfg),
		RecordEntity:  NewRecordEntityClient(cfg),
		TagEntity:     NewTagEntityClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		CreatorEntity: NewCreatorEntityClient(cfg),
		RecordEntity:  NewRecordEntityClient(cfg),
		TagEntity:     NewTagEntityClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		CreatorEntity.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.CreatorEntity.Use(hooks...)
	c.RecordEntity.Use(hooks...)
	c.TagEntity.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.CreatorEntity.Intercept(interceptors...)
	c.RecordEntity.Intercept(interceptors...)
	c.TagEntity.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *CreatorEntityMutation:
		return c.CreatorEntity.mutate(ctx, m)
	case *RecordEntityMutation:
		return c.RecordEntity.mutate(ctx, m)
	case *TagEntityMutation:
		return c.TagEntity.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// CreatorEntityClient is a client for the CreatorEntity schema.
type CreatorEntityClient struct {
	config
}

// NewCreatorEntityClient returns a client for the CreatorEntity from the given config.
func NewCreatorEntityClient(c config) *CreatorEntityClient {
	return &CreatorEntityClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `creatorentity.Hooks(f(g(h())))`.
func (c *CreatorEntityClient) Use(hooks ...Hook) {
	c.hooks.CreatorEntity = append(c.hooks.CreatorEntity, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `creatorentity.Intercept(f(g(h())))`.
func (c *CreatorEntityClient) Intercept(interceptors ...Interceptor) {
	c.inters.CreatorEntity = append(c.inters.CreatorEntity, interceptors...)
}

// Create returns a builder for creating a CreatorEntity entity.
func (c *CreatorEntityClient) Create() *CreatorEntityCreate {
	mutation := newCreatorEntityMutation(c.config, OpCreate)
	return &CreatorEntityCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CreatorEntity entities.
func (c *CreatorEntityClient) CreateBulk(builders ...*CreatorEntityCreate) *CreatorEntityCreateBulk {
	return &CreatorEntityCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CreatorEntityClient) MapCreateBulk(slice any, setFunc func(*CreatorEntityCreate, int)) *CreatorEntityCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CreatorEntityCreateBulk{err: fmt.Errorf("calling to CreatorEntityClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CreatorEntityCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CreatorEntityCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CreatorEntity.
func (c *CreatorEntityClient) Update() *CreatorEntityUpdate {
	mutation := newCreatorEntityMutation(c.config, OpUpdate)
	return &CreatorEntityUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CreatorEntityClient) UpdateOne(_m *CreatorEntity) *CreatorEntityUpdateOne {
	mutation := newCreatorEntityMutation(c.config, OpUpdateOne, withCreatorEntity(_m))
	return &CreatorEntityUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CreatorEntityClient) UpdateOneID(id resource.CID) *CreatorEntityUpdateOne {
	mutation := newCreatorEntityMutation(c.config, OpUpdateOne, withCreatorEntityID(id))
	return &CreatorEntityUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CreatorEntity.
func (c *CreatorEntityClient) Delete() *CreatorEntityDelete {
	mutation := newCreatorEntityMutation(c.config, OpDelete)
	return &CreatorEntityDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CreatorEntityClient) DeleteOne(_m *CreatorEntity) *CreatorEntityDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CreatorEntityClient) DeleteOneID(id resource.CID) *CreatorEntityDeleteOne {
	builder := c.Delete().Where(creatorentity.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CreatorEntityDeleteOne{builder}
}

// Query returns a query builder for CreatorEntity.
func (c *CreatorEntityClient) Query() *CreatorEntityQuery {
	return &CreatorEntityQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCreatorEntity},
		inters: c.Interceptors(),
	}
}

// Get returns a CreatorEntity entity by its id.
func (c *CreatorEntityClient) Get(ctx context.Context, id resource.CID) (*CreatorEntity, error) {
	return c.Query().Where(creatorentity.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CreatorEntityClient) GetX(ctx context.Context, id resource.CID) *CreatorEntity {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRecords queries the records edge of a CreatorEntity.
func (c *CreatorEntityClient) QueryRecords(_m *CreatorEntity) *RecordEntityQuery {
	query := (&RecordEntityClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(creatorentity.Table, creatorentity.FieldID, id),
			sqlgraph.To(recordentity.Table, recordentity.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, creatorentity.RecordsTable, creatorentity.RecordsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CreatorEntityClient) Hooks() []Hook {
	return c.hooks.CreatorEntity
}

// Interceptors returns the client interceptors.
func (c *CreatorEntityClient) Interceptors() []Interceptor {
	return c.inters.CreatorEntity
}

func (c *CreatorEntityClient) mutate(ctx context.Context, m *CreatorEntityMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CreatorEntityCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CreatorEntityUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CreatorEntityUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CreatorEntityDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CreatorEntity mutation op: %q", m.Op())
	}
}

// RecordEntityClient is a client for the RecordEntity schema.
type RecordEntityClient struct {
	config
}

// NewRecordEntityClient returns a client for the RecordEntity from the given config.
func NewRecordEntityClient(c config) *RecordEntityClient {
	return &RecordEntityClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `recordentity.Hooks(f(g(h())))`.
func (c *RecordEntityClient) Use(hooks ...Hook) {
	c.hooks.RecordEntity = append(c.hooks.RecordEntity, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `recordentity.Intercept(f(g(h())))`.
func (c *RecordEntityClient) Intercept(interceptors ...Interceptor) {
	c.inters.RecordEntity = append(c.inters.RecordEntity, interceptors...)
}

// Create returns a builder for creating a RecordEntity entity.
func (c *RecordEntityClient) Create() *RecordEntityCreate {
	mutation := newRecordEntityMutation(c.config, OpCreate)
	return &RecordEntityCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RecordEntity entities.
func (c *RecordEntityClient) CreateBulk(builders ...*RecordEntityCreate) *RecordEntityCreateBulk {
	return &RecordEntityCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RecordEntityClient) MapCreateBulk(slice any, setFunc func(*RecordEntityCreate, int)) *RecordEntityCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RecordEntityCreateBulk{err: fmt.Errorf("calling to RecordEntityClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RecordEntityCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RecordEntityCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RecordEntity.
func (c *RecordEntityClient) Update() *RecordEntityUpdate {
	mutation := newRecordEntityMutation(c.config, OpUpdate)
	return &RecordEntityUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RecordEntityClient) UpdateOne(_m *RecordEntity) *RecordEntityUpdateOne {
	mutation := newRecordEntityMutation(c.config, OpUpdateOne, withRecordEntity(_m))
	return &RecordEntityUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RecordEntityClient) UpdateOneID(id resource.RID) *RecordEntityUpdateOne {
	mutation := newRecordEntityMutation(c.config, OpUpdateOne, withRecordEntityID(id))
	return &RecordEntityUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RecordEntity.
func (c *RecordEntityClient) Delete() *RecordEntityDelete {
	mutation := newRecordEntityMutation(c.config, OpDelete)
	return &RecordEntityDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RecordEntityClient) DeleteOne(_m *RecordEntity) *RecordEntityDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RecordEntityClient) DeleteOneID(id resource.RID) *RecordEntityDeleteOne {
	builder := c.Delete().Where(recordentity.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RecordEntityDeleteOne{builder}
}

// Query returns a query builder for RecordEntity.
func (c *RecordEntityClient) Query() *RecordEntityQuery {
	return &RecordEntityQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRecordEntity},
		inters: c.Interceptors(),
	}
}

// Get returns a RecordEntity entity by its id.
func (c *RecordEntityClient) Get(ctx context.Context, id resource.RID) (*RecordEntity, error) {
	return c.Query().Where(recordentity.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RecordEntityClient) GetX(ctx context.Context, id resource.RID) *RecordEntity {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTags queries the tags edge of a RecordEntity.
func (c *RecordEntityClient) QueryTags(_m *RecordEntity) *TagEntityQuery {
	query := (&TagEntityClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(recordentity.Table, recordentity.FieldID, id),
			sqlgraph.To(tagentity.Table, tagentity.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, recordentity.TagsTable, recordentity.TagsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCreator queries the creator edge of a RecordEntity.
func (c *RecordEntityClient) QueryCreator(_m *RecordEntity) *CreatorEntityQuery {
	query := (&CreatorEntityClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(recordentity.Table, recordentity.FieldID, id),
			sqlgraph.To(creatorentity.Table, creatorentity.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, recordentity.CreatorTable, recordentity.CreatorColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RecordEntityClient) Hooks() []Hook {
	return c.hooks.RecordEntity
}

// Interceptors returns the client interceptors.
func (c *RecordEntityClient) Interceptors() []Interceptor {
	return c.inters.RecordEntity
}

func (c *RecordEntityClient) mutate(ctx context.Context, m *RecordEntityMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RecordEntityCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RecordEntityUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RecordEntityUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RecordEntityDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RecordEntity mutation op: %q", m.Op())
	}
}

// TagEntityClient is a client for the TagEntity schema.
type TagEntityClient struct {
	config
}

// NewTagEntityClient returns a client for the TagEntity from the given config.
func NewTagEntityClient(c config) *TagEntityClient {
	return &TagEntityClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tagentity.Hooks(f(g(h())))`.
func (c *TagEntityClient) Use(hooks ...Hook) {
	c.hooks.TagEntity = append(c.hooks.TagEntity, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `tagentity.Intercept(f(g(h())))`.
func (c *TagEntityClient) Intercept(interceptors ...Interceptor) {
	c.inters.TagEntity = append(c.inters.TagEntity, interceptors...)
}

// Create returns a builder for creating a TagEntity entity.
func (c *TagEntityClient) Create() *TagEntityCreate {
	mutation := newTagEntityMutation(c.config, OpCreate)
	return &TagEntityCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TagEntity entities.
func (c *TagEntityClient) CreateBulk(builders ...*TagEntityCreate) *TagEntityCreateBulk {
	return &TagEntityCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TagEntityClient) MapCreateBulk(slice any, setFunc func(*TagEntityCreate, int)) *TagEntityCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TagEntityCreateBulk{err: fmt.Errorf("calling to TagEntityClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TagEntityCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TagEntityCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TagEntity.
func (c *TagEntityClient) Update() *TagEntityUpdate {
	mutation := newTagEntityMutation(c.config, OpUpdate)
	return &TagEntityUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TagEntityClient) UpdateOne(_m *TagEntity) *TagEntityUpdateOne {
	mutation := newTagEntityMutation(c.config, OpUpdateOne, withTagEntity(_m))
	return &TagEntityUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TagEntityClient) UpdateOneID(id resource.TID) *TagEntityUpdateOne {
	mutation := newTagEntityMutation(c.config, OpUpdateOne, withTagEntityID(id))
	return &TagEntityUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TagEntity.
func (c *TagEntityClient) Delete() *TagEntityDelete {
	mutation := newTagEntityMutation(c.config, OpDelete)
	return &TagEntityDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TagEntityClient) DeleteOne(_m *TagEntity) *TagEntityDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TagEntityClient) DeleteOneID(id resource.TID) *TagEntityDeleteOne {
	builder := c.Delete().Where(tagentity.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TagEntityDeleteOne{builder}
}

// Query returns a query builder for TagEntity.
func (c *TagEntityClient) Query() *TagEntityQuery {
	return &TagEntityQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTagEntity},
		inters: c.Interceptors(),
	}
}

// Get returns a TagEntity entity by its id.
func (c *TagEntityClient) Get(ctx context.Context, id resource.TID) (*TagEntity, error) {
	return c.Query().Where(tagentity.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TagEntityClient) GetX(ctx context.Context, id resource.TID) *TagEntity {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRecords queries the records edge of a TagEntity.
func (c *TagEntityClient) QueryRecords(_m *TagEntity) *RecordEntityQuery {
	query := (&RecordEntityClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tagentity.Table, tagentity.FieldID, id),
			sqlgraph.To(recordentity.Table, recordentity.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, tagentity.RecordsTable, tagentity.RecordsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TagEntityClient) Hooks() []Hook {
	return c.hooks.TagEntity
}

// Interceptors returns the client interceptors.
func (c *TagEntityClient) Interceptors() []Interceptor {
	return c.inters.TagEntity
}

func (c *TagEntityClient) mutate(ctx context.Context, m *TagEntityMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TagEntityCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TagEntityUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TagEntityUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TagEntityDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TagEntity mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		CreatorEntity, RecordEntity, TagEntity []ent.Hook
	}
	inters struct {
		CreatorEntity, RecordEntity, TagEntity []ent.Interceptor
	}
)
