// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/r3dpixel/card-client/store/record/erecord/ent/creatorentity"
	"github.com/r3dpixel/card-client/store/resource"
	"github.com/r3dpixel/card-fetcher/source"
)

// CreatorEntity is the model entity for the CreatorEntity schema.
type CreatorEntity struct {
	config `json:"-"`
	// ID of the ent.
	// ID of the creator
	ID resource.CID `json:"id,omitempty"`
	// Nickname of the creator
	Nickname string `json:"nickname,omitempty"`
	// Username of the creator
	Username string `json:"username,omitempty"`
	// Platform ID of the creator
	PlatformID string `json:"platform_id,omitempty"`
	// SOURCE (ChubAI, WyvernChat, etc...)
	Source source.ID `json:"source,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CreatorEntityQuery when eager-loading is set.
	Edges        CreatorEntityEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CreatorEntityEdges holds the relations/edges for other nodes in the graph.
type CreatorEntityEdges struct {
	// Records holds the value of the records edge.
	Records []*RecordEntity `json:"records,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RecordsOrErr returns the Records value or an error if the edge
// was not loaded in eager-loading.
func (e CreatorEntityEdges) RecordsOrErr() ([]*RecordEntity, error) {
	if e.loadedTypes[0] {
		return e.Records, nil
	}
	return nil, &NotLoadedError{edge: "records"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CreatorEntity) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case creatorentity.FieldID, creatorentity.FieldNickname, creatorentity.FieldUsername, creatorentity.FieldPlatformID, creatorentity.FieldSource:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CreatorEntity fields.
func (_m *CreatorEntity) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case creatorentity.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = resource.CID(value.String)
			}
		case creatorentity.FieldNickname:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nickname", values[i])
			} else if value.Valid {
				_m.Nickname = value.String
			}
		case creatorentity.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case creatorentity.FieldPlatformID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform_id", values[i])
			} else if value.Valid {
				_m.PlatformID = value.String
			}
		case creatorentity.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = source.ID(value.String)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CreatorEntity.
// This includes values selected through modifiers, order, etc.
func (_m *CreatorEntity) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRecords queries the "records" edge of the CreatorEntity entity.
func (_m *CreatorEntity) QueryRecords() *RecordEntityQuery {
	return NewCreatorEntityClient(_m.config).QueryRecords(_m)
}

// Update returns a builder for updating this CreatorEntity.
// Note that you need to call CreatorEntity.Unwrap() before calling this method if this CreatorEntity
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CreatorEntity) Update() *CreatorEntityUpdateOne {
	return NewCreatorEntityClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CreatorEntity entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CreatorEntity) Unwrap() *CreatorEntity {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CreatorEntity is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CreatorEntity) String() string {
	var builder strings.Builder
	builder.WriteString("CreatorEntity(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("nickname=")
	builder.WriteString(_m.Nickname)
	builder.WriteString(", ")
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("platform_id=")
	builder.WriteString(_m.PlatformID)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(fmt.Sprintf("%v", _m.Source))
	builder.WriteByte(')')
	return builder.String()
}

// CreatorEntities is a parsable slice of CreatorEntity.
type CreatorEntities []*CreatorEntity
