// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/digital-foxy/card-client/store/record/erecord/ent/creatorentity"
	"github.com/digital-foxy/card-client/store/record/erecord/ent/predicate"
	"github.com/digital-foxy/card-client/store/record/erecord/ent/recordentity"
	"github.com/digital-foxy/card-client/store/resource"
)

// CreatorEntityQuery is the builder for querying CreatorEntity entities.
type CreatorEntityQuery struct {
	config
	ctx         *QueryContext
	order       []creatorentity.OrderOption
	inters      []Interceptor
	predicates  []predicate.CreatorEntity
	withRecords *RecordEntityQuery
	modifiers   []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CreatorEntityQuery builder.
func (_q *CreatorEntityQuery) Where(ps ...predicate.CreatorEntity) *CreatorEntityQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *CreatorEntityQuery) Limit(limit int) *CreatorEntityQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *CreatorEntityQuery) Offset(offset int) *CreatorEntityQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *CreatorEntityQuery) Unique(unique bool) *CreatorEntityQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *CreatorEntityQuery) Order(o ...creatorentity.OrderOption) *CreatorEntityQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryRecords chains the current query on the "records" edge.
func (_q *CreatorEntityQuery) QueryRecords() *RecordEntityQuery {
	query := (&RecordEntityClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(creatorentity.Table, creatorentity.FieldID, selector),
			sqlgraph.To(recordentity.Table, recordentity.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, creatorentity.RecordsTable, creatorentity.RecordsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CreatorEntity entity from the query.
// Returns a *NotFoundError when no CreatorEntity was found.
func (_q *CreatorEntityQuery) First(ctx context.Context) (*CreatorEntity, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{creatorentity.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *CreatorEntityQuery) FirstX(ctx context.Context) *CreatorEntity {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CreatorEntity ID from the query.
// Returns a *NotFoundError when no CreatorEntity ID was found.
func (_q *CreatorEntityQuery) FirstID(ctx context.Context) (id resource.CID, err error) {
	var ids []resource.CID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{creatorentity.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *CreatorEntityQuery) FirstIDX(ctx context.Context) resource.CID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CreatorEntity entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CreatorEntity entity is found.
// Returns a *NotFoundError when no CreatorEntity entities are found.
func (_q *CreatorEntityQuery) Only(ctx context.Context) (*CreatorEntity, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{creatorentity.Label}
	default:
		return nil, &NotSingularError{creatorentity.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *CreatorEntityQuery) OnlyX(ctx context.Context) *CreatorEntity {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CreatorEntity ID in the query.
// Returns a *NotSingularError when more than one CreatorEntity ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *CreatorEntityQuery) OnlyID(ctx context.Context) (id resource.CID, err error) {
	var ids []resource.CID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{creatorentity.Label}
	default:
		err = &NotSingularError{creatorentity.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *CreatorEntityQuery) OnlyIDX(ctx context.Context) resource.CID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CreatorEntities.
func (_q *CreatorEntityQuery) All(ctx context.Context) ([]*CreatorEntity, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CreatorEntity, *CreatorEntityQuery]()
	return withInterceptors[[]*CreatorEntity](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *CreatorEntityQuery) AllX(ctx context.Context) []*CreatorEntity {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CreatorEntity IDs.
func (_q *CreatorEntityQuery) IDs(ctx context.Context) (ids []resource.CID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(creatorentity.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *CreatorEntityQuery) IDsX(ctx context.Context) []resource.CID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *CreatorEntityQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*CreatorEntityQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *CreatorEntityQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *CreatorEntityQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *CreatorEntityQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CreatorEntityQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *CreatorEntityQuery) Clone() *CreatorEntityQuery {
	if _q == nil {
		return nil
	}
	return &CreatorEntityQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]creatorentity.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.CreatorEntity{}, _q.predicates...),
		withRecords: _q.withRecords.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithRecords tells the query-builder to eager-load the nodes that are connected to
// the "records" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CreatorEntityQuery) WithRecords(opts ...func(*RecordEntityQuery)) *CreatorEntityQuery {
	query := (&RecordEntityClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRecords = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Nickname string `json:"nickname,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CreatorEntity.Query().
//		GroupBy(creatorentity.FieldNickname).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *CreatorEntityQuery) GroupBy(field string, fields ...string) *CreatorEntityGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CreatorEntityGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = creatorentity.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Nickname string `json:"nickname,omitempty"`
//	}
//
//	client.CreatorEntity.Query().
//		Select(creatorentity.FieldNickname).
//		Scan(ctx, &v)
func (_q *CreatorEntityQuery) Select(fields ...string) *CreatorEntitySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &CreatorEntitySelect{CreatorEntityQuery: _q}
	sbuild.label = creatorentity.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CreatorEntitySelect configured with the given aggregations.
func (_q *CreatorEntityQuery) Aggregate(fns ...AggregateFunc) *CreatorEntitySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *CreatorEntityQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !creatorentity.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *CreatorEntityQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CreatorEntity, error) {
	var (
		nodes       = []*CreatorEntity{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withRecords != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CreatorEntity).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CreatorEntity{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withRecords; query != nil {
		if err := _q.loadRecords(ctx, query, nodes,
			func(n *CreatorEntity) { n.Edges.Records = []*RecordEntity{} },
			func(n *CreatorEntity, e *RecordEntity) { n.Edges.Records = append(n.Edges.Records, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *CreatorEntityQuery) loadRecords(ctx context.Context, query *RecordEntityQuery, nodes []*CreatorEntity, init func(*CreatorEntity), assign func(*CreatorEntity, *RecordEntity)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[resource.CID]*CreatorEntity)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(recordentity.FieldCreatorID)
	}
	query.Where(predicate.RecordEntity(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(creatorentity.RecordsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CreatorID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "creator_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *CreatorEntityQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *CreatorEntityQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(creatorentity.Table, creatorentity.Columns, sqlgraph.NewFieldSpec(creatorentity.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, creatorentity.FieldID)
		for i := range fields {
			if fields[i] != creatorentity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *CreatorEntityQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(creatorentity.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = creatorentity.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *CreatorEntityQuery) Modify(modifiers ...func(s *sql.Selector)) *CreatorEntitySelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// CreatorEntityGroupBy is the group-by builder for CreatorEntity entities.
type CreatorEntityGroupBy struct {
	selector
	build *CreatorEntityQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *CreatorEntityGroupBy) Aggregate(fns ...AggregateFunc) *CreatorEntityGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *CreatorEntityGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CreatorEntityQuery, *CreatorEntityGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *CreatorEntityGroupBy) sqlScan(ctx context.Context, root *CreatorEntityQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CreatorEntitySelect is the builder for selecting fields of CreatorEntity entities.
type CreatorEntitySelect struct {
	*CreatorEntityQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *CreatorEntitySelect) Aggregate(fns ...AggregateFunc) *CreatorEntitySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *CreatorEntitySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CreatorEntityQuery, *CreatorEntitySelect](ctx, _s.CreatorEntityQuery, _s, _s.inters, v)
}

func (_s *CreatorEntitySelect) sqlScan(ctx context.Context, root *CreatorEntityQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *CreatorEntitySelect) Modify(modifiers ...func(s *sql.Selector)) *CreatorEntitySelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
