// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/digital-foxy/card-client/store/record/erecord/ent/creatorentity"
	"github.com/digital-foxy/card-client/store/record/erecord/ent/recordentity"
	"github.com/digital-foxy/card-client/store/resource"
	"github.com/digital-foxy/card-fetcher/source"
)

// CreatorEntityCreate is the builder for creating a CreatorEntity entity.
type CreatorEntityCreate struct {
	config
	mutation *CreatorEntityMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetNickname sets the "nickname" field.
func (_c *CreatorEntityCreate) SetNickname(v string) *CreatorEntityCreate {
	_c.mutation.SetNickname(v)
	return _c
}

// SetUsername sets the "username" field.
func (_c *CreatorEntityCreate) SetUsername(v string) *CreatorEntityCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetPlatformID sets the "platform_id" field.
func (_c *CreatorEntityCreate) SetPlatformID(v string) *CreatorEntityCreate {
	_c.mutation.SetPlatformID(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *CreatorEntityCreate) SetSource(v source.ID) *CreatorEntityCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetID sets the "id" field.
func (_c *CreatorEntityCreate) SetID(v resource.CID) *CreatorEntityCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddRecordIDs adds the "records" edge to the RecordEntity entity by IDs.
func (_c *CreatorEntityCreate) AddRecordIDs(ids ...resource.RID) *CreatorEntityCreate {
	_c.mutation.AddRecordIDs(ids...)
	return _c
}

// AddRecords adds the "records" edges to the RecordEntity entity.
func (_c *CreatorEntityCreate) AddRecords(v ...*RecordEntity) *CreatorEntityCreate {
	ids := make([]resource.RID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRecordIDs(ids...)
}

// Mutation returns the CreatorEntityMutation object of the builder.
func (_c *CreatorEntityCreate) Mutation() *CreatorEntityMutation {
	return _c.mutation
}

// Save creates the CreatorEntity in the database.
func (_c *CreatorEntityCreate) Save(ctx context.Context) (*CreatorEntity, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CreatorEntityCreate) SaveX(ctx context.Context) *CreatorEntity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CreatorEntityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CreatorEntityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CreatorEntityCreate) check() error {
	if _, ok := _c.mutation.Nickname(); !ok {
		return &ValidationError{Name: "nickname", err: errors.New(`ent: missing required field "CreatorEntity.nickname"`)}
	}
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "CreatorEntity.username"`)}
	}
	if _, ok := _c.mutation.PlatformID(); !ok {
		return &ValidationError{Name: "platform_id", err: errors.New(`ent: missing required field "CreatorEntity.platform_id"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "CreatorEntity.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := creatorentity.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "CreatorEntity.source": %w`, err)}
		}
	}
	return nil
}

func (_c *CreatorEntityCreate) sqlSave(ctx context.Context) (*CreatorEntity, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = resource.CID(id)
		} else {
			return nil, fmt.Errorf("unexpected CreatorEntity.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CreatorEntityCreate) createSpec() (*CreatorEntity, *sqlgraph.CreateSpec) {
	var (
		_node = &CreatorEntity{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(creatorentity.Table, sqlgraph.NewFieldSpec(creatorentity.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Nickname(); ok {
		_spec.SetField(creatorentity.FieldNickname, field.TypeString, value)
		_node.Nickname = value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(creatorentity.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.PlatformID(); ok {
		_spec.SetField(creatorentity.FieldPlatformID, field.TypeString, value)
		_node.PlatformID = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(creatorentity.FieldSource, field.TypeEnum, value)
		_node.Source = value
	}
	if nodes := _c.mutation.RecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   creatorentity.RecordsTable,
			Columns: []string{creatorentity.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recordentity.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CreatorEntity.Create().
//		SetNickname(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CreatorEntityUpsert) {
//			SetNickname(v+v).
//		}).
//		Exec(ctx)
func (_c *CreatorEntityCreate) OnConflict(opts ...sql.ConflictOption) *CreatorEntityUpsertOne {
	_c.conflict = opts
	return &CreatorEntityUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CreatorEntity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CreatorEntityCreate) OnConflictColumns(columns ...string) *CreatorEntityUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CreatorEntityUpsertOne{
		create: _c,
	}
}

type (
	// CreatorEntityUpsertOne is the builder for "upsert"-ing
	//  one CreatorEntity node.
	CreatorEntityUpsertOne struct {
		create *CreatorEntityCreate
	}

	// CreatorEntityUpsert is the "OnConflict" setter.
	CreatorEntityUpsert struct {
		*sql.UpdateSet
	}
)

// SetNickname sets the "nickname" field.
func (u *CreatorEntityUpsert) SetNickname(v string) *CreatorEntityUpsert {
	u.Set(creatorentity.FieldNickname, v)
	return u
}

// UpdateNickname sets the "nickname" field to the value that was provided on create.
func (u *CreatorEntityUpsert) UpdateNickname() *CreatorEntityUpsert {
	u.SetExcluded(creatorentity.FieldNickname)
	return u
}

// SetUsername sets the "username" field.
func (u *CreatorEntityUpsert) SetUsername(v string) *CreatorEntityUpsert {
	u.Set(creatorentity.FieldUsername, v)
	return u
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *CreatorEntityUpsert) UpdateUsername() *CreatorEntityUpsert {
	u.SetExcluded(creatorentity.FieldUsername)
	return u
}

// SetPlatformID sets the "platform_id" field.
func (u *CreatorEntityUpsert) SetPlatformID(v string) *CreatorEntityUpsert {
	u.Set(creatorentity.FieldPlatformID, v)
	return u
}

// UpdatePlatformID sets the "platform_id" field to the value that was provided on create.
func (u *CreatorEntityUpsert) UpdatePlatformID() *CreatorEntityUpsert {
	u.SetExcluded(creatorentity.FieldPlatformID)
	return u
}

// SetSource sets the "source" field.
func (u *CreatorEntityUpsert) SetSource(v source.ID) *CreatorEntityUpsert {
	u.Set(creatorentity.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *CreatorEntityUpsert) UpdateSource() *CreatorEntityUpsert {
	u.SetExcluded(creatorentity.FieldSource)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.CreatorEntity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(creatorentity.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CreatorEntityUpsertOne) UpdateNewValues() *CreatorEntityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(creatorentity.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CreatorEntity.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CreatorEntityUpsertOne) Ignore() *CreatorEntityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CreatorEntityUpsertOne) DoNothing() *CreatorEntityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CreatorEntityCreate.OnConflict
// documentation for more info.
func (u *CreatorEntityUpsertOne) Update(set func(*CreatorEntityUpsert)) *CreatorEntityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CreatorEntityUpsert{UpdateSet: update})
	}))
	return u
}

// SetNickname sets the "nickname" field.
func (u *CreatorEntityUpsertOne) SetNickname(v string) *CreatorEntityUpsertOne {
	return u.Update(func(s *CreatorEntityUpsert) {
		s.SetNickname(v)
	})
}

// UpdateNickname sets the "nickname" field to the value that was provided on create.
func (u *CreatorEntityUpsertOne) UpdateNickname() *CreatorEntityUpsertOne {
	return u.Update(func(s *CreatorEntityUpsert) {
		s.UpdateNickname()
	})
}

// SetUsername sets the "username" field.
func (u *CreatorEntityUpsertOne) SetUsername(v string) *CreatorEntityUpsertOne {
	return u.Update(func(s *CreatorEntityUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *CreatorEntityUpsertOne) UpdateUsername() *CreatorEntityUpsertOne {
	return u.Update(func(s *CreatorEntityUpsert) {
		s.UpdateUsername()
	})
}

// SetPlatformID sets the "platform_id" field.
func (u *CreatorEntityUpsertOne) SetPlatformID(v string) *CreatorEntityUpsertOne {
	return u.Update(func(s *CreatorEntityUpsert) {
		s.SetPlatformID(v)
	})
}

// UpdatePlatformID sets the "platform_id" field to the value that was provided on create.
func (u *CreatorEntityUpsertOne) UpdatePlatformID() *CreatorEntityUpsertOne {
	return u.Update(func(s *CreatorEntityUpsert) {
		s.UpdatePlatformID()
	})
}

// SetSource sets the "source" field.
func (u *CreatorEntityUpsertOne) SetSource(v source.ID) *CreatorEntityUpsertOne {
	return u.Update(func(s *CreatorEntityUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *CreatorEntityUpsertOne) UpdateSource() *CreatorEntityUpsertOne {
	return u.Update(func(s *CreatorEntityUpsert) {
		s.UpdateSource()
	})
}

// Exec executes the query.
func (u *CreatorEntityUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CreatorEntityCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CreatorEntityUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CreatorEntityUpsertOne) ID(ctx context.Context) (id resource.CID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: CreatorEntityUpsertOne.ID is not supported by MySQL driver. Use CreatorEntityUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CreatorEntityUpsertOne) IDX(ctx context.Context) resource.CID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CreatorEntityCreateBulk is the builder for creating many CreatorEntity entities in bulk.
type CreatorEntityCreateBulk struct {
	config
	err      error
	builders []*CreatorEntityCreate
	conflict []sql.ConflictOption
}

// Save creates the CreatorEntity entities in the database.
func (_c *CreatorEntityCreateBulk) Save(ctx context.Context) ([]*CreatorEntity, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CreatorEntity, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CreatorEntityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CreatorEntityCreateBulk) SaveX(ctx context.Context) []*CreatorEntity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CreatorEntityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CreatorEntityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CreatorEntity.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CreatorEntityUpsert) {
//			SetNickname(v+v).
//		}).
//		Exec(ctx)
func (_c *CreatorEntityCreateBulk) OnConflict(opts ...sql.ConflictOption) *CreatorEntityUpsertBulk {
	_c.conflict = opts
	return &CreatorEntityUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CreatorEntity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CreatorEntityCreateBulk) OnConflictColumns(columns ...string) *CreatorEntityUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CreatorEntityUpsertBulk{
		create: _c,
	}
}

// CreatorEntityUpsertBulk is the builder for "upsert"-ing
// a bulk of CreatorEntity nodes.
type CreatorEntityUpsertBulk struct {
	create *CreatorEntityCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CreatorEntity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(creatorentity.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CreatorEntityUpsertBulk) UpdateNewValues() *CreatorEntityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(creatorentity.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CreatorEntity.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CreatorEntityUpsertBulk) Ignore() *CreatorEntityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CreatorEntityUpsertBulk) DoNothing() *CreatorEntityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CreatorEntityCreateBulk.OnConflict
// documentation for more info.
func (u *CreatorEntityUpsertBulk) Update(set func(*CreatorEntityUpsert)) *CreatorEntityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CreatorEntityUpsert{UpdateSet: update})
	}))
	return u
}

// SetNickname sets the "nickname" field.
func (u *CreatorEntityUpsertBulk) SetNickname(v string) *CreatorEntityUpsertBulk {
	return u.Update(func(s *CreatorEntityUpsert) {
		s.SetNickname(v)
	})
}

// UpdateNickname sets the "nickname" field to the value that was provided on create.
func (u *CreatorEntityUpsertBulk) UpdateNickname() *CreatorEntityUpsertBulk {
	return u.Update(func(s *CreatorEntityUpsert) {
		s.UpdateNickname()
	})
}

// SetUsername sets the "username" field.
func (u *CreatorEntityUpsertBulk) SetUsername(v string) *CreatorEntityUpsertBulk {
	return u.Update(func(s *CreatorEntityUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *CreatorEntityUpsertBulk) UpdateUsername() *CreatorEntityUpsertBulk {
	return u.Update(func(s *CreatorEntityUpsert) {
		s.UpdateUsername()
	})
}

// SetPlatformID sets the "platform_id" field.
func (u *CreatorEntityUpsertBulk) SetPlatformID(v string) *CreatorEntityUpsertBulk {
	return u.Update(func(s *CreatorEntityUpsert) {
		s.SetPlatformID(v)
	})
}

// UpdatePlatformID sets the "platform_id" field to the value that was provided on create.
func (u *CreatorEntityUpsertBulk) UpdatePlatformID() *CreatorEntityUpsertBulk {
	return u.Update(func(s *CreatorEntityUpsert) {
		s.UpdatePlatformID()
	})
}

// SetSource sets the "source" field.
func (u *CreatorEntityUpsertBulk) SetSource(v source.ID) *CreatorEntityUpsertBulk {
	return u.Update(func(s *CreatorEntityUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *CreatorEntityUpsertBulk) UpdateSource() *CreatorEntityUpsertBulk {
	return u.Update(func(s *CreatorEntityUpsert) {
		s.UpdateSource()
	})
}

// Exec executes the query.
func (u *CreatorEntityUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CreatorEntityCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CreatorEntityCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CreatorEntityUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
