// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/r3dpixel/card-client/store/record/erecord/ent/creatorentity"
	"github.com/r3dpixel/card-client/store/record/erecord/ent/recordentity"
	"github.com/r3dpixel/card-client/store/resource"
	"github.com/r3dpixel/card-fetcher/source"
	"github.com/r3dpixel/toolkit/timestamp"
)

// RecordEntity is the model entity for the RecordEntity schema.
type RecordEntity struct {
	config `json:"-"`
	// ID of the ent.
	// Auto-increment resource ID
	ID resource.RID `json:"id,omitempty"`
	// Import index inside batch
	ImportIndex int `json:"import_index,omitempty"`
	// Import timestamp
	ImportTime timestamp.Nano `json:"import_time,omitempty"`
	// SOURCE (ChubAI, WyvernChat, etc...)
	Source source.ID `json:"source,omitempty"`
	// Normalized card URL
	NormalizedURL string `json:"normalized_url,omitempty"`
	// Direct card URL
	DirectURL string `json:"direct_url,omitempty"`
	// Platform ID for card
	PlatformID string `json:"platform_id,omitempty"`
	// Character identifier from platform
	CharacterID string `json:"character_id,omitempty"`
	// Card title
	Title string `json:"title,omitempty"`
	// Character name
	Name string `json:"name,omitempty"`
	// Card creator/author ID
	CreatorID resource.CID `json:"creator_id,omitempty"`
	// Short description or tagline
	Tagline string `json:"tagline,omitempty"`
	// Card creation timestamp
	CreateTime timestamp.Nano `json:"create_time,omitempty"`
	// Last update timestamp
	UpdateTime timestamp.Nano `json:"update_time,omitempty"`
	// Book/collection update timestamp
	BookUpdateTime timestamp.Nano `json:"book_update_time,omitempty"`
	// Synchronization status
	SyncStatus resource.SyncStatus `json:"sync_status,omitempty"`
	// Last synchronization timestamp
	SyncTime timestamp.Nano `json:"sync_time,omitempty"`
	// Exported version timestamp
	ExportedVersion timestamp.Nano `json:"exported_version,omitempty"`
	// Last export timestamp
	ExportTime timestamp.Nano `json:"export_time,omitempty"`
	// Whether card is marked as favorite
	Favorite bool `json:"favorite,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RecordEntityQuery when eager-loading is set.
	Edges        RecordEntityEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RecordEntityEdges holds the relations/edges for other nodes in the graph.
type RecordEntityEdges struct {
	// Tags holds the value of the tags edge.
	Tags []*TagEntity `json:"tags,omitempty"`
	// Creator holds the value of the creator edge.
	Creator *CreatorEntity `json:"creator,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TagsOrErr returns the Tags value or an error if the edge
// was not loaded in eager-loading.
func (e RecordEntityEdges) TagsOrErr() ([]*TagEntity, error) {
	if e.loadedTypes[0] {
		return e.Tags, nil
	}
	return nil, &NotLoadedError{edge: "tags"}
}

// CreatorOrErr returns the Creator value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RecordEntityEdges) CreatorOrErr() (*CreatorEntity, error) {
	if e.Creator != nil {
		return e.Creator, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: creatorentity.Label}
	}
	return nil, &NotLoadedError{edge: "creator"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RecordEntity) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case recordentity.FieldFavorite:
			values[i] = new(sql.NullBool)
		case recordentity.FieldID, recordentity.FieldImportIndex, recordentity.FieldImportTime, recordentity.FieldCreateTime, recordentity.FieldUpdateTime, recordentity.FieldBookUpdateTime, recordentity.FieldSyncTime, recordentity.FieldExportedVersion, recordentity.FieldExportTime:
			values[i] = new(sql.NullInt64)
		case recordentity.FieldSource, recordentity.FieldNormalizedURL, recordentity.FieldDirectURL, recordentity.FieldPlatformID, recordentity.FieldCharacterID, recordentity.FieldTitle, recordentity.FieldName, recordentity.FieldCreatorID, recordentity.FieldTagline, recordentity.FieldSyncStatus:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RecordEntity fields.
func (_m *RecordEntity) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case recordentity.FieldID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = resource.RID(value.Int64)
			}
		case recordentity.FieldImportIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field import_index", values[i])
			} else if value.Valid {
				_m.ImportIndex = int(value.Int64)
			}
		case recordentity.FieldImportTime:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field import_time", values[i])
			} else if value.Valid {
				_m.ImportTime = timestamp.Nano(value.Int64)
			}
		case recordentity.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = source.ID(value.String)
			}
		case recordentity.FieldNormalizedURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field normalized_url", values[i])
			} else if value.Valid {
				_m.NormalizedURL = value.String
			}
		case recordentity.FieldDirectURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field direct_url", values[i])
			} else if value.Valid {
				_m.DirectURL = value.String
			}
		case recordentity.FieldPlatformID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform_id", values[i])
			} else if value.Valid {
				_m.PlatformID = value.String
			}
		case recordentity.FieldCharacterID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field character_id", values[i])
			} else if value.Valid {
				_m.CharacterID = value.String
			}
		case recordentity.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case recordentity.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case recordentity.FieldCreatorID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field creator_id", values[i])
			} else if value.Valid {
				_m.CreatorID = resource.CID(value.String)
			}
		case recordentity.FieldTagline:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tagline", values[i])
			} else if value.Valid {
				_m.Tagline = value.String
			}
		case recordentity.FieldCreateTime:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = timestamp.Nano(value.Int64)
			}
		case recordentity.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = timestamp.Nano(value.Int64)
			}
		case recordentity.FieldBookUpdateTime:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field book_update_time", values[i])
			} else if value.Valid {
				_m.BookUpdateTime = timestamp.Nano(value.Int64)
			}
		case recordentity.FieldSyncStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sync_status", values[i])
			} else if value.Valid {
				_m.SyncStatus = resource.SyncStatus(value.String)
			}
		case recordentity.FieldSyncTime:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sync_time", values[i])
			} else if value.Valid {
				_m.SyncTime = timestamp.Nano(value.Int64)
			}
		case recordentity.FieldExportedVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field exported_version", values[i])
			} else if value.Valid {
				_m.ExportedVersion = timestamp.Nano(value.Int64)
			}
		case recordentity.FieldExportTime:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field export_time", values[i])
			} else if value.Valid {
				_m.ExportTime = timestamp.Nano(value.Int64)
			}
		case recordentity.FieldFavorite:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field favorite", values[i])
			} else if value.Valid {
				_m.Favorite = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RecordEntity.
// This includes values selected through modifiers, order, etc.
func (_m *RecordEntity) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTags queries the "tags" edge of the RecordEntity entity.
func (_m *RecordEntity) QueryTags() *TagEntityQuery {
	return NewRecordEntityClient(_m.config).QueryTags(_m)
}

// QueryCreator queries the "creator" edge of the RecordEntity entity.
func (_m *RecordEntity) QueryCreator() *CreatorEntityQuery {
	return NewRecordEntityClient(_m.config).QueryCreator(_m)
}

// Update returns a builder for updating this RecordEntity.
// Note that you need to call RecordEntity.Unwrap() before calling this method if this RecordEntity
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RecordEntity) Update() *RecordEntityUpdateOne {
	return NewRecordEntityClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RecordEntity entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RecordEntity) Unwrap() *RecordEntity {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RecordEntity is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RecordEntity) String() string {
	var builder strings.Builder
	builder.WriteString("RecordEntity(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("import_index=")
	builder.WriteString(fmt.Sprintf("%v", _m.ImportIndex))
	builder.WriteString(", ")
	builder.WriteString("import_time=")
	builder.WriteString(fmt.Sprintf("%v", _m.ImportTime))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(fmt.Sprintf("%v", _m.Source))
	builder.WriteString(", ")
	builder.WriteString("normalized_url=")
	builder.WriteString(_m.NormalizedURL)
	builder.WriteString(", ")
	builder.WriteString("direct_url=")
	builder.WriteString(_m.DirectURL)
	builder.WriteString(", ")
	builder.WriteString("platform_id=")
	builder.WriteString(_m.PlatformID)
	builder.WriteString(", ")
	builder.WriteString("character_id=")
	builder.WriteString(_m.CharacterID)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("creator_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatorID))
	builder.WriteString(", ")
	builder.WriteString("tagline=")
	builder.WriteString(_m.Tagline)
	builder.WriteString(", ")
	builder.WriteString("create_time=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreateTime))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdateTime))
	builder.WriteString(", ")
	builder.WriteString("book_update_time=")
	builder.WriteString(fmt.Sprintf("%v", _m.BookUpdateTime))
	builder.WriteString(", ")
	builder.WriteString("sync_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.SyncStatus))
	builder.WriteString(", ")
	builder.WriteString("sync_time=")
	builder.WriteString(fmt.Sprintf("%v", _m.SyncTime))
	builder.WriteString(", ")
	builder.WriteString("exported_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExportedVersion))
	builder.WriteString(", ")
	builder.WriteString("export_time=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExportTime))
	builder.WriteString(", ")
	builder.WriteString("favorite=")
	builder.WriteString(fmt.Sprintf("%v", _m.Favorite))
	builder.WriteByte(')')
	return builder.String()
}

// RecordEntities is a parsable slice of RecordEntity.
type RecordEntities []*RecordEntity
