// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/digital-foxy/card-client/store/record/erecord/ent/recordentity"
	"github.com/digital-foxy/card-client/store/record/erecord/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	recordentityFields := schema.RecordEntity{}.Fields()
	_ = recordentityFields
	// recordentityDescIsFork is the schema descriptor for is_fork field.
	recordentityDescIsFork := recordentityFields[14].Descriptor()
	// recordentity.DefaultIsFork holds the default value on creation for the is_fork field.
	recordentity.DefaultIsFork = recordentityDescIsFork.Default.(bool)
	// recordentityDescGreetingsCount is the schema descriptor for greetings_count field.
	recordentityDescGreetingsCount := recordentityFields[16].Descriptor()
	// recordentity.DefaultGreetingsCount holds the default value on creation for the greetings_count field.
	recordentity.DefaultGreetingsCount = recordentityDescGreetingsCount.Default.(int)
}
