// Code generated by ent, DO NOT EDIT.

package creatorentity

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/r3dpixel/card-client/store/record/entrecord/ent/predicate"
	"github.com/r3dpixel/card-client/store/resource"
	"github.com/r3dpixel/card-fetcher/source"
)

// ID filters vertices based on their ID field.
func ID(id resource.CID) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id resource.CID) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id resource.CID) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...resource.CID) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...resource.CID) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id resource.CID) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id resource.CID) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id resource.CID) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id resource.CID) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldLTE(FieldID, id))
}

// Nickname applies equality check predicate on the "nickname" field. It's identical to NicknameEQ.
func Nickname(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldEQ(FieldNickname, v))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldEQ(FieldUsername, v))
}

// PlatformID applies equality check predicate on the "platform_id" field. It's identical to PlatformIDEQ.
func PlatformID(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldEQ(FieldPlatformID, v))
}

// NicknameEQ applies the EQ predicate on the "nickname" field.
func NicknameEQ(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldEQ(FieldNickname, v))
}

// NicknameNEQ applies the NEQ predicate on the "nickname" field.
func NicknameNEQ(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldNEQ(FieldNickname, v))
}

// NicknameIn applies the In predicate on the "nickname" field.
func NicknameIn(vs ...string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldIn(FieldNickname, vs...))
}

// NicknameNotIn applies the NotIn predicate on the "nickname" field.
func NicknameNotIn(vs ...string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldNotIn(FieldNickname, vs...))
}

// NicknameGT applies the GT predicate on the "nickname" field.
func NicknameGT(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldGT(FieldNickname, v))
}

// NicknameGTE applies the GTE predicate on the "nickname" field.
func NicknameGTE(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldGTE(FieldNickname, v))
}

// NicknameLT applies the LT predicate on the "nickname" field.
func NicknameLT(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldLT(FieldNickname, v))
}

// NicknameLTE applies the LTE predicate on the "nickname" field.
func NicknameLTE(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldLTE(FieldNickname, v))
}

// NicknameContains applies the Contains predicate on the "nickname" field.
func NicknameContains(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldContains(FieldNickname, v))
}

// NicknameHasPrefix applies the HasPrefix predicate on the "nickname" field.
func NicknameHasPrefix(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldHasPrefix(FieldNickname, v))
}

// NicknameHasSuffix applies the HasSuffix predicate on the "nickname" field.
func NicknameHasSuffix(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldHasSuffix(FieldNickname, v))
}

// NicknameEqualFold applies the EqualFold predicate on the "nickname" field.
func NicknameEqualFold(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldEqualFold(FieldNickname, v))
}

// NicknameContainsFold applies the ContainsFold predicate on the "nickname" field.
func NicknameContainsFold(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldContainsFold(FieldNickname, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldContainsFold(FieldUsername, v))
}

// PlatformIDEQ applies the EQ predicate on the "platform_id" field.
func PlatformIDEQ(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldEQ(FieldPlatformID, v))
}

// PlatformIDNEQ applies the NEQ predicate on the "platform_id" field.
func PlatformIDNEQ(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldNEQ(FieldPlatformID, v))
}

// PlatformIDIn applies the In predicate on the "platform_id" field.
func PlatformIDIn(vs ...string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldIn(FieldPlatformID, vs...))
}

// PlatformIDNotIn applies the NotIn predicate on the "platform_id" field.
func PlatformIDNotIn(vs ...string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldNotIn(FieldPlatformID, vs...))
}

// PlatformIDGT applies the GT predicate on the "platform_id" field.
func PlatformIDGT(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldGT(FieldPlatformID, v))
}

// PlatformIDGTE applies the GTE predicate on the "platform_id" field.
func PlatformIDGTE(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldGTE(FieldPlatformID, v))
}

// PlatformIDLT applies the LT predicate on the "platform_id" field.
func PlatformIDLT(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldLT(FieldPlatformID, v))
}

// PlatformIDLTE applies the LTE predicate on the "platform_id" field.
func PlatformIDLTE(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldLTE(FieldPlatformID, v))
}

// PlatformIDContains applies the Contains predicate on the "platform_id" field.
func PlatformIDContains(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldContains(FieldPlatformID, v))
}

// PlatformIDHasPrefix applies the HasPrefix predicate on the "platform_id" field.
func PlatformIDHasPrefix(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldHasPrefix(FieldPlatformID, v))
}

// PlatformIDHasSuffix applies the HasSuffix predicate on the "platform_id" field.
func PlatformIDHasSuffix(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldHasSuffix(FieldPlatformID, v))
}

// PlatformIDEqualFold applies the EqualFold predicate on the "platform_id" field.
func PlatformIDEqualFold(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldEqualFold(FieldPlatformID, v))
}

// PlatformIDContainsFold applies the ContainsFold predicate on the "platform_id" field.
func PlatformIDContainsFold(v string) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.FieldContainsFold(FieldPlatformID, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v source.ID) predicate.CreatorEntity {
	vc := v
	return predicate.CreatorEntity(sql.FieldEQ(FieldSource, vc))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v source.ID) predicate.CreatorEntity {
	vc := v
	return predicate.CreatorEntity(sql.FieldNEQ(FieldSource, vc))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...source.ID) predicate.CreatorEntity {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.CreatorEntity(sql.FieldIn(FieldSource, v...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...source.ID) predicate.CreatorEntity {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.CreatorEntity(sql.FieldNotIn(FieldSource, v...))
}

// HasRecords applies the HasEdge predicate on the "records" edge.
func HasRecords() predicate.CreatorEntity {
	return predicate.CreatorEntity(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, RecordsTable, RecordsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRecordsWith applies the HasEdge predicate on the "records" edge with a given conditions (other predicates).
func HasRecordsWith(preds ...predicate.RecordEntity) predicate.CreatorEntity {
	return predicate.CreatorEntity(func(s *sql.Selector) {
		step := newRecordsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CreatorEntity) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CreatorEntity) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CreatorEntity) predicate.CreatorEntity {
	return predicate.CreatorEntity(sql.NotPredicates(p))
}
