// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CreatorEntity is the predicate function for creatorentity builders.
type CreatorEntity func(*sql.Selector)

// RecordEntity is the predicate function for recordentity builders.
type RecordEntity func(*sql.Selector)

// TagEntity is the predicate function for tagentity builders.
type TagEntity func(*sql.Selector)
